var data = {lines:[
{"lineNum":"    1","line":"#!/usr/bin/env bash"},
{"lineNum":"    2","line":"#"},
{"lineNum":"    3","line":"# Recursively compares two directories and reports differences in existence,"},
{"lineNum":"    4","line":"# size, timestamps, and checksums. Reports missing directories at the top level"},
{"lineNum":"    5","line":"# rather than enumerating all their contents."},
{"lineNum":"    6","line":"#"},
{"lineNum":"    7","line":"# Usage:"},
{"lineNum":"    8","line":"#   ./compare-dirs.sh [OPTIONS] <dir1> <dir2>"},
{"lineNum":"    9","line":""},
{"lineNum":"   10","line":"set -o errexit","class":"lineCov","hits":"1","order":"3698",},
{"lineNum":"   11","line":"set -o nounset","class":"lineCov","hits":"1","order":"3660",},
{"lineNum":"   12","line":"set -o pipefail","class":"lineCov","hits":"1","order":"3657",},
{"lineNum":"   13","line":""},
{"lineNum":"   14","line":"# --- Shared Library ---"},
{"lineNum":"   15","line":"# shellcheck source=../../lib/colors.sh"},
{"lineNum":"   16","line":"source \"$(cd \"$(dirname \"$0\")\" && pwd -P)/../../lib/colors.sh\"","class":"lineCov","hits":"1","order":"3708",},
{"lineNum":"   17","line":"# @include ../../lib/colors.sh"},
{"lineNum":"   18","line":"# shellcheck source=../../lib/platform.sh"},
{"lineNum":"   19","line":"source \"$(cd \"$(dirname \"$0\")\" && pwd -P)/../../lib/platform.sh\"","class":"lineCov","hits":"1","order":"3678",},
{"lineNum":"   20","line":"# @include ../../lib/platform.sh"},
{"lineNum":"   21","line":"# shellcheck source=../../lib/cli.sh"},
{"lineNum":"   22","line":"source \"$(cd \"$(dirname \"$0\")\" && pwd -P)/../../lib/cli.sh\"","class":"lineCov","hits":"1","order":"3677",},
{"lineNum":"   23","line":"# @include ../../lib/cli.sh"},
{"lineNum":"   24","line":"# shellcheck source=../../lib/core.sh"},
{"lineNum":"   25","line":"source \"$(cd \"$(dirname \"$0\")\" && pwd -P)/../../lib/core.sh\"","class":"lineCov","hits":"1","order":"3647",},
{"lineNum":"   26","line":"# @include ../../lib/core.sh"},
{"lineNum":"   27","line":""},
{"lineNum":"   28","line":"# --- Global State ---"},
{"lineNum":"   29","line":"_opt_timestamps=false","class":"lineCov","hits":"1","order":"3704",},
{"lineNum":"   30","line":"_opt_checksums=false","class":"lineCov","hits":"1","order":"3684",},
{"lineNum":"   31","line":"_opt_no_color=false","class":"lineCov","hits":"1","order":"3681",},
{"lineNum":"   32","line":"_opt_ignore_case=false","class":"lineCov","hits":"1","order":"3696",},
{"lineNum":"   33","line":"_opt_no_dotfiles=false","class":"lineCov","hits":"1","order":"3796",},
{"lineNum":"   34","line":"_opt_excludes=()"},
{"lineNum":"   35","line":"_opt_excludes_left=()"},
{"lineNum":"   36","line":"_opt_excludes_right=()"},
{"lineNum":"   37","line":"_dir1=\"\"","class":"lineCov","hits":"1","order":"3733",},
{"lineNum":"   38","line":"_dir2=\"\"","class":"lineCov","hits":"1","order":"3727",},
{"lineNum":"   39","line":"_count_left_only=0","class":"lineCov","hits":"1","order":"3724",},
{"lineNum":"   40","line":"_count_right_only=0","class":"lineCov","hits":"1","order":"3719",},
{"lineNum":"   41","line":"_count_differences=0","class":"lineCov","hits":"1","order":"3741",},
{"lineNum":"   42","line":""},
{"lineNum":"   43","line":"# --- Color Variables (set by setup_colors \"${_opt_no_color}\") ---"},
{"lineNum":"   44","line":""},
{"lineNum":"   45","line":"########################################"},
{"lineNum":"   46","line":"# Prints the script\'s usage instructions."},
{"lineNum":"   47","line":"# Globals:"},
{"lineNum":"   48","line":"#   SCRIPT_NAME"},
{"lineNum":"   49","line":"########################################"},
{"lineNum":"   50","line":"show_usage() {"},
{"lineNum":"   51","line":"  cat <<EOF","class":"lineCov","hits":"1","order":"3687",},
{"lineNum":"   52","line":"Usage: ${SCRIPT_NAME} [OPTIONS] <dir1> <dir2>"},
{"lineNum":"   53","line":""},
{"lineNum":"   54","line":"Recursively compare two directories and report differences."},
{"lineNum":"   55","line":""},
{"lineNum":"   56","line":"Options:"},
{"lineNum":"   57","line":"  -t, --timestamps         Also compare file modification times"},
{"lineNum":"   58","line":"  -c, --checksums          Also compare file checksums (sha256)"},
{"lineNum":"   59","line":"  -i, --ignore-case        Case-insensitive filename matching"},
{"lineNum":"   60","line":"  -d, --no-dotfiles        Skip hidden (dot) files and directories"},
{"lineNum":"   61","line":"  -x, --exclude PAT        Skip entries matching glob pattern (repeatable)"},
{"lineNum":"   62","line":"      --exclude-left PAT   Suppress LEFT-only reports for matches (repeatable)"},
{"lineNum":"   63","line":"      --exclude-right PAT  Suppress RIGHT-only reports for matches (repeatable)"},
{"lineNum":"   64","line":"  -n, --no-color           Disable colored output"},
{"lineNum":"   65","line":"  -h, --help               Show this help message"},
{"lineNum":"   66","line":""},
{"lineNum":"   67","line":"Output markers:"},
{"lineNum":"   68","line":"  ←  Item exists only in LEFT directory"},
{"lineNum":"   69","line":"  →  Item exists only in RIGHT directory"},
{"lineNum":"   70","line":"  ≠  Item differs between directories"},
{"lineNum":"   71","line":"  ⚡ Type mismatch (e.g., file vs directory)"},
{"lineNum":"   72","line":"EOF"},
{"lineNum":"   73","line":"}"},
{"lineNum":"   74","line":""},
{"lineNum":"   75","line":"########################################"},
{"lineNum":"   76","line":"# Parses command-line arguments into global option flags."},
{"lineNum":"   77","line":"# Supports long options and combined short options (e.g., -tc)."},
{"lineNum":"   78","line":"# Globals:"},
{"lineNum":"   79","line":"#   _opt_timestamps, _opt_checksums, _opt_no_color, _opt_ignore_case,"},
{"lineNum":"   80","line":"#   _opt_no_dotfiles, _opt_excludes, _opt_excludes_left, _opt_excludes_right,"},
{"lineNum":"   81","line":"#   _dir1, _dir2"},
{"lineNum":"   82","line":"# Arguments:"},
{"lineNum":"   83","line":"#   Command-line arguments passed to the script."},
{"lineNum":"   84","line":"########################################"},
{"lineNum":"   85","line":"parse_options() {"},
{"lineNum":"   86","line":"  local positional=()","class":"lineCov","hits":"1","order":"3737",},
{"lineNum":"   87","line":""},
{"lineNum":"   88","line":"  while [[ $# -gt 0 ]]; do","class":"lineCov","hits":"1","order":"3702",},
{"lineNum":"   89","line":"    case \"$1\" in","class":"lineCov","hits":"1","order":"3682",},
{"lineNum":"   90","line":"      -t|--timestamps)"},
{"lineNum":"   91","line":"        _opt_timestamps=true","class":"lineCov","hits":"1","order":"3694",},
{"lineNum":"   92","line":"        shift","class":"lineCov","hits":"1","order":"3739",},
{"lineNum":"   93","line":"        ;;"},
{"lineNum":"   94","line":"      -c|--checksums)"},
{"lineNum":"   95","line":"        _opt_checksums=true","class":"lineCov","hits":"1","order":"3778",},
{"lineNum":"   96","line":"        shift","class":"lineCov","hits":"1","order":"3736",},
{"lineNum":"   97","line":"        ;;"},
{"lineNum":"   98","line":"      -i|--ignore-case)"},
{"lineNum":"   99","line":"        _opt_ignore_case=true","class":"lineCov","hits":"1","order":"3715",},
{"lineNum":"  100","line":"        shift","class":"lineCov","hits":"1","order":"3745",},
{"lineNum":"  101","line":"        ;;"},
{"lineNum":"  102","line":"      -d|--no-dotfiles)"},
{"lineNum":"  103","line":"        _opt_no_dotfiles=true","class":"lineCov","hits":"1","order":"3711",},
{"lineNum":"  104","line":"        shift","class":"lineCov","hits":"1","order":"3749",},
{"lineNum":"  105","line":"        ;;"},
{"lineNum":"  106","line":"      -x|--exclude)"},
{"lineNum":"  107","line":"        _opt_excludes+=(\"$2\")","class":"lineCov","hits":"1","order":"3675",},
{"lineNum":"  108","line":"        shift 2","class":"lineCov","hits":"1","order":"3674",},
{"lineNum":"  109","line":"        ;;"},
{"lineNum":"  110","line":"      --exclude-left)"},
{"lineNum":"  111","line":"        _opt_excludes_left+=(\"$2\")","class":"lineCov","hits":"1","order":"3673",},
{"lineNum":"  112","line":"        shift 2","class":"lineCov","hits":"1","order":"3672",},
{"lineNum":"  113","line":"        ;;"},
{"lineNum":"  114","line":"      --exclude-right)"},
{"lineNum":"  115","line":"        _opt_excludes_right+=(\"$2\")","class":"lineCov","hits":"1","order":"3671",},
{"lineNum":"  116","line":"        shift 2","class":"lineCov","hits":"1","order":"3670",},
{"lineNum":"  117","line":"        ;;"},
{"lineNum":"  118","line":"      -n|--no-color)"},
{"lineNum":"  119","line":"        _opt_no_color=true","class":"lineCov","hits":"1","order":"3669",},
{"lineNum":"  120","line":"        shift","class":"lineCov","hits":"1","order":"3666",},
{"lineNum":"  121","line":"        ;;"},
{"lineNum":"  122","line":"      -h|--help)"},
{"lineNum":"  123","line":"        show_usage","class":"lineCov","hits":"1","order":"3664",},
{"lineNum":"  124","line":"        exit 0","class":"lineCov","hits":"1","order":"3662",},
{"lineNum":"  125","line":"        ;;"},
{"lineNum":"  126","line":"      --)"},
{"lineNum":"  127","line":"        shift","class":"lineCov","hits":"1","order":"3661",},
{"lineNum":"  128","line":"        positional+=(\"$@\")","class":"lineCov","hits":"1","order":"3809",},
{"lineNum":"  129","line":"        break","class":"lineCov","hits":"1","order":"3791",},
{"lineNum":"  130","line":"        ;;"},
{"lineNum":"  131","line":"      --*)"},
{"lineNum":"  132","line":"        # Caught before the combined-flag arm below, which strips one dash and reads the rest as single"},
{"lineNum":"  133","line":"        # letters — for a long option that means reporting \"Unknown option: --\" and losing the name."},
{"lineNum":"  134","line":"        die_usage \"Unknown option \'$1\'.\"","class":"lineCov","hits":"1","order":"3706",},
{"lineNum":"  135","line":"        ;;"},
{"lineNum":"  136","line":"      -*)"},
{"lineNum":"  137","line":"        local combined=\"${1#-}\"","class":"lineCov","hits":"1","order":"3697",},
{"lineNum":"  138","line":"        shift","class":"lineCov","hits":"1","order":"3659",},
{"lineNum":"  139","line":"        for (( i=0; i<${#combined}; i++ )); do","class":"lineCov","hits":"1","order":"3656",},
{"lineNum":"  140","line":"          case \"${combined:$i:1}\" in","class":"lineCov","hits":"1","order":"3686",},
{"lineNum":"  141","line":"            t) _opt_timestamps=true ;;","class":"lineCov","hits":"1","order":"3654",},
{"lineNum":"  142","line":"            c) _opt_checksums=true ;;","class":"lineCov","hits":"1","order":"3652",},
{"lineNum":"  143","line":"            i) _opt_ignore_case=true ;;","class":"lineCov","hits":"1","order":"3710",},
{"lineNum":"  144","line":"            d) _opt_no_dotfiles=true ;;","class":"lineCov","hits":"1","order":"3650",},
{"lineNum":"  145","line":"            x)"},
{"lineNum":"  146","line":"              if (( i + 1 < ${#combined} )); then","class":"lineCov","hits":"1","order":"3648",},
{"lineNum":"  147","line":"                die_usage \"-x must be last in a combined flag group (requires an argument)\"","class":"lineCov","hits":"1","order":"3699",},
{"lineNum":"  148","line":"              fi"},
{"lineNum":"  149","line":"              _opt_excludes+=(\"$1\")","class":"lineCov","hits":"1","order":"3676",},
{"lineNum":"  150","line":"              shift","class":"lineCov","hits":"1","order":"3692",},
{"lineNum":"  151","line":"              ;;"},
{"lineNum":"  152","line":"            n) _opt_no_color=true ;;","class":"lineNoCov","hits":"0",},
{"lineNum":"  153","line":"            h) show_usage; exit 0 ;;","class":"lineNoCov","hits":"0",},
{"lineNum":"  154","line":"            *)"},
{"lineNum":"  155","line":"              die_usage \"Unknown option: -${combined:$i:1}\"","class":"lineCov","hits":"1","order":"3731",},
{"lineNum":"  156","line":"              ;;"},
{"lineNum":"  157","line":"          esac"},
{"lineNum":"  158","line":"        done"},
{"lineNum":"  159","line":"        ;;"},
{"lineNum":"  160","line":"      *)"},
{"lineNum":"  161","line":"        positional+=(\"$1\")","class":"lineCov","hits":"1","order":"3643",},
{"lineNum":"  162","line":"        shift","class":"lineCov","hits":"1","order":"3753",},
{"lineNum":"  163","line":"        ;;"},
{"lineNum":"  164","line":"    esac"},
{"lineNum":"  165","line":"  done"},
{"lineNum":"  166","line":""},
{"lineNum":"  167","line":"  if [[ ${#positional[@]} -ne 2 ]]; then","class":"lineCov","hits":"1","order":"3721",},
{"lineNum":"  168","line":"    log_error \"Expected exactly 2 directory arguments, got ${#positional[@]}.\"","class":"lineCov","hits":"1","order":"3743",},
{"lineNum":"  169","line":"    show_usage","class":"lineCov","hits":"1","order":"3755",},
{"lineNum":"  170","line":"    exit 1","class":"lineCov","hits":"1","order":"3757",},
{"lineNum":"  171","line":"  fi"},
{"lineNum":"  172","line":""},
{"lineNum":"  173","line":"  _dir1=\"${positional[0]}\"","class":"lineCov","hits":"1","order":"3759",},
{"lineNum":"  174","line":"  _dir2=\"${positional[1]}\"","class":"lineCov","hits":"1","order":"3761",},
{"lineNum":"  175","line":""},
{"lineNum":"  176","line":"  if [[ ! -d \"${_dir1}\" ]]; then","class":"lineCov","hits":"1","order":"3763",},
{"lineNum":"  177","line":"    log_error \"\'${_dir1}\' is not a directory.\"","class":"lineCov","hits":"1","order":"3764",},
{"lineNum":"  178","line":"    exit 1","class":"lineCov","hits":"1","order":"3689",},
{"lineNum":"  179","line":"  fi"},
{"lineNum":"  180","line":"  if [[ ! -d \"${_dir2}\" ]]; then","class":"lineCov","hits":"1","order":"3765",},
{"lineNum":"  181","line":"    log_error \"\'${_dir2}\' is not a directory.\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  182","line":"    exit 1","class":"lineNoCov","hits":"0",},
{"lineNum":"  183","line":"  fi"},
{"lineNum":"  184","line":""},
{"lineNum":"  185","line":"  # Resolve to absolute paths for display"},
{"lineNum":"  186","line":"  _dir1=\"$(cd \"${_dir1}\" && pwd)\"","class":"lineCov","hits":"1","order":"3766",},
{"lineNum":"  187","line":"  _dir2=\"$(cd \"${_dir2}\" && pwd)\"","class":"lineCov","hits":"1","order":"3767",},
{"lineNum":"  188","line":"}"},
{"lineNum":"  189","line":""},
{"lineNum":"  190","line":"########################################"},
{"lineNum":"  191","line":"# Formats an epoch timestamp as a human-readable date string."},
{"lineNum":"  192","line":"# Arguments:"},
{"lineNum":"  193","line":"#   ts: Unix epoch timestamp."},
{"lineNum":"  194","line":"# Outputs:"},
{"lineNum":"  195","line":"#   Prints formatted date to stdout."},
{"lineNum":"  196","line":"########################################"},
{"lineNum":"  197","line":"format_mtime() {"},
{"lineNum":"  198","line":"  local ts=\"$1\"","class":"lineCov","hits":"1","order":"3769",},
{"lineNum":"  199","line":"  if date -d \"@${ts}\" \'+%Y-%m-%d %H:%M:%S\' 2>/dev/null; then","class":"lineCov","hits":"1","order":"3770",},
{"lineNum":"  200","line":"    return","class":"lineCov","hits":"1","order":"3772",},
{"lineNum":"  201","line":"  fi"},
{"lineNum":"  202","line":"  # BSD date fallback"},
{"lineNum":"  203","line":"  date -r \"${ts}\" \'+%Y-%m-%d %H:%M:%S\'","class":"lineNoCov","hits":"0",},
{"lineNum":"  204","line":"}"},
{"lineNum":"  205","line":""},
{"lineNum":"  206","line":"########################################"},
{"lineNum":"  207","line":"# Formats a byte count with thousands separators."},
{"lineNum":"  208","line":"# Arguments:"},
{"lineNum":"  209","line":"#   size: File size in bytes."},
{"lineNum":"  210","line":"# Outputs:"},
{"lineNum":"  211","line":"#   Prints formatted size to stdout."},
{"lineNum":"  212","line":"########################################"},
{"lineNum":"  213","line":"format_size() {"},
{"lineNum":"  214","line":"  printf \"%\'d bytes\" \"$1\"","class":"lineCov","hits":"1","order":"3775",},
{"lineNum":"  215","line":"}"},
{"lineNum":"  216","line":""},
{"lineNum":"  217","line":"########################################"},
{"lineNum":"  218","line":"# Determines the filesystem type of a path."},
{"lineNum":"  219","line":"# Arguments:"},
{"lineNum":"  220","line":"#   path: Filesystem path to inspect."},
{"lineNum":"  221","line":"# Outputs:"},
{"lineNum":"  222","line":"#   Prints one of: symlink, directory, file, other."},
{"lineNum":"  223","line":"########################################"},
{"lineNum":"  224","line":"get_type() {"},
{"lineNum":"  225","line":"  local path=\"$1\"","class":"lineCov","hits":"1","order":"3777",},
{"lineNum":"  226","line":"  if [[ -L \"${path}\" ]]; then","class":"lineCov","hits":"1","order":"3717",},
{"lineNum":"  227","line":"    echo \"symlink\"","class":"lineCov","hits":"1","order":"3746",},
{"lineNum":"  228","line":"  elif [[ -d \"${path}\" ]]; then","class":"lineCov","hits":"1","order":"3781",},
{"lineNum":"  229","line":"    echo \"directory\"","class":"lineCov","hits":"1","order":"3784",},
{"lineNum":"  230","line":"  elif [[ -f \"${path}\" ]]; then","class":"lineCov","hits":"1","order":"3713",},
{"lineNum":"  231","line":"    echo \"file\"","class":"lineCov","hits":"1","order":"3751",},
{"lineNum":"  232","line":"  else"},
{"lineNum":"  233","line":"    echo \"other\"","class":"lineCov","hits":"1","order":"3786",},
{"lineNum":"  234","line":"  fi"},
{"lineNum":"  235","line":"}"},
{"lineNum":"  236","line":""},
{"lineNum":"  237","line":"# --- Output Helpers ---"},
{"lineNum":"  238","line":""},
{"lineNum":"  239","line":"########################################"},
{"lineNum":"  240","line":"# Reports an item found only in the left directory."},
{"lineNum":"  241","line":"# Globals:"},
{"lineNum":"  242","line":"#   _C_RED, _C_BOLD, _C_RESET, _count_left_only"},
{"lineNum":"  243","line":"# Arguments:"},
{"lineNum":"  244","line":"#   Relative path of the item."},
{"lineNum":"  245","line":"########################################"},
{"lineNum":"  246","line":"print_left_only() {"},
{"lineNum":"  247","line":"  echo \"${_C_RED}← LEFT only:  ${_C_BOLD}${1}${_C_RESET}\"","class":"lineCov","hits":"1","order":"3668",},
{"lineNum":"  248","line":"  (( _count_left_only++ )) || true","class":"lineCov","hits":"1","order":"3788",},
{"lineNum":"  249","line":"}"},
{"lineNum":"  250","line":""},
{"lineNum":"  251","line":"########################################"},
{"lineNum":"  252","line":"# Reports an item found only in the right directory."},
{"lineNum":"  253","line":"# Globals:"},
{"lineNum":"  254","line":"#   _C_GREEN, _C_BOLD, _C_RESET, _count_right_only"},
{"lineNum":"  255","line":"# Arguments:"},
{"lineNum":"  256","line":"#   Relative path of the item."},
{"lineNum":"  257","line":"########################################"},
{"lineNum":"  258","line":"print_right_only() {"},
{"lineNum":"  259","line":"  echo \"${_C_GREEN}→ RIGHT only: ${_C_BOLD}${1}${_C_RESET}\"","class":"lineCov","hits":"1","order":"3790",},
{"lineNum":"  260","line":"  (( _count_right_only++ )) || true","class":"lineCov","hits":"1","order":"3794",},
{"lineNum":"  261","line":"}"},
{"lineNum":"  262","line":""},
{"lineNum":"  263","line":"########################################"},
{"lineNum":"  264","line":"# Reports a file size difference between left and right."},
{"lineNum":"  265","line":"# Globals:"},
{"lineNum":"  266","line":"#   _C_YELLOW, _C_BOLD, _C_RESET, _count_differences"},
{"lineNum":"  267","line":"# Arguments:"},
{"lineNum":"  268","line":"#   path: Relative path of the file."},
{"lineNum":"  269","line":"#   size1: Size in left directory (bytes)."},
{"lineNum":"  270","line":"#   size2: Size in right directory (bytes)."},
{"lineNum":"  271","line":"########################################"},
{"lineNum":"  272","line":"print_size_diff() {"},
{"lineNum":"  273","line":"  local path=\"$1\" size1=\"$2\" size2=\"$3\"","class":"lineCov","hits":"1","order":"3707",},
{"lineNum":"  274","line":"  echo \"${_C_YELLOW}≠ Size differs: ${_C_BOLD}${path}${_C_RESET}\"","class":"lineCov","hits":"1","order":"3701",},
{"lineNum":"  275","line":"  echo \"    LEFT:  $(format_size \"${size1}\")\"","class":"lineCov","hits":"1","order":"3795",},
{"lineNum":"  276","line":"  echo \"    RIGHT: $(format_size \"${size2}\")\"","class":"lineCov","hits":"1","order":"3679",},
{"lineNum":"  277","line":"  (( _count_differences++ )) || true","class":"lineCov","hits":"1","order":"3693",},
{"lineNum":"  278","line":"}"},
{"lineNum":"  279","line":""},
{"lineNum":"  280","line":"########################################"},
{"lineNum":"  281","line":"# Reports a modification time difference between left and right."},
{"lineNum":"  282","line":"# Globals:"},
{"lineNum":"  283","line":"#   _C_YELLOW, _C_BOLD, _C_RESET, _count_differences"},
{"lineNum":"  284","line":"# Arguments:"},
{"lineNum":"  285","line":"#   path: Relative path of the file."},
{"lineNum":"  286","line":"#   mtime1: Epoch timestamp in left directory."},
{"lineNum":"  287","line":"#   mtime2: Epoch timestamp in right directory."},
{"lineNum":"  288","line":"########################################"},
{"lineNum":"  289","line":"print_mtime_diff() {"},
{"lineNum":"  290","line":"  local path=\"$1\" mtime1=\"$2\" mtime2=\"$3\"","class":"lineCov","hits":"1","order":"3797",},
{"lineNum":"  291","line":"  echo \"${_C_YELLOW}≠ Mtime differs: ${_C_BOLD}${path}${_C_RESET}\"","class":"lineCov","hits":"1","order":"3734",},
{"lineNum":"  292","line":"  echo \"    LEFT:  $(format_mtime \"${mtime1}\")\"","class":"lineCov","hits":"1","order":"3729",},
{"lineNum":"  293","line":"  echo \"    RIGHT: $(format_mtime \"${mtime2}\")\"","class":"lineCov","hits":"1","order":"3725",},
{"lineNum":"  294","line":"  (( _count_differences++ )) || true","class":"lineCov","hits":"1","order":"3732",},
{"lineNum":"  295","line":"}"},
{"lineNum":"  296","line":""},
{"lineNum":"  297","line":"########################################"},
{"lineNum":"  298","line":"# Reports a checksum difference between left and right."},
{"lineNum":"  299","line":"# Globals:"},
{"lineNum":"  300","line":"#   _C_YELLOW, _C_BOLD, _C_RESET, _count_differences"},
{"lineNum":"  301","line":"# Arguments:"},
{"lineNum":"  302","line":"#   Relative path of the file."},
{"lineNum":"  303","line":"########################################"},
{"lineNum":"  304","line":"print_checksum_diff() {"},
{"lineNum":"  305","line":"  echo \"${_C_YELLOW}≠ Checksum differs: ${_C_BOLD}${1}${_C_RESET}\"","class":"lineCov","hits":"1","order":"3690",},
{"lineNum":"  306","line":"  (( _count_differences++ )) || true","class":"lineCov","hits":"1","order":"3798",},
{"lineNum":"  307","line":"}"},
{"lineNum":"  308","line":""},
{"lineNum":"  309","line":"########################################"},
{"lineNum":"  310","line":"# Reports a type mismatch (e.g., file vs directory)."},
{"lineNum":"  311","line":"# Globals:"},
{"lineNum":"  312","line":"#   _C_YELLOW, _C_BOLD, _C_RESET, _count_differences"},
{"lineNum":"  313","line":"# Arguments:"},
{"lineNum":"  314","line":"#   path: Relative path of the item."},
{"lineNum":"  315","line":"#   type1: Type in left directory."},
{"lineNum":"  316","line":"#   type2: Type in right directory."},
{"lineNum":"  317","line":"########################################"},
{"lineNum":"  318","line":"print_type_mismatch() {"},
{"lineNum":"  319","line":"  local path=\"$1\" type1=\"$2\" type2=\"$3\"","class":"lineCov","hits":"1","order":"3799",},
{"lineNum":"  320","line":"  echo \"${_C_YELLOW}⚡ Type mismatch: ${_C_BOLD}${path}${_C_RESET}\"","class":"lineCov","hits":"1","order":"3800",},
{"lineNum":"  321","line":"  echo \"    LEFT:  ${type1}\"","class":"lineCov","hits":"1","order":"3801",},
{"lineNum":"  322","line":"  echo \"    RIGHT: ${type2}\"","class":"lineCov","hits":"1","order":"3802",},
{"lineNum":"  323","line":"  (( _count_differences++ )) || true","class":"lineCov","hits":"1","order":"3803",},
{"lineNum":"  324","line":"}"},
{"lineNum":"  325","line":""},
{"lineNum":"  326","line":"########################################"},
{"lineNum":"  327","line":"# Reports a symlink target difference between left and right."},
{"lineNum":"  328","line":"# Globals:"},
{"lineNum":"  329","line":"#   _C_YELLOW, _C_BOLD, _C_RESET, _count_differences"},
{"lineNum":"  330","line":"# Arguments:"},
{"lineNum":"  331","line":"#   path: Relative path of the symlink."},
{"lineNum":"  332","line":"#   target1: Link target in left directory."},
{"lineNum":"  333","line":"#   target2: Link target in right directory."},
{"lineNum":"  334","line":"########################################"},
{"lineNum":"  335","line":"print_symlink_diff() {"},
{"lineNum":"  336","line":"  local path=\"$1\" target1=\"$2\" target2=\"$3\"","class":"lineCov","hits":"1","order":"3804",},
{"lineNum":"  337","line":"  echo \"${_C_YELLOW}≠ Symlink target differs: ${_C_BOLD}${path}${_C_RESET}\"","class":"lineCov","hits":"1","order":"3805",},
{"lineNum":"  338","line":"  echo \"    LEFT:  -> ${target1}\"","class":"lineCov","hits":"1","order":"3806",},
{"lineNum":"  339","line":"  echo \"    RIGHT: -> ${target2}\"","class":"lineCov","hits":"1","order":"3807",},
{"lineNum":"  340","line":"  (( _count_differences++ )) || true","class":"lineCov","hits":"1","order":"3738",},
{"lineNum":"  341","line":"}"},
{"lineNum":"  342","line":""},
{"lineNum":"  343","line":"########################################"},
{"lineNum":"  344","line":"# Tests whether a filename matches any of the given glob patterns."},
{"lineNum":"  345","line":"# Arguments:"},
{"lineNum":"  346","line":"#   name: The filename to test."},
{"lineNum":"  347","line":"#   ...: One or more glob patterns."},
{"lineNum":"  348","line":"# Returns:"},
{"lineNum":"  349","line":"#   0 if any pattern matches, 1 otherwise."},
{"lineNum":"  350","line":"########################################"},
{"lineNum":"  351","line":"matches_pattern() {"},
{"lineNum":"  352","line":"  local name=\"$1\"","class":"lineCov","hits":"1","order":"3779",},
{"lineNum":"  353","line":"  shift","class":"lineCov","hits":"1","order":"3735",},
{"lineNum":"  354","line":"  local pattern","class":"lineCov","hits":"1","order":"3747",},
{"lineNum":"  355","line":"  for pattern in \"$@\"; do","class":"lineCov","hits":"1","order":"3782",},
{"lineNum":"  356","line":"    # shellcheck disable=SC2254,SC2053"},
{"lineNum":"  357","line":"    if [[ \"${name}\" == ${pattern} ]]; then","class":"lineCov","hits":"1","order":"3744",},
{"lineNum":"  358","line":"      return 0","class":"lineCov","hits":"1","order":"3752",},
{"lineNum":"  359","line":"    fi"},
{"lineNum":"  360","line":"  done"},
{"lineNum":"  361","line":"  return 1","class":"lineCov","hits":"1","order":"3748",},
{"lineNum":"  362","line":"}"},
{"lineNum":"  363","line":""},
{"lineNum":"  364","line":"########################################"},
{"lineNum":"  365","line":"# Recursively compares two directory trees, printing differences."},
{"lineNum":"  366","line":"# Uses null-delimited I/O internally to handle arbitrary filenames."},
{"lineNum":"  367","line":"# Globals:"},
{"lineNum":"  368","line":"#   _opt_timestamps, _opt_checksums, _opt_ignore_case, _opt_no_dotfiles,"},
{"lineNum":"  369","line":"#   _opt_excludes, _opt_excludes_left, _opt_excludes_right,"},
{"lineNum":"  370","line":"#   _count_left_only, _count_right_only, _count_differences"},
{"lineNum":"  371","line":"# Arguments:"},
{"lineNum":"  372","line":"#   prefix: Relative path prefix for display (empty string for top level)."},
{"lineNum":"  373","line":"#   left:   Absolute path to the left directory being compared."},
{"lineNum":"  374","line":"#   right:  Absolute path to the right directory being compared."},
{"lineNum":"  375","line":"########################################"},
{"lineNum":"  376","line":"compare_dirs() {"},
{"lineNum":"  377","line":"  local prefix=\"$1\"","class":"lineCov","hits":"1","order":"3665",},
{"lineNum":"  378","line":"  local left=\"$2\"","class":"lineCov","hits":"1","order":"3663",},
{"lineNum":"  379","line":"  local right=\"$3\"","class":"lineCov","hits":"1","order":"3808",},
{"lineNum":"  380","line":""},
{"lineNum":"  381","line":"  # Build sorted lists of entries (null-delimited for filename safety)"},
{"lineNum":"  382","line":"  local -a left_sorted=()","class":"lineCov","hits":"1","order":"3722",},
{"lineNum":"  383","line":"  local -a right_sorted=()","class":"lineCov","hits":"1","order":"3714",},
{"lineNum":"  384","line":""},
{"lineNum":"  385","line":"  if [[ -d \"${left}\" ]]; then","class":"lineCov","hits":"1","order":"3810",},
{"lineNum":"  386","line":"    while IFS= read -r -d \'\' entry; do","class":"lineCov","hits":"1","order":"3792",},
{"lineNum":"  387","line":"      local base","class":"lineCov","hits":"1","order":"3642",},
{"lineNum":"  388","line":"      base=\"$(basename \"${entry}\")\"","class":"lineCov","hits":"1","order":"3641",},
{"lineNum":"  389","line":"      [[ \"${_opt_no_dotfiles}\" == true && \"${base}\" == .* ]] && continue","class":"lineCov","hits":"1","order":"3640",},
{"lineNum":"  390","line":"      [[ ${#_opt_excludes[@]} -gt 0 ]] && matches_pattern \"${base}\" \"${_opt_excludes[@]}\" && continue","class":"lineCov","hits":"1","order":"3639",},
{"lineNum":"  391","line":"      left_sorted+=(\"${base}\")","class":"lineCov","hits":"1","order":"3705",},
{"lineNum":"  392","line":"    done < <(find \"${left}\" -maxdepth 1 -mindepth 1 -print0 | sort -z)","class":"lineNoCov","hits":"0",},
{"lineNum":"  393","line":"  fi"},
{"lineNum":"  394","line":""},
{"lineNum":"  395","line":"  if [[ -d \"${right}\" ]]; then","class":"lineCov","hits":"1","order":"3658",},
{"lineNum":"  396","line":"    while IFS= read -r -d \'\' entry; do","class":"lineCov","hits":"1","order":"3655",},
{"lineNum":"  397","line":"      local base","class":"lineCov","hits":"1","order":"3685",},
{"lineNum":"  398","line":"      base=\"$(basename \"${entry}\")\"","class":"lineCov","hits":"1","order":"3653",},
{"lineNum":"  399","line":"      [[ \"${_opt_no_dotfiles}\" == true && \"${base}\" == .* ]] && continue","class":"lineCov","hits":"1","order":"3651",},
{"lineNum":"  400","line":"      [[ ${#_opt_excludes[@]} -gt 0 ]] && matches_pattern \"${base}\" \"${_opt_excludes[@]}\" && continue","class":"lineCov","hits":"1","order":"3709",},
{"lineNum":"  401","line":"      right_sorted+=(\"${base}\")","class":"lineCov","hits":"1","order":"3649",},
{"lineNum":"  402","line":"    done < <(find \"${right}\" -maxdepth 1 -mindepth 1 -print0 | sort -z)","class":"lineNoCov","hits":"0",},
{"lineNum":"  403","line":"  fi"},
{"lineNum":"  404","line":""},
{"lineNum":"  405","line":"  # Use associative arrays for O(1) set membership tests."},
{"lineNum":"  406","line":"  # Values store the original filename for path construction."},
{"lineNum":"  407","line":"  local -A left_set=()","class":"lineCov","hits":"1","order":"3691",},
{"lineNum":"  408","line":"  local -A right_set=()","class":"lineCov","hits":"1","order":"3638",},
{"lineNum":"  409","line":"  for e in \"${left_sorted[@]+\"${left_sorted[@]}\"}\"; do","class":"lineCov","hits":"1","order":"3645",},
{"lineNum":"  410","line":"    local norm=\"${e}\"","class":"lineCov","hits":"1","order":"3644",},
{"lineNum":"  411","line":"    [[ \"${_opt_ignore_case}\" == true ]] && norm=\"${e,,}\"","class":"lineCov","hits":"1","order":"3637",},
{"lineNum":"  412","line":"    left_set[\"${norm}\"]=\"${e}\"","class":"lineCov","hits":"1","order":"3730",},
{"lineNum":"  413","line":"  done"},
{"lineNum":"  414","line":"  for e in \"${right_sorted[@]+\"${right_sorted[@]}\"}\"; do","class":"lineCov","hits":"1","order":"3636",},
{"lineNum":"  415","line":"    local norm=\"${e}\"","class":"lineCov","hits":"1","order":"3635",},
{"lineNum":"  416","line":"    [[ \"${_opt_ignore_case}\" == true ]] && norm=\"${e,,}\"","class":"lineCov","hits":"1","order":"3634",},
{"lineNum":"  417","line":"    right_set[\"${norm}\"]=\"${e}\"","class":"lineCov","hits":"1","order":"3633",},
{"lineNum":"  418","line":"  done"},
{"lineNum":"  419","line":""},
{"lineNum":"  420","line":"  # Compute merged sorted unique list of normalized keys. Both sides accumulate into one array, which"},
{"lineNum":"  421","line":"  # the enclosing condition guarantees is non-empty, so its expansion needs no guarding."},
{"lineNum":"  422","line":"  local -a all_entries=()","class":"lineCov","hits":"1","order":"3632",},
{"lineNum":"  423","line":"  if [[ ${#left_sorted[@]} -gt 0 || ${#right_sorted[@]} -gt 0 ]]; then","class":"lineCov","hits":"1","order":"3631",},
{"lineNum":"  424","line":"    local -a norm_entries=()","class":"lineCov","hits":"1","order":"3720",},
{"lineNum":"  425","line":"    for e in \"${left_sorted[@]+\"${left_sorted[@]}\"}\"; do","class":"lineCov","hits":"1","order":"3742",},
{"lineNum":"  426","line":"      local n=\"${e}\"","class":"lineCov","hits":"1","order":"3754",},
{"lineNum":"  427","line":"      [[ \"${_opt_ignore_case}\" == true ]] && n=\"${e,,}\"","class":"lineCov","hits":"1","order":"3756",},
{"lineNum":"  428","line":"      norm_entries+=(\"${n}\")","class":"lineCov","hits":"1","order":"3630",},
{"lineNum":"  429","line":"    done"},
{"lineNum":"  430","line":"    for e in \"${right_sorted[@]+\"${right_sorted[@]}\"}\"; do","class":"lineCov","hits":"1","order":"3758",},
{"lineNum":"  431","line":"      local n=\"${e}\"","class":"lineCov","hits":"1","order":"3760",},
{"lineNum":"  432","line":"      [[ \"${_opt_ignore_case}\" == true ]] && n=\"${e,,}\"","class":"lineCov","hits":"1","order":"3629",},
{"lineNum":"  433","line":"      norm_entries+=(\"${n}\")","class":"lineCov","hits":"1","order":"3762",},
{"lineNum":"  434","line":"    done"},
{"lineNum":"  435","line":"    while IFS= read -r -d \'\' entry; do","class":"lineCov","hits":"1","order":"3688",},
{"lineNum":"  436","line":"      all_entries+=(\"${entry}\")","class":"lineCov","hits":"1","order":"3628",},
{"lineNum":"  437","line":"    done < <(printf \'%s\\0\' \"${norm_entries[@]}\" | sort -uz)","class":"lineNoCov","hits":"0",},
{"lineNum":"  438","line":"  fi"},
{"lineNum":"  439","line":""},
{"lineNum":"  440","line":"  for norm_entry in \"${all_entries[@]+\"${all_entries[@]}\"}\"; do","class":"lineCov","hits":"1","order":"3627",},
{"lineNum":"  441","line":"    local orig_left=\"${left_set[${norm_entry}]:-}\"","class":"lineCov","hits":"1","order":"3626",},
{"lineNum":"  442","line":"    local orig_right=\"${right_set[${norm_entry}]:-}\"","class":"lineCov","hits":"1","order":"3625",},
{"lineNum":"  443","line":""},
{"lineNum":"  444","line":"    # Use the left original name for display if available, otherwise right"},
{"lineNum":"  445","line":"    local display_name=\"${orig_left:-${orig_right}}\"","class":"lineCov","hits":"1","order":"3624",},
{"lineNum":"  446","line":"    local rel_path","class":"lineCov","hits":"1","order":"3623",},
{"lineNum":"  447","line":"    if [[ -n \"${prefix}\" ]]; then","class":"lineCov","hits":"1","order":"3622",},
{"lineNum":"  448","line":"      rel_path=\"${prefix}${display_name}\"","class":"lineCov","hits":"1","order":"3621",},
{"lineNum":"  449","line":"    else"},
{"lineNum":"  450","line":"      rel_path=\"${display_name}\"","class":"lineCov","hits":"1","order":"3620",},
{"lineNum":"  451","line":"    fi"},
{"lineNum":"  452","line":""},
{"lineNum":"  453","line":"    if [[ -n \"${orig_left}\" && -z \"${orig_right}\" ]]; then","class":"lineCov","hits":"1","order":"3619",},
{"lineNum":"  454","line":"      if [[ ${#_opt_excludes_left[@]} -gt 0 ]] && matches_pattern \"${display_name}\" \"${_opt_excludes_left[@]}\"; then","class":"lineCov","hits":"1","order":"3618",},
{"lineNum":"  455","line":"        continue","class":"lineCov","hits":"1","order":"3768",},
{"lineNum":"  456","line":"      fi"},
{"lineNum":"  457","line":"      local type_l","class":"lineCov","hits":"1","order":"3771",},
{"lineNum":"  458","line":"      type_l=\"$(get_type \"${left}/${orig_left}\")\"","class":"lineCov","hits":"1","order":"3617",},
{"lineNum":"  459","line":"      if [[ \"${type_l}\" == \"directory\" ]]; then","class":"lineCov","hits":"1","order":"3616",},
{"lineNum":"  460","line":"        print_left_only \"${rel_path}/\"","class":"lineCov","hits":"1","order":"3773",},
{"lineNum":"  461","line":"      else"},
{"lineNum":"  462","line":"        print_left_only \"${rel_path}\"","class":"lineCov","hits":"1","order":"3615",},
{"lineNum":"  463","line":"      fi"},
{"lineNum":"  464","line":""},
{"lineNum":"  465","line":"    elif [[ -z \"${orig_left}\" && -n \"${orig_right}\" ]]; then","class":"lineCov","hits":"1","order":"3614",},
{"lineNum":"  466","line":"      if [[ ${#_opt_excludes_right[@]} -gt 0 ]] && matches_pattern \"${display_name}\" \"${_opt_excludes_right[@]}\"; then","class":"lineCov","hits":"1","order":"3613",},
{"lineNum":"  467","line":"        continue","class":"lineCov","hits":"1","order":"3612",},
{"lineNum":"  468","line":"      fi"},
{"lineNum":"  469","line":"      local type_r","class":"lineCov","hits":"1","order":"3611",},
{"lineNum":"  470","line":"      type_r=\"$(get_type \"${right}/${orig_right}\")\"","class":"lineCov","hits":"1","order":"3610",},
{"lineNum":"  471","line":"      if [[ \"${type_r}\" == \"directory\" ]]; then","class":"lineCov","hits":"1","order":"3774",},
{"lineNum":"  472","line":"        print_right_only \"${rel_path}/\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  473","line":"      else"},
{"lineNum":"  474","line":"        print_right_only \"${rel_path}\"","class":"lineCov","hits":"1","order":"3609",},
{"lineNum":"  475","line":"      fi"},
{"lineNum":"  476","line":""},
{"lineNum":"  477","line":"    else"},
{"lineNum":"  478","line":"      # Present in both — compare"},
{"lineNum":"  479","line":"      local left_path=\"${left}/${orig_left}\"","class":"lineCov","hits":"1","order":"3608",},
{"lineNum":"  480","line":"      local right_path=\"${right}/${orig_right}\"","class":"lineCov","hits":"1","order":"3607",},
{"lineNum":"  481","line":"      local type_l type_r","class":"lineCov","hits":"1","order":"3606",},
{"lineNum":"  482","line":"      type_l=\"$(get_type \"${left_path}\")\"","class":"lineCov","hits":"1","order":"3776",},
{"lineNum":"  483","line":"      type_r=\"$(get_type \"${right_path}\")\"","class":"lineCov","hits":"1","order":"3716",},
{"lineNum":"  484","line":""},
{"lineNum":"  485","line":"      if [[ \"${type_l}\" != \"${type_r}\" ]]; then","class":"lineCov","hits":"1","order":"3780",},
{"lineNum":"  486","line":"        print_type_mismatch \"${rel_path}\" \"${type_l}\" \"${type_r}\"","class":"lineCov","hits":"1","order":"3783",},
{"lineNum":"  487","line":"      elif [[ \"${type_l}\" == \"directory\" ]]; then","class":"lineCov","hits":"1","order":"3712",},
{"lineNum":"  488","line":"        compare_dirs \"${rel_path}/\" \"${left_path}\" \"${right_path}\"","class":"lineCov","hits":"1","order":"3750",},
{"lineNum":"  489","line":"      elif [[ \"${type_l}\" == \"symlink\" ]]; then","class":"lineCov","hits":"1","order":"3605",},
{"lineNum":"  490","line":"        local target_l target_r","class":"lineCov","hits":"1","order":"3785",},
{"lineNum":"  491","line":"        target_l=\"$(readlink \"${left_path}\")\"","class":"lineCov","hits":"1","order":"3604",},
{"lineNum":"  492","line":"        target_r=\"$(readlink \"${right_path}\")\"","class":"lineCov","hits":"1","order":"3603",},
{"lineNum":"  493","line":"        if [[ \"${target_l}\" != \"${target_r}\" ]]; then","class":"lineCov","hits":"1","order":"3602",},
{"lineNum":"  494","line":"          print_symlink_diff \"${rel_path}\" \"${target_l}\" \"${target_r}\"","class":"lineCov","hits":"1","order":"3601",},
{"lineNum":"  495","line":"        fi"},
{"lineNum":"  496","line":"      elif [[ \"${type_l}\" == \"file\" ]]; then","class":"lineCov","hits":"1","order":"3600",},
{"lineNum":"  497","line":"        local size_l size_r","class":"lineCov","hits":"1","order":"3599",},
{"lineNum":"  498","line":"        size_l=\"$(stat_size \"${left_path}\")\"","class":"lineCov","hits":"1","order":"3598",},
{"lineNum":"  499","line":"        size_r=\"$(stat_size \"${right_path}\")\"","class":"lineCov","hits":"1","order":"3597",},
{"lineNum":"  500","line":""},
{"lineNum":"  501","line":"        if [[ \"${size_l}\" != \"${size_r}\" ]]; then","class":"lineCov","hits":"1","order":"3596",},
{"lineNum":"  502","line":"          print_size_diff \"${rel_path}\" \"${size_l}\" \"${size_r}\"","class":"lineCov","hits":"1","order":"3595",},
{"lineNum":"  503","line":"        elif [[ \"${_opt_checksums}\" == true ]]; then","class":"lineCov","hits":"1","order":"3594",},
{"lineNum":"  504","line":"          local cksum_l cksum_r","class":"lineCov","hits":"1","order":"3667",},
{"lineNum":"  505","line":"          cksum_l=\"$(file_checksum \"${left_path}\")\"","class":"lineCov","hits":"1","order":"3787",},
{"lineNum":"  506","line":"          cksum_r=\"$(file_checksum \"${right_path}\")\"","class":"lineCov","hits":"1","order":"3593",},
{"lineNum":"  507","line":"          if [[ \"${cksum_l}\" != \"${cksum_r}\" ]]; then","class":"lineCov","hits":"1","order":"3592",},
{"lineNum":"  508","line":"            print_checksum_diff \"${rel_path}\"","class":"lineCov","hits":"1","order":"3591",},
{"lineNum":"  509","line":"          fi"},
{"lineNum":"  510","line":"        fi"},
{"lineNum":"  511","line":""},
{"lineNum":"  512","line":"        if [[ \"${_opt_timestamps}\" == true ]]; then","class":"lineCov","hits":"1","order":"3590",},
{"lineNum":"  513","line":"          local mtime_l mtime_r","class":"lineCov","hits":"1","order":"3589",},
{"lineNum":"  514","line":"          mtime_l=\"$(stat_mtime \"${left_path}\")\"","class":"lineCov","hits":"1","order":"3588",},
{"lineNum":"  515","line":"          mtime_r=\"$(stat_mtime \"${right_path}\")\"","class":"lineCov","hits":"1","order":"3587",},
{"lineNum":"  516","line":"          if [[ \"${mtime_l}\" != \"${mtime_r}\" ]]; then","class":"lineCov","hits":"1","order":"3789",},
{"lineNum":"  517","line":"            print_mtime_diff \"${rel_path}\" \"${mtime_l}\" \"${mtime_r}\"","class":"lineCov","hits":"1","order":"3793",},
{"lineNum":"  518","line":"          fi"},
{"lineNum":"  519","line":"        fi"},
{"lineNum":"  520","line":"      fi"},
{"lineNum":"  521","line":"    fi"},
{"lineNum":"  522","line":"  done"},
{"lineNum":"  523","line":"}"},
{"lineNum":"  524","line":""},
{"lineNum":"  525","line":"########################################"},
{"lineNum":"  526","line":"# Main entry point."},
{"lineNum":"  527","line":"# Arguments:"},
{"lineNum":"  528","line":"#   Command-line arguments."},
{"lineNum":"  529","line":"########################################"},
{"lineNum":"  530","line":"main() {"},
{"lineNum":"  531","line":"  parse_options \"$@\"","class":"lineCov","hits":"1","order":"3700",},
{"lineNum":"  532","line":""},
{"lineNum":"  533","line":"  # Checked once, up front: without a checksum tool every comparison would fail one file at a time,"},
{"lineNum":"  534","line":"  # and the option promises something the machine cannot deliver."},
{"lineNum":"  535","line":"  if [[ \"${_opt_checksums}\" == true ]] && ! has_checksum_tool; then","class":"lineCov","hits":"1","order":"3586",},
{"lineNum":"  536","line":"    log_error \"No checksum tool found (sha256sum or shasum). Checksum comparison disabled.\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  537","line":"    _opt_checksums=false","class":"lineNoCov","hits":"0",},
{"lineNum":"  538","line":"  fi"},
{"lineNum":"  539","line":"  setup_colors \"${_opt_no_color}\"","class":"lineCov","hits":"1","order":"3646",},
{"lineNum":"  540","line":""},
{"lineNum":"  541","line":"  # Print header"},
{"lineNum":"  542","line":"  echo \"${_C_CYAN}Comparing:${_C_RESET}\"","class":"lineCov","hits":"1","order":"3585",},
{"lineNum":"  543","line":"  echo \"  LEFT:  ${_C_BOLD}${_dir1}${_C_RESET}\"","class":"lineCov","hits":"1","order":"3703",},
{"lineNum":"  544","line":"  echo \"  RIGHT: ${_C_BOLD}${_dir2}${_C_RESET}\"","class":"lineCov","hits":"1","order":"3683",},
{"lineNum":"  545","line":"  echo \"─────────────────────────────────\"","class":"lineCov","hits":"1","order":"3680",},
{"lineNum":"  546","line":"  echo \"\"","class":"lineCov","hits":"1","order":"3695",},
{"lineNum":"  547","line":""},
{"lineNum":"  548","line":"  # Run comparison"},
{"lineNum":"  549","line":"  compare_dirs \"\" \"${_dir1}\" \"${_dir2}\"","class":"lineCov","hits":"1","order":"3728",},
{"lineNum":"  550","line":""},
{"lineNum":"  551","line":"  # Print footer"},
{"lineNum":"  552","line":"  echo \"\"","class":"lineCov","hits":"1","order":"3726",},
{"lineNum":"  553","line":"  echo \"─────────────────────────────────\"","class":"lineCov","hits":"1","order":"3723",},
{"lineNum":"  554","line":"  local total=$(( _count_left_only + _count_right_only + _count_differences ))","class":"lineCov","hits":"1","order":"3718",},
{"lineNum":"  555","line":"  if [[ ${total} -eq 0 ]]; then","class":"lineCov","hits":"1","order":"3740",},
{"lineNum":"  556","line":"    echo \"${_C_GREEN}Directories are identical.${_C_RESET}\"","class":"lineCov","hits":"1","order":"3584",},
{"lineNum":"  557","line":"    exit 0","class":"lineCov","hits":"1","order":"3583",},
{"lineNum":"  558","line":"  else"},
{"lineNum":"  559","line":"    echo \"${_C_CYAN}Summary:${_C_RESET} ${_count_left_only} only in LEFT, ${_count_right_only} only in RIGHT, ${_count_differences} differences\"","class":"lineCov","hits":"1","order":"3582",},
{"lineNum":"  560","line":"    exit 1","class":"lineCov","hits":"1","order":"3581",},
{"lineNum":"  561","line":"  fi"},
{"lineNum":"  562","line":"}"},
{"lineNum":"  563","line":""},
{"lineNum":"  564","line":"# Only run when executed, not when sourced — the test suite sources this file to exercise its"},
{"lineNum":"  565","line":"# individual functions."},
{"lineNum":"  566","line":"if [[ \"${BASH_SOURCE[0]}\" == \"${0}\" ]]; then","class":"lineCov","hits":"1","order":"3580",},
{"lineNum":"  567","line":"  main \"$@\"","class":"lineCov","hits":"1","order":"3579",},
{"lineNum":"  568","line":"fi"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "update-all-indexes.sh", "date" : "2026-08-26 18:58:42", "instrumented" : 243, "covered" : 232,};
var merged_data = [];
