var data = {lines:[
{"lineNum":"    1","line":"# shellcheck shell=bash"},
{"lineNum":"    2","line":"#"},
{"lineNum":"    3","line":"# Finding and validating a script\'s configuration."},
{"lineNum":"    4","line":"#"},
{"lineNum":"    5","line":"# Sourced at development time and inlined by compile-includes.sh at build time."},
{"lineNum":"    6","line":""},
{"lineNum":"    7","line":"# Double-source guard"},
{"lineNum":"    8","line":"if [[ \"${_CONFIG_SH_LOADED:-}\" == \"true\" ]]; then","class":"lineCov","hits":"1","order":"1147",},
{"lineNum":"    9","line":"  return 0","class":"lineNoCov","hits":"0",},
{"lineNum":"   10","line":"fi"},
{"lineNum":"   11","line":"_CONFIG_SH_LOADED=\"true\"","class":"lineCov","hits":"1","order":"1142",},
{"lineNum":"   12","line":""},
{"lineNum":"   13","line":"# Logging, and the install prefix the search below uses. Declared here rather than left to each script:"},
{"lineNum":"   14","line":"# the compiler follows this and inlines core.sh once, so a script that wants a config need not know that a"},
{"lineNum":"   15","line":"# config needs a logger."},
{"lineNum":"   16","line":"# shellcheck source=./core.sh"},
{"lineNum":"   17","line":"source \"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" && pwd -P)/core.sh\"","class":"lineCov","hits":"1","order":"1154",},
{"lineNum":"   18","line":"# @include core.sh"},
{"lineNum":"   19","line":""},
{"lineNum":"   20","line":"########################################"},
{"lineNum":"   21","line":"# Sources a configuration file, announcing which one."},
{"lineNum":"   22","line":"# nounset is relaxed around the source so a config may reference variables that are not set, and"},
{"lineNum":"   23","line":"# restored afterwards so the script\'s own strictness is unaffected."},
{"lineNum":"   24","line":"# Arguments:"},
{"lineNum":"   25","line":"#   path: The configuration file to source."},
{"lineNum":"   26","line":"########################################"},
{"lineNum":"   27","line":"_source_config() {"},
{"lineNum":"   28","line":"  log_info \"Loading configuration from: $1\"","class":"lineCov","hits":"1","order":"1173",},
{"lineNum":"   29","line":"  set +o nounset","class":"lineCov","hits":"1","order":"1175",},
{"lineNum":"   30","line":"  # shellcheck source=/dev/null"},
{"lineNum":"   31","line":"  source \"$1\"","class":"lineCov","hits":"1","order":"1156",},
{"lineNum":"   32","line":"  set -o nounset","class":"lineCov","hits":"1","order":"1177",},
{"lineNum":"   33","line":"}"},
{"lineNum":"   34","line":""},
{"lineNum":"   35","line":"########################################"},
{"lineNum":"   36","line":"# Finds and sources the configuration file."},
{"lineNum":"   37","line":"# Search order:"},
{"lineNum":"   38","line":"#   0. $CONFIG_FILE, when set"},
{"lineNum":"   39","line":"#   1. Same directory as the script (for standalone/tarball use)"},
{"lineNum":"   40","line":"#   2. <install-prefix>/etc/ (for Homebrew/package installs)"},
{"lineNum":"   41","line":"#   3. /etc/ (system-wide fallback)"},
{"lineNum":"   42","line":"# Globals:"},
{"lineNum":"   43","line":"#   CONFIG_FILE, SCRIPT_NAME"},
{"lineNum":"   44","line":"# Arguments:"},
{"lineNum":"   45","line":"#   None"},
{"lineNum":"   46","line":"# Returns:"},
{"lineNum":"   47","line":"#   0 if config was found and sourced, 2 if CONFIG_FILE names a file that cannot be read, 1 if no"},
{"lineNum":"   48","line":"#   config file exists. The two failures are distinguished because \"you asked for a file I cannot"},
{"lineNum":"   49","line":"#   read\" is a user error every caller should refuse, while \"there is no config\" is normal for a"},
{"lineNum":"   50","line":"#   script whose every setting has a default."},
{"lineNum":"   51","line":"########################################"},
{"lineNum":"   52","line":"load_config() {"},
{"lineNum":"   53","line":"  # A named file wins outright, and an unreadable one is an error rather than a quiet fall back to the"},
{"lineNum":"   54","line":"  # search: naming a file excludes the alternatives, so silently loading a different config — with"},
{"lineNum":"   55","line":"  # different backup targets or credentials in it — would be worse than refusing."},
{"lineNum":"   56","line":"  if [[ -n \"${CONFIG_FILE:-}\" ]]; then","class":"lineCov","hits":"1","order":"1155",},
{"lineNum":"   57","line":"    if [[ ! -r \"${CONFIG_FILE}\" ]]; then","class":"lineCov","hits":"1","order":"1159",},
{"lineNum":"   58","line":"      log_error \"CONFIG_FILE is set to \'${CONFIG_FILE}\', which does not exist or is not readable.\"","class":"lineCov","hits":"1","order":"1164",},
{"lineNum":"   59","line":"      return 2","class":"lineCov","hits":"1","order":"1165",},
{"lineNum":"   60","line":"    fi"},
{"lineNum":"   61","line":"    _source_config \"${CONFIG_FILE}\"","class":"lineCov","hits":"1","order":"1160",},
{"lineNum":"   62","line":"    return","class":"lineCov","hits":"1","order":"1145",},
{"lineNum":"   63","line":"  fi"},
{"lineNum":"   64","line":""},
{"lineNum":"   65","line":"  local script_dir","class":"lineCov","hits":"1","order":"1144",},
{"lineNum":"   66","line":"  script_dir=$(cd \"$(dirname \"$0\")\" && pwd -P)","class":"lineCov","hits":"1","order":"1146",},
{"lineNum":"   67","line":"  local config_path_local=\"${script_dir}/${SCRIPT_NAME}.conf\"","class":"lineCov","hits":"1","order":"1148",},
{"lineNum":"   68","line":""},
{"lineNum":"   69","line":"  local prefix","class":"lineCov","hits":"1","order":"1150",},
{"lineNum":"   70","line":"  prefix=$(_get_script_prefix)","class":"lineCov","hits":"1","order":"1141",},
{"lineNum":"   71","line":"  local config_path_prefix=\"\"","class":"lineCov","hits":"1","order":"1139",},
{"lineNum":"   72","line":"  local config_path_system=\"/etc/${SCRIPT_NAME}.conf\"","class":"lineCov","hits":"1","order":"1138",},
{"lineNum":"   73","line":""},
{"lineNum":"   74","line":"  if [[ -n \"${prefix}\" ]]; then","class":"lineCov","hits":"1","order":"1136",},
{"lineNum":"   75","line":"    config_path_prefix=\"${prefix}/etc/${SCRIPT_NAME}.conf\"","class":"lineCov","hits":"1","order":"1152",},
{"lineNum":"   76","line":"  fi"},
{"lineNum":"   77","line":""},
{"lineNum":"   78","line":"  local config_to_load=\"\"","class":"lineCov","hits":"1","order":"1134",},
{"lineNum":"   79","line":"  if [[ -r \"${config_path_local}\" ]]; then","class":"lineCov","hits":"1","order":"1133",},
{"lineNum":"   80","line":"    config_to_load=\"${config_path_local}\"","class":"lineCov","hits":"1","order":"1131",},
{"lineNum":"   81","line":"  elif [[ -n \"${config_path_prefix}\" && -r \"${config_path_prefix}\" ]]; then","class":"lineCov","hits":"1","order":"1129",},
{"lineNum":"   82","line":"    config_to_load=\"${config_path_prefix}\"","class":"lineCov","hits":"1","order":"1127",},
{"lineNum":"   83","line":"  elif [[ -r \"${config_path_system}\" ]]; then","class":"lineCov","hits":"1","order":"1126",},
{"lineNum":"   84","line":"    config_to_load=\"${config_path_system}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"   85","line":"  fi"},
{"lineNum":"   86","line":""},
{"lineNum":"   87","line":"  if [[ -z \"${config_to_load}\" ]]; then","class":"lineCov","hits":"1","order":"1157",},
{"lineNum":"   88","line":"    return 1","class":"lineCov","hits":"1","order":"1162",},
{"lineNum":"   89","line":"  fi"},
{"lineNum":"   90","line":""},
{"lineNum":"   91","line":"  _source_config \"${config_to_load}\"","class":"lineCov","hits":"1","order":"1161",},
{"lineNum":"   92","line":"}"},
{"lineNum":"   93","line":""},
{"lineNum":"   94","line":"########################################"},
{"lineNum":"   95","line":"# Loads configuration for a script that can run without one."},
{"lineNum":"   96","line":"# An absent config is normal for such a script, since every setting has a default — but a CONFIG_FILE"},
{"lineNum":"   97","line":"# naming a file that cannot be read is a user error, because carrying on would apply the very defaults"},
{"lineNum":"   98","line":"# the caller believes they have overridden. Callers redirect stdout themselves when they do not want"},
{"lineNum":"   99","line":"# _source_config\'s \"Loading configuration from\" line; the refusal goes to stderr either way."},
{"lineNum":"  100","line":"# Globals:"},
{"lineNum":"  101","line":"#   CONFIG_FILE, SCRIPT_NAME"},
{"lineNum":"  102","line":"# Returns:"},
{"lineNum":"  103","line":"#   0 whether or not a config was found, 1 when CONFIG_FILE cannot be read (load_config has logged why)."},
{"lineNum":"  104","line":"########################################"},
{"lineNum":"  105","line":"load_optional_config() {"},
{"lineNum":"  106","line":"  local status=0","class":"lineCov","hits":"1","order":"1166",},
{"lineNum":"  107","line":"  load_config || status=$?","class":"lineCov","hits":"1","order":"1167",},
{"lineNum":"  108","line":"  (( status != 2 ))","class":"lineCov","hits":"1","order":"1168",},
{"lineNum":"  109","line":"}"},
{"lineNum":"  110","line":""},
{"lineNum":"  111","line":"########################################"},
{"lineNum":"  112","line":"# Validates configuration variables according to type-prefixed rules."},
{"lineNum":"  113","line":"# Each argument is either \"NAME\" (non-empty string check) or \"TYPE:NAME\"."},
{"lineNum":"  114","line":"# Supported types:"},
{"lineNum":"  115","line":"#   (none)  — variable must be set and non-empty (default)"},
{"lineNum":"  116","line":"#   int     — variable must be a positive integer"},
{"lineNum":"  117","line":"#   array   — variable must be a declared, non-empty array"},
{"lineNum":"  118","line":"# Globals:"},
{"lineNum":"  119","line":"#   None (checks variables by name)"},
{"lineNum":"  120","line":"# Arguments:"},
{"lineNum":"  121","line":"#   Type-prefixed variable names to check (e.g., \"HOST\" \"int:PORT\" \"array:DIRS\")."},
{"lineNum":"  122","line":"# Returns:"},
{"lineNum":"  123","line":"#   0 if all checks pass, 1 if any fail."},
{"lineNum":"  124","line":"########################################"},
{"lineNum":"  125","line":"validate_config() {"},
{"lineNum":"  126","line":"  local has_errors=false","class":"lineCov","hits":"1","order":"1149",},
{"lineNum":"  127","line":""},
{"lineNum":"  128","line":"  for spec in \"$@\"; do","class":"lineCov","hits":"1","order":"1151",},
{"lineNum":"  129","line":"    local var_type=\"string\"","class":"lineCov","hits":"1","order":"1143",},
{"lineNum":"  130","line":"    local var_name=\"${spec}\"","class":"lineCov","hits":"1","order":"1140",},
{"lineNum":"  131","line":""},
{"lineNum":"  132","line":"    if [[ \"${spec}\" == *:* ]]; then","class":"lineCov","hits":"1","order":"1169",},
{"lineNum":"  133","line":"      var_type=\"${spec%%:*}\"","class":"lineCov","hits":"1","order":"1137",},
{"lineNum":"  134","line":"      var_name=\"${spec#*:}\"","class":"lineCov","hits":"1","order":"1153",},
{"lineNum":"  135","line":"    fi"},
{"lineNum":"  136","line":""},
{"lineNum":"  137","line":"    case \"${var_type}\" in","class":"lineCov","hits":"1","order":"1135",},
{"lineNum":"  138","line":"      string)"},
{"lineNum":"  139","line":"        if [[ -z \"${!var_name:-}\" ]]; then","class":"lineCov","hits":"1","order":"1132",},
{"lineNum":"  140","line":"          log_error \"Required setting \'${var_name}\' is missing or empty.\"","class":"lineCov","hits":"1","order":"1130",},
{"lineNum":"  141","line":"          has_errors=true","class":"lineCov","hits":"1","order":"1128",},
{"lineNum":"  142","line":"        fi"},
{"lineNum":"  143","line":"        ;;"},
{"lineNum":"  144","line":"      int)"},
{"lineNum":"  145","line":"        if [[ ! \"${!var_name:-}\" =~ ^[1-9][0-9]*$ ]]; then","class":"lineCov","hits":"1","order":"1170",},
{"lineNum":"  146","line":"          log_error \"${var_name} must be a positive integer, got \'${!var_name:-}\'.\"","class":"lineCov","hits":"1","order":"1158",},
{"lineNum":"  147","line":"          has_errors=true","class":"lineCov","hits":"1","order":"1163",},
{"lineNum":"  148","line":"        fi"},
{"lineNum":"  149","line":"        ;;"},
{"lineNum":"  150","line":"      array)"},
{"lineNum":"  151","line":"        # The declared attributes distinguish an array from a plain string: ${#var[@]} is 1 for a"},
{"lineNum":"  152","line":"        # scalar, so a length check alone accepts any non-empty value and the type is never verified."},
{"lineNum":"  153","line":"        local declaration=\"\" attributes=\"\"","class":"lineCov","hits":"1","order":"1171",},
{"lineNum":"  154","line":"        if declaration=$(declare -p \"${var_name}\" 2>/dev/null); then","class":"lineCov","hits":"1","order":"1172",},
{"lineNum":"  155","line":"          attributes=\"${declaration#declare -}\"","class":"lineCov","hits":"1","order":"1174",},
{"lineNum":"  156","line":"          attributes=\"${attributes%% *}\"","class":"lineCov","hits":"1","order":"1176",},
{"lineNum":"  157","line":"        fi"},
{"lineNum":"  158","line":""},
{"lineNum":"  159","line":"        if [[ -z \"${declaration}\" ]]; then","class":"lineCov","hits":"1","order":"1178",},
{"lineNum":"  160","line":"          log_error \"Required setting \'${var_name}\' is missing or empty.\"","class":"lineCov","hits":"1","order":"1179",},
{"lineNum":"  161","line":"          has_errors=true","class":"lineCov","hits":"1","order":"1180",},
{"lineNum":"  162","line":"        elif [[ \"${attributes}\" != *[aA]* ]]; then","class":"lineCov","hits":"1","order":"1181",},
{"lineNum":"  163","line":"          log_error \"Required setting \'${var_name}\' must be an array, e.g. ${var_name}=(one two).\"","class":"lineCov","hits":"1","order":"1182",},
{"lineNum":"  164","line":"          has_errors=true","class":"lineCov","hits":"1","order":"1125",},
{"lineNum":"  165","line":"        elif eval \"(( \\${#${var_name}[@]} == 0 ))\"; then","class":"lineCov","hits":"1","order":"1124",},
{"lineNum":"  166","line":"          log_error \"Required setting \'${var_name}\' is missing or empty.\"","class":"lineCov","hits":"1","order":"1123",},
{"lineNum":"  167","line":"          has_errors=true","class":"lineCov","hits":"1","order":"1122",},
{"lineNum":"  168","line":"        fi"},
{"lineNum":"  169","line":"        ;;"},
{"lineNum":"  170","line":"      *)"},
{"lineNum":"  171","line":"        log_error \"Unknown validation type \'${var_type}\' for \'${var_name}\'.\"","class":"lineCov","hits":"1","order":"1121",},
{"lineNum":"  172","line":"        has_errors=true","class":"lineCov","hits":"1","order":"1120",},
{"lineNum":"  173","line":"        ;;"},
{"lineNum":"  174","line":"    esac"},
{"lineNum":"  175","line":"  done"},
{"lineNum":"  176","line":""},
{"lineNum":"  177","line":"  if [[ \"${has_errors}\" == \"true\" ]]; then","class":"lineCov","hits":"1","order":"1119",},
{"lineNum":"  178","line":"    return 1","class":"lineCov","hits":"1","order":"1118",},
{"lineNum":"  179","line":"  fi"},
{"lineNum":"  180","line":"}"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "update-all-indexes.sh", "date" : "2026-08-19 12:33:32", "instrumented" : 67, "covered" : 65,};
var merged_data = [];
