var data = {lines:[
{"lineNum":"    1","line":"#!/usr/bin/env bash"},
{"lineNum":"    2","line":"#"},
{"lineNum":"    3","line":"# A robust script for backing up photo collections from multiple sources"},
{"lineNum":"    4","line":"# to a remote server using rsync."},
{"lineNum":"    5","line":"#"},
{"lineNum":"    6","line":"# This script requires all settings to be provided either via a system-wide"},
{"lineNum":"    7","line":"# configuration file or through command-line options."},
{"lineNum":"    8","line":""},
{"lineNum":"    9","line":"set -o errexit","class":"lineCov","hits":"1","order":"1641",},
{"lineNum":"   10","line":"set -o nounset","class":"lineCov","hits":"1","order":"1640",},
{"lineNum":"   11","line":"set -o pipefail","class":"lineCov","hits":"1","order":"1642",},
{"lineNum":"   12","line":""},
{"lineNum":"   13","line":"# --- Global Constants ---"},
{"lineNum":"   14","line":"TEMP_DIR=$(mktemp -d)","class":"lineCov","hits":"1","order":"1652",},
{"lineNum":"   15","line":"readonly TEMP_DIR","class":"lineCov","hits":"1","order":"1645",},
{"lineNum":"   16","line":""},
{"lineNum":"   17","line":"# --- Shared Library ---"},
{"lineNum":"   18","line":"# shellcheck source=../lib/common.sh"},
{"lineNum":"   19","line":"source \"$(cd \"$(dirname \"$0\")\" && pwd -P)/../lib/common.sh\"","class":"lineCov","hits":"1","order":"1635",},
{"lineNum":"   20","line":"# @include ../lib/common.sh"},
{"lineNum":"   21","line":""},
{"lineNum":"   22","line":"# --- Configuration (initialized as empty) ---"},
{"lineNum":"   23","line":"SOURCES=()"},
{"lineNum":"   24","line":"HOST=\"\"","class":"lineCov","hits":"1","order":"1639",},
{"lineNum":"   25","line":"DEST_PATH=\"\"","class":"lineCov","hits":"1","order":"1633",},
{"lineNum":"   26","line":"LOG_FILE=\"\"","class":"lineCov","hits":"1","order":"1653",},
{"lineNum":"   27","line":"DRY_RUN_FLAG=\"\"","class":"lineCov","hits":"1","order":"1638",},
{"lineNum":"   28","line":""},
{"lineNum":"   29","line":"# --- Runtime variables ---"},
{"lineNum":"   30","line":"DESTINATION=\"\" # Will be set in main after config is validated.","class":"lineCov","hits":"1","order":"1654",},
{"lineNum":"   31","line":""},
{"lineNum":"   32","line":"trap \'rm -rf \"${TEMP_DIR}\"\' EXIT","class":"lineCov","hits":"1","order":"1634",},
{"lineNum":"   33","line":""},
{"lineNum":"   34","line":"#######################################"},
{"lineNum":"   35","line":"# Prints the script\'s usage instructions to stdout."},
{"lineNum":"   36","line":"# Globals:"},
{"lineNum":"   37","line":"#   SCRIPT_NAME"},
{"lineNum":"   38","line":"# Arguments:"},
{"lineNum":"   39","line":"#   None"},
{"lineNum":"   40","line":"# Outputs:"},
{"lineNum":"   41","line":"#   Writes usage text to stdout."},
{"lineNum":"   42","line":"#######################################"},
{"lineNum":"   43","line":"show_usage() {"},
{"lineNum":"   44","line":"  cat <<EOF","class":"lineCov","hits":"1","order":"1626",},
{"lineNum":"   45","line":"Usage: ${SCRIPT_NAME} [OPTIONS]"},
{"lineNum":"   46","line":"Syncs photos from multiple sources to a remote backup server."},
{"lineNum":"   47","line":""},
{"lineNum":"   48","line":"Required settings must be provided either in a config file"},
{"lineNum":"   49","line":"(e.g., /etc/${SCRIPT_NAME}.conf) or via the options below."},
{"lineNum":"   50","line":""},
{"lineNum":"   51","line":"Options:"},
{"lineNum":"   52","line":"  -s PATH       Source path (can be used multiple times)"},
{"lineNum":"   53","line":"  -H HOST       Backup server hostname (required)"},
{"lineNum":"   54","line":"  -p PATH       Destination path (required)"},
{"lineNum":"   55","line":"  -l FILE       Log file path (optional)"},
{"lineNum":"   56","line":"  -n            Dry-run mode (no changes are made)"},
{"lineNum":"   57","line":"  -d            Debug mode (enables verbose logging)"},
{"lineNum":"   58","line":"  -h            Show this help message"},
{"lineNum":"   59","line":"EOF"},
{"lineNum":"   60","line":"}"},
{"lineNum":"   61","line":""},
{"lineNum":"   62","line":"#######################################"},
{"lineNum":"   63","line":"# Parses command-line options, overriding any config file values."},
{"lineNum":"   64","line":"# Globals:"},
{"lineNum":"   65","line":"#   SOURCES, HOST, DEST_PATH, LOG_FILE, DRY_RUN_FLAG"},
{"lineNum":"   66","line":"# Arguments:"},
{"lineNum":"   67","line":"#   Command-line arguments passed to the script."},
{"lineNum":"   68","line":"#######################################"},
{"lineNum":"   69","line":"parse_options() {"},
{"lineNum":"   70","line":"  while getopts \":s:H:p:l:ndh\" opt; do","class":"lineCov","hits":"1","order":"1643",},
{"lineNum":"   71","line":"    case \"${opt}\" in","class":"lineCov","hits":"1","order":"1644",},
{"lineNum":"   72","line":"      s) SOURCES+=(\"${OPTARG}\") ;;","class":"lineNoCov","hits":"0",},
{"lineNum":"   73","line":"      H) HOST=\"${OPTARG}\" ;;","class":"lineNoCov","hits":"0",},
{"lineNum":"   74","line":"      p) DEST_PATH=\"${OPTARG}\" ;;","class":"lineNoCov","hits":"0",},
{"lineNum":"   75","line":"      l) LOG_FILE=\"${OPTARG}\" ;;","class":"lineNoCov","hits":"0",},
{"lineNum":"   76","line":"      n) DRY_RUN_FLAG=\"--dry-run\" ;;","class":"lineNoCov","hits":"0",},
{"lineNum":"   77","line":"      d) enable_debug_mode ;;","class":"lineNoCov","hits":"0",},
{"lineNum":"   78","line":"      h)"},
{"lineNum":"   79","line":"        show_usage","class":"lineCov","hits":"1","order":"1647",},
{"lineNum":"   80","line":"        exit 0","class":"lineCov","hits":"1","order":"1648",},
{"lineNum":"   81","line":"        ;;"},
{"lineNum":"   82","line":"      :)"},
{"lineNum":"   83","line":"        log_error \"Option -${OPTARG} requires an argument.\"","class":"lineNoCov","hits":"0",},
{"lineNum":"   84","line":"        show_usage","class":"lineNoCov","hits":"0",},
{"lineNum":"   85","line":"        exit 1","class":"lineNoCov","hits":"0",},
{"lineNum":"   86","line":"        ;;"},
{"lineNum":"   87","line":"      *)"},
{"lineNum":"   88","line":"        log_error \"Invalid option: -${OPTARG}\"","class":"lineCov","hits":"1","order":"1632",},
{"lineNum":"   89","line":"        show_usage","class":"lineCov","hits":"1","order":"1650",},
{"lineNum":"   90","line":"        exit 1","class":"lineCov","hits":"1","order":"1637",},
{"lineNum":"   91","line":"        ;;"},
{"lineNum":"   92","line":"    esac"},
{"lineNum":"   93","line":"  done"},
{"lineNum":"   94","line":"  shift $((OPTIND - 1))","class":"lineCov","hits":"1","order":"1631",},
{"lineNum":"   95","line":""},
{"lineNum":"   96","line":"  if (( $# > 0 )); then","class":"lineCov","hits":"1","order":"1630",},
{"lineNum":"   97","line":"    log_error \"Unexpected arguments: $*\"","class":"lineCov","hits":"1","order":"1629",},
{"lineNum":"   98","line":"    show_usage","class":"lineCov","hits":"1","order":"1628",},
{"lineNum":"   99","line":"    exit 1","class":"lineCov","hits":"1","order":"1627",},
{"lineNum":"  100","line":"  fi"},
{"lineNum":"  101","line":"}"},
{"lineNum":"  102","line":""},
{"lineNum":"  103","line":"#######################################"},
{"lineNum":"  104","line":"# Logs a command to debug, then executes it, capturing output to the log file."},
{"lineNum":"  105","line":"# Globals:"},
{"lineNum":"  106","line":"#   LOG_FILE"},
{"lineNum":"  107","line":"# Arguments:"},
{"lineNum":"  108","line":"#   Command and its arguments."},
{"lineNum":"  109","line":"#######################################"},
{"lineNum":"  110","line":"run_command() {"},
{"lineNum":"  111","line":"  log_debug \"Running command: $*\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  112","line":"  if [[ -n \"${LOG_FILE}\" ]]; then","class":"lineNoCov","hits":"0",},
{"lineNum":"  113","line":"    # Log both streams to the file while preserving stderr/stdout separation"},
{"lineNum":"  114","line":"    \"$@\" > >(tee -a \"${LOG_FILE}\") 2> >(tee -a \"${LOG_FILE}\" >&2)","class":"lineNoCov","hits":"0",},
{"lineNum":"  115","line":"  else"},
{"lineNum":"  116","line":"    \"$@\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  117","line":"  fi"},
{"lineNum":"  118","line":"}"},
{"lineNum":"  119","line":""},
{"lineNum":"  120","line":"#######################################"},
{"lineNum":"  121","line":"# Verifies that a source directory exists and is not empty."},
{"lineNum":"  122","line":"# Arguments:"},
{"lineNum":"  123","line":"#   Directory path to verify."},
{"lineNum":"  124","line":"#######################################"},
{"lineNum":"  125","line":"verify_source_directory() {"},
{"lineNum":"  126","line":"  local dir=\"$1\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  127","line":""},
{"lineNum":"  128","line":"  if [[ ! -d \"${dir}\" ]]; then","class":"lineNoCov","hits":"0",},
{"lineNum":"  129","line":"    log_error \"Source directory \'${dir}\' not found or not mounted.\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  130","line":"    exit 1","class":"lineNoCov","hits":"0",},
{"lineNum":"  131","line":"  fi"},
{"lineNum":"  132","line":""},
{"lineNum":"  133","line":"  if ! find \"${dir}\" -mindepth 1 -print -quit | grep -q .; then","class":"lineNoCov","hits":"0",},
{"lineNum":"  134","line":"    log_error \"Source directory \'${dir}\' appears to be empty. Aborting for safety.\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  135","line":"    exit 1","class":"lineNoCov","hits":"0",},
{"lineNum":"  136","line":"  fi"},
{"lineNum":"  137","line":"}"},
{"lineNum":"  138","line":""},
{"lineNum":"  139","line":"#######################################"},
{"lineNum":"  140","line":"# Removes files matching a pattern from a directory."},
{"lineNum":"  141","line":"# Arguments:"},
{"lineNum":"  142","line":"#   dir: The directory to clean."},
{"lineNum":"  143","line":"#   pattern: The file pattern to remove (e.g., \'*.tmp\')."},
{"lineNum":"  144","line":"#######################################"},
{"lineNum":"  145","line":"remove_files() {"},
{"lineNum":"  146","line":"  local dir=\"$1\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  147","line":"  local pattern=\"$2\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  148","line":""},
{"lineNum":"  149","line":"  log_info \"Deleting \'${pattern}\' files from \'${dir}\'...\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  150","line":"  run_command find \"${dir}\" -name \"${pattern}\" -delete -print","class":"lineNoCov","hits":"0",},
{"lineNum":"  151","line":"}"},
{"lineNum":"  152","line":""},
{"lineNum":"  153","line":"#######################################"},
{"lineNum":"  154","line":"# Cleans a directory of common temporary and metadata files."},
{"lineNum":"  155","line":"# The following are removed:"},
{"lineNum":"  156","line":"#   - .DS_Store: macOS Finder metadata, not needed in backups."},
{"lineNum":"  157","line":"#   - *_original: Lightroom/Photoshop original files created when"},
{"lineNum":"  158","line":"#     editing (e.g., \"IMG_1234_original\"). Safe to remove since the"},
{"lineNum":"  159","line":"#     actual originals are the RAW files."},
{"lineNum":"  160","line":"# Arguments:"},
{"lineNum":"  161","line":"#   dir: The directory to clean."},
{"lineNum":"  162","line":"#######################################"},
{"lineNum":"  163","line":"clean_directory() {"},
{"lineNum":"  164","line":"  local dir=\"$1\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  165","line":""},
{"lineNum":"  166","line":"  log_info \"Cleaning temporary files in \'${dir}\'...\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  167","line":"  remove_files \"${dir}\" \'.DS_Store\'","class":"lineNoCov","hits":"0",},
{"lineNum":"  168","line":"  remove_files \"${dir}\" \'*_original\'","class":"lineNoCov","hits":"0",},
{"lineNum":"  169","line":""},
{"lineNum":"  170","line":"  if command -v dot_clean &> /dev/null; then","class":"lineNoCov","hits":"0",},
{"lineNum":"  171","line":"    run_command dot_clean -v \"${dir}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  172","line":"  else"},
{"lineNum":"  173","line":"    log_info \"Skipping \'dot_clean\': command not found (expected on non-macOS).\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  174","line":"  fi"},
{"lineNum":"  175","line":"}"},
{"lineNum":"  176","line":""},
{"lineNum":"  177","line":"#######################################"},
{"lineNum":"  178","line":"# Generates rsync protection filter rules from multiple directories."},
{"lineNum":"  179","line":"# Arguments:"},
{"lineNum":"  180","line":"#   filter_file: The path to write the generated filter rules to."},
{"lineNum":"  181","line":"#   protect_dirs: An array of source directories whose contents should be protected."},
{"lineNum":"  182","line":"#######################################"},
{"lineNum":"  183","line":"generate_protection_filter() {"},
{"lineNum":"  184","line":"  local filter_file=\"$1\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  185","line":"  shift","class":"lineNoCov","hits":"0",},
{"lineNum":"  186","line":"  local protect_dirs=(\"$@\")","class":"lineNoCov","hits":"0",},
{"lineNum":"  187","line":""},
{"lineNum":"  188","line":"  # Truncate the filter file to ensure it\'s empty before starting"},
{"lineNum":"  189","line":"  true > \"${filter_file}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  190","line":""},
{"lineNum":"  191","line":"  for protect_src in \"${protect_dirs[@]}\"; do","class":"lineNoCov","hits":"0",},
{"lineNum":"  192","line":"    log_info \"Generating protection rules for \'${protect_src}\'\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  193","line":"    # Use sh to create a subshell, ensuring path variables are handled correctly"},
{"lineNum":"  194","line":"    run_command bash -c \'","class":"lineNoCov","hits":"0",},
{"lineNum":"  195","line":"      set -o errexit","class":"lineNoCov","hits":"0",},
{"lineNum":"  196","line":"      set -o pipefail","class":"lineNoCov","hits":"0",},
{"lineNum":"  197","line":"      # The find command lists all items, and the while loop creates relative paths"},
{"lineNum":"  198","line":"      find \"$1\" -mindepth 1 -print0 | while IFS= read -r -d \"\" path; do","class":"lineNoCov","hits":"0",},
{"lineNum":"  199","line":"        relative_path=\"${path#\"$1\"/}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  200","line":"        # \"P\" is rsync syntax to protect the path from deletion"},
{"lineNum":"  201","line":"        printf \"P /%s\\n\" \"${relative_path}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  202","line":"      done >> \"$2\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  203","line":"    \' _ \"${protect_src}\" \"${filter_file}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  204","line":"  done"},
{"lineNum":"  205","line":"}"},
{"lineNum":"  206","line":""},
{"lineNum":"  207","line":"#######################################"},
{"lineNum":"  208","line":"# Validates that a filter file exists and is not empty."},
{"lineNum":"  209","line":"# Arguments:"},
{"lineNum":"  210","line":"#   filter_file: Path to the filter file to validate."},
{"lineNum":"  211","line":"#######################################"},
{"lineNum":"  212","line":"validate_filter_file() {"},
{"lineNum":"  213","line":"  local filter_file=\"$1\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  214","line":""},
{"lineNum":"  215","line":"  if [[ ! -f \"${filter_file}\" ]]; then","class":"lineNoCov","hits":"0",},
{"lineNum":"  216","line":"    log_error \"FATAL: Protection filter file \'${filter_file}\' was not created.\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  217","line":"    exit 1","class":"lineNoCov","hits":"0",},
{"lineNum":"  218","line":"  fi"},
{"lineNum":"  219","line":""},
{"lineNum":"  220","line":"  if [[ ! -s \"${filter_file}\" ]]; then","class":"lineNoCov","hits":"0",},
{"lineNum":"  221","line":"    log_error \"FATAL: Protection filter file \'${filter_file}\' is empty. Aborting to prevent data loss.\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  222","line":"    exit 1","class":"lineNoCov","hits":"0",},
{"lineNum":"  223","line":"  fi"},
{"lineNum":"  224","line":"}"},
{"lineNum":"  225","line":""},
{"lineNum":"  226","line":"#######################################"},
{"lineNum":"  227","line":"# Performs the rsync backup operation, optionally using a protection filter."},
{"lineNum":"  228","line":"# Globals:"},
{"lineNum":"  229","line":"#   DESTINATION, DRY_RUN_FLAG"},
{"lineNum":"  230","line":"# Arguments:"},
{"lineNum":"  231","line":"#   source_dir: The directory to back up."},
{"lineNum":"  232","line":"#   filter_file: (Optional) The path to the rsync filter file. If empty,"},
{"lineNum":"  233","line":"#                no filter is used."},
{"lineNum":"  234","line":"#######################################"},
{"lineNum":"  235","line":"perform_backup() {"},
{"lineNum":"  236","line":"  local source_dir=\"$1\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  237","line":"  # Default to empty string if filter_file is not provided"},
{"lineNum":"  238","line":"  local filter_file=\"${2:-}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  239","line":""},
{"lineNum":"  240","line":"  log_info \"Backing up \'${source_dir}\' to \'${DESTINATION}\'...\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  241","line":""},
{"lineNum":"  242","line":"  local rsync_args=(","class":"lineNoCov","hits":"0",},
{"lineNum":"  243","line":"    -aHv","class":"lineNoCov","hits":"0",},
{"lineNum":"  244","line":"    --progress","class":"lineNoCov","hits":"0",},
{"lineNum":"  245","line":"    --exclude \'.*\'","class":"lineNoCov","hits":"0",},
{"lineNum":"  246","line":"    --delete","class":"lineNoCov","hits":"0",},
{"lineNum":"  247","line":"  )"},
{"lineNum":"  248","line":""},
{"lineNum":"  249","line":"  if [[ -n \"${DRY_RUN_FLAG}\" ]]; then","class":"lineNoCov","hits":"0",},
{"lineNum":"  250","line":"    rsync_args+=(\"${DRY_RUN_FLAG}\")","class":"lineNoCov","hits":"0",},
{"lineNum":"  251","line":"  fi"},
{"lineNum":"  252","line":""},
{"lineNum":"  253","line":"  if [[ -n \"${filter_file}\" ]]; then","class":"lineNoCov","hits":"0",},
{"lineNum":"  254","line":"    log_info \"Using protection filter: ${filter_file}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  255","line":"    rsync_args+=(--filter=\"merge ${filter_file}\")","class":"lineNoCov","hits":"0",},
{"lineNum":"  256","line":"  fi"},
{"lineNum":"  257","line":""},
{"lineNum":"  258","line":"  run_command rsync \"${rsync_args[@]}\" \"${source_dir}/\" \"${DESTINATION}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  259","line":"}"},
{"lineNum":"  260","line":""},
{"lineNum":"  261","line":"#######################################"},
{"lineNum":"  262","line":"# Loads config, parses CLI options, and runs the photo backup pipeline."},
{"lineNum":"  263","line":"# Globals:"},
{"lineNum":"  264","line":"#   SOURCES, HOST, DEST_PATH, LOG_FILE, DESTINATION, DRY_RUN_FLAG"},
{"lineNum":"  265","line":"# Arguments:"},
{"lineNum":"  266","line":"#   Command-line arguments passed to the script."},
{"lineNum":"  267","line":"#######################################"},
{"lineNum":"  268","line":"main() {"},
{"lineNum":"  269","line":"  load_config || true  # Config is optional; CLI args can provide everything","class":"lineCov","hits":"1","order":"1646",},
{"lineNum":"  270","line":"  parse_options \"$@\"","class":"lineCov","hits":"1","order":"1651",},
{"lineNum":"  271","line":"  validate_config \"HOST\" \"DEST_PATH\" \"array:SOURCES\" || { show_usage; exit 1; }","class":"lineNoCov","hits":"0",},
{"lineNum":"  272","line":""},
{"lineNum":"  273","line":"  # If LOG_FILE is not set, determine a default location based on the script\'s prefix"},
{"lineNum":"  274","line":"  if [[ -z \"${LOG_FILE}\" ]]; then","class":"lineNoCov","hits":"0",},
{"lineNum":"  275","line":"    local prefix","class":"lineNoCov","hits":"0",},
{"lineNum":"  276","line":"    prefix=$(get_script_prefix)","class":"lineNoCov","hits":"0",},
{"lineNum":"  277","line":"    if [[ -n \"${prefix}\" ]]; then","class":"lineNoCov","hits":"0",},
{"lineNum":"  278","line":"      LOG_FILE=\"${prefix}/var/log/${SCRIPT_NAME}.log\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  279","line":"      log_info \"No log file specified. Defaulting to: ${LOG_FILE}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  280","line":"    fi"},
{"lineNum":"  281","line":"  fi"},
{"lineNum":"  282","line":""},
{"lineNum":"  283","line":"  DESTINATION=\"${HOST}:${DEST_PATH}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  284","line":""},
{"lineNum":"  285","line":"  log_info \"Starting photo backup operation.\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  286","line":"  local source_label=\"directories\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  287","line":"  if (( ${#SOURCES[@]} == 1 )); then","class":"lineNoCov","hits":"0",},
{"lineNum":"  288","line":"    source_label=\"directory\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  289","line":"  fi"},
{"lineNum":"  290","line":"  log_info \"Found ${#SOURCES[@]} source ${source_label}:\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  291","line":"  for src in \"${SOURCES[@]}\"; do","class":"lineNoCov","hits":"0",},
{"lineNum":"  292","line":"    log_info \" -> ${src}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  293","line":"  done"},
{"lineNum":"  294","line":"  log_info \"Destination: ${DESTINATION}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  295","line":"  if [[ -n \"${LOG_FILE}\" ]]; then","class":"lineNoCov","hits":"0",},
{"lineNum":"  296","line":"    log_info \"Logging to: ${LOG_FILE}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  297","line":"  fi"},
{"lineNum":"  298","line":"  if [[ -n \"${DRY_RUN_FLAG}\" ]]; then","class":"lineNoCov","hits":"0",},
{"lineNum":"  299","line":"    log_info \"Dry-run mode is enabled. No files will be changed.\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  300","line":"  fi"},
{"lineNum":"  301","line":""},
{"lineNum":"  302","line":"  for src in \"${SOURCES[@]}\"; do","class":"lineNoCov","hits":"0",},
{"lineNum":"  303","line":"    verify_source_directory \"${src}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  304","line":"  done"},
{"lineNum":"  305","line":""},
{"lineNum":"  306","line":"  if [[ -z \"${DRY_RUN_FLAG}\" ]]; then","class":"lineNoCov","hits":"0",},
{"lineNum":"  307","line":"    for src in \"${SOURCES[@]}\"; do","class":"lineNoCov","hits":"0",},
{"lineNum":"  308","line":"      clean_directory \"${src}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  309","line":"    done"},
{"lineNum":"  310","line":"  fi"},
{"lineNum":"  311","line":""},
{"lineNum":"  312","line":"  # --- Main Backup Loop ---"},
{"lineNum":"  313","line":"  for i in \"${!SOURCES[@]}\"; do","class":"lineNoCov","hits":"0",},
{"lineNum":"  314","line":"    local current_source=\"${SOURCES[i]}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  315","line":"    local protect_sources=()","class":"lineNoCov","hits":"0",},
{"lineNum":"  316","line":""},
{"lineNum":"  317","line":"    # Build an array of all other sources to protect"},
{"lineNum":"  318","line":"    for j in \"${!SOURCES[@]}\"; do","class":"lineNoCov","hits":"0",},
{"lineNum":"  319","line":"      if (( i != j )); then","class":"lineNoCov","hits":"0",},
{"lineNum":"  320","line":"        protect_sources+=(\"${SOURCES[j]}\")","class":"lineNoCov","hits":"0",},
{"lineNum":"  321","line":"      fi"},
{"lineNum":"  322","line":"    done"},
{"lineNum":"  323","line":""},
{"lineNum":"  324","line":"    log_info \"--- Starting backup for \'${current_source}\' ---\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  325","line":""},
{"lineNum":"  326","line":"    local filter_file=\"\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  327","line":""},
{"lineNum":"  328","line":"    # If there are other sources, generate a protection filter for them"},
{"lineNum":"  329","line":"    if (( ${#protect_sources[@]} > 0 )); then","class":"lineNoCov","hits":"0",},
{"lineNum":"  330","line":"      filter_file=\"${TEMP_DIR}/filter.rules\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  331","line":"      generate_protection_filter \"${filter_file}\" \"${protect_sources[@]}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  332","line":"      validate_filter_file \"${filter_file}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  333","line":"    else"},
{"lineNum":"  334","line":"      log_info \"Only one source directory specified, or this is the only source; running sync without protection filter.\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  335","line":"    fi"},
{"lineNum":"  336","line":""},
{"lineNum":"  337","line":"    # Perform the backup, passing the filter file path (which will be empty if not generated)"},
{"lineNum":"  338","line":"    perform_backup \"${current_source}\" \"${filter_file}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  339","line":"  done"},
{"lineNum":"  340","line":""},
{"lineNum":"  341","line":"  log_info \"Backup operation completed successfully.\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  342","line":"}"},
{"lineNum":"  343","line":""},
{"lineNum":"  344","line":"# Only run when executed, not when sourced — the test suite sources this file to exercise its"},
{"lineNum":"  345","line":"# individual functions."},
{"lineNum":"  346","line":"if [[ \"${BASH_SOURCE[0]}\" == \"${0}\" ]]; then","class":"lineCov","hits":"1","order":"1649",},
{"lineNum":"  347","line":"  main \"$@\"","class":"lineCov","hits":"1","order":"1636",},
{"lineNum":"  348","line":"fi"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "update-readme-table.sh", "date" : "2026-08-11 23:41:13", "instrumented" : 135, "covered" : 29,};
var merged_data = [];
