var data = {lines:[
{"lineNum":"    1","line":"#!/usr/bin/env bash"},
{"lineNum":"    2","line":"#"},
{"lineNum":"    3","line":"# Recursively compares two directories and reports differences in existence,"},
{"lineNum":"    4","line":"# size, timestamps, and checksums. Reports missing directories at the top level"},
{"lineNum":"    5","line":"# rather than enumerating all their contents."},
{"lineNum":"    6","line":"#"},
{"lineNum":"    7","line":"# Usage:"},
{"lineNum":"    8","line":"#   ./compare-dirs.sh [OPTIONS] <dir1> <dir2>"},
{"lineNum":"    9","line":""},
{"lineNum":"   10","line":"set -o errexit","class":"lineCov","hits":"1","order":"5424",},
{"lineNum":"   11","line":"set -o nounset","class":"lineCov","hits":"1","order":"5386",},
{"lineNum":"   12","line":"set -o pipefail","class":"lineCov","hits":"1","order":"5383",},
{"lineNum":"   13","line":""},
{"lineNum":"   14","line":"# --- Shared Library ---"},
{"lineNum":"   15","line":"# shellcheck source=../../lib/colors.sh"},
{"lineNum":"   16","line":"source \"$(cd \"$(dirname \"$0\")\" && pwd -P)/../../lib/colors.sh\"","class":"lineCov","hits":"1","order":"5434",},
{"lineNum":"   17","line":"# @include ../../lib/colors.sh"},
{"lineNum":"   18","line":"# shellcheck source=../../lib/platform.sh"},
{"lineNum":"   19","line":"source \"$(cd \"$(dirname \"$0\")\" && pwd -P)/../../lib/platform.sh\"","class":"lineCov","hits":"1","order":"5404",},
{"lineNum":"   20","line":"# @include ../../lib/platform.sh"},
{"lineNum":"   21","line":"# shellcheck source=../../lib/cli.sh"},
{"lineNum":"   22","line":"source \"$(cd \"$(dirname \"$0\")\" && pwd -P)/../../lib/cli.sh\"","class":"lineCov","hits":"1","order":"5403",},
{"lineNum":"   23","line":"# @include ../../lib/cli.sh"},
{"lineNum":"   24","line":"# shellcheck source=../../lib/core.sh"},
{"lineNum":"   25","line":"source \"$(cd \"$(dirname \"$0\")\" && pwd -P)/../../lib/core.sh\"","class":"lineCov","hits":"1","order":"5373",},
{"lineNum":"   26","line":"# @include ../../lib/core.sh"},
{"lineNum":"   27","line":""},
{"lineNum":"   28","line":"# --- Global State ---"},
{"lineNum":"   29","line":"_opt_timestamps=false","class":"lineCov","hits":"1","order":"5430",},
{"lineNum":"   30","line":"_opt_checksums=false","class":"lineCov","hits":"1","order":"5410",},
{"lineNum":"   31","line":"_opt_no_color=false","class":"lineCov","hits":"1","order":"5407",},
{"lineNum":"   32","line":"_opt_ignore_case=false","class":"lineCov","hits":"1","order":"5422",},
{"lineNum":"   33","line":"_opt_no_dotfiles=false","class":"lineCov","hits":"1","order":"5522",},
{"lineNum":"   34","line":"_opt_excludes=()"},
{"lineNum":"   35","line":"_opt_excludes_left=()"},
{"lineNum":"   36","line":"_opt_excludes_right=()"},
{"lineNum":"   37","line":"_dir1=\"\"","class":"lineCov","hits":"1","order":"5459",},
{"lineNum":"   38","line":"_dir2=\"\"","class":"lineCov","hits":"1","order":"5453",},
{"lineNum":"   39","line":"_count_left_only=0","class":"lineCov","hits":"1","order":"5450",},
{"lineNum":"   40","line":"_count_right_only=0","class":"lineCov","hits":"1","order":"5445",},
{"lineNum":"   41","line":"_count_differences=0","class":"lineCov","hits":"1","order":"5467",},
{"lineNum":"   42","line":""},
{"lineNum":"   43","line":"# --- Color Variables (set by setup_colors \"${_opt_no_color}\") ---"},
{"lineNum":"   44","line":""},
{"lineNum":"   45","line":"########################################"},
{"lineNum":"   46","line":"# Prints the script\'s usage instructions."},
{"lineNum":"   47","line":"# Globals:"},
{"lineNum":"   48","line":"#   SCRIPT_NAME"},
{"lineNum":"   49","line":"########################################"},
{"lineNum":"   50","line":"show_usage() {"},
{"lineNum":"   51","line":"  cat <<EOF","class":"lineCov","hits":"1","order":"5413",},
{"lineNum":"   52","line":"Usage: ${SCRIPT_NAME} [OPTIONS] <dir1> <dir2>"},
{"lineNum":"   53","line":""},
{"lineNum":"   54","line":"Recursively compare two directories and report differences."},
{"lineNum":"   55","line":""},
{"lineNum":"   56","line":"Options:"},
{"lineNum":"   57","line":"  -t, --timestamps         Also compare file modification times"},
{"lineNum":"   58","line":"  -c, --checksums          Also compare file checksums (sha256)"},
{"lineNum":"   59","line":"  -i, --ignore-case        Case-insensitive filename matching"},
{"lineNum":"   60","line":"  -d, --no-dotfiles        Skip hidden (dot) files and directories"},
{"lineNum":"   61","line":"  -x, --exclude PAT        Skip entries matching glob pattern (repeatable)"},
{"lineNum":"   62","line":"      --exclude-left PAT   Suppress LEFT-only reports for matches (repeatable)"},
{"lineNum":"   63","line":"      --exclude-right PAT  Suppress RIGHT-only reports for matches (repeatable)"},
{"lineNum":"   64","line":"  -n, --no-color           Disable colored output"},
{"lineNum":"   65","line":"  -h, --help               Show this help message"},
{"lineNum":"   66","line":""},
{"lineNum":"   67","line":"Output markers:"},
{"lineNum":"   68","line":"  ←  Item exists only in LEFT directory"},
{"lineNum":"   69","line":"  →  Item exists only in RIGHT directory"},
{"lineNum":"   70","line":"  ≠  Item differs between directories"},
{"lineNum":"   71","line":"  ⚡ Type mismatch (e.g., file vs directory)"},
{"lineNum":"   72","line":"EOF"},
{"lineNum":"   73","line":"}"},
{"lineNum":"   74","line":""},
{"lineNum":"   75","line":"########################################"},
{"lineNum":"   76","line":"# Parses command-line arguments into global option flags."},
{"lineNum":"   77","line":"# Supports long options and combined short options (e.g., -tc)."},
{"lineNum":"   78","line":"# Globals:"},
{"lineNum":"   79","line":"#   _opt_timestamps, _opt_checksums, _opt_no_color, _opt_ignore_case,"},
{"lineNum":"   80","line":"#   _opt_no_dotfiles, _opt_excludes, _opt_excludes_left, _opt_excludes_right,"},
{"lineNum":"   81","line":"#   _dir1, _dir2"},
{"lineNum":"   82","line":"# Arguments:"},
{"lineNum":"   83","line":"#   Command-line arguments passed to the script."},
{"lineNum":"   84","line":"########################################"},
{"lineNum":"   85","line":"parse_options() {"},
{"lineNum":"   86","line":"  local positional=()","class":"lineCov","hits":"1","order":"5463",},
{"lineNum":"   87","line":""},
{"lineNum":"   88","line":"  while [[ $# -gt 0 ]]; do","class":"lineCov","hits":"1","order":"5428",},
{"lineNum":"   89","line":"    case \"$1\" in","class":"lineCov","hits":"1","order":"5408",},
{"lineNum":"   90","line":"      -t|--timestamps)"},
{"lineNum":"   91","line":"        _opt_timestamps=true","class":"lineCov","hits":"1","order":"5420",},
{"lineNum":"   92","line":"        shift","class":"lineCov","hits":"1","order":"5465",},
{"lineNum":"   93","line":"        ;;"},
{"lineNum":"   94","line":"      -c|--checksums)"},
{"lineNum":"   95","line":"        _opt_checksums=true","class":"lineCov","hits":"1","order":"5504",},
{"lineNum":"   96","line":"        shift","class":"lineCov","hits":"1","order":"5462",},
{"lineNum":"   97","line":"        ;;"},
{"lineNum":"   98","line":"      -i|--ignore-case)"},
{"lineNum":"   99","line":"        _opt_ignore_case=true","class":"lineCov","hits":"1","order":"5441",},
{"lineNum":"  100","line":"        shift","class":"lineCov","hits":"1","order":"5471",},
{"lineNum":"  101","line":"        ;;"},
{"lineNum":"  102","line":"      -d|--no-dotfiles)"},
{"lineNum":"  103","line":"        _opt_no_dotfiles=true","class":"lineCov","hits":"1","order":"5437",},
{"lineNum":"  104","line":"        shift","class":"lineCov","hits":"1","order":"5475",},
{"lineNum":"  105","line":"        ;;"},
{"lineNum":"  106","line":"      -x|--exclude)"},
{"lineNum":"  107","line":"        _opt_excludes+=(\"$2\")","class":"lineCov","hits":"1","order":"5401",},
{"lineNum":"  108","line":"        shift 2","class":"lineCov","hits":"1","order":"5400",},
{"lineNum":"  109","line":"        ;;"},
{"lineNum":"  110","line":"      --exclude-left)"},
{"lineNum":"  111","line":"        _opt_excludes_left+=(\"$2\")","class":"lineCov","hits":"1","order":"5399",},
{"lineNum":"  112","line":"        shift 2","class":"lineCov","hits":"1","order":"5398",},
{"lineNum":"  113","line":"        ;;"},
{"lineNum":"  114","line":"      --exclude-right)"},
{"lineNum":"  115","line":"        _opt_excludes_right+=(\"$2\")","class":"lineCov","hits":"1","order":"5397",},
{"lineNum":"  116","line":"        shift 2","class":"lineCov","hits":"1","order":"5396",},
{"lineNum":"  117","line":"        ;;"},
{"lineNum":"  118","line":"      -n|--no-color)"},
{"lineNum":"  119","line":"        _opt_no_color=true","class":"lineCov","hits":"1","order":"5395",},
{"lineNum":"  120","line":"        shift","class":"lineCov","hits":"1","order":"5392",},
{"lineNum":"  121","line":"        ;;"},
{"lineNum":"  122","line":"      -h|--help)"},
{"lineNum":"  123","line":"        show_usage","class":"lineCov","hits":"1","order":"5390",},
{"lineNum":"  124","line":"        exit 0","class":"lineCov","hits":"1","order":"5388",},
{"lineNum":"  125","line":"        ;;"},
{"lineNum":"  126","line":"      --)"},
{"lineNum":"  127","line":"        shift","class":"lineCov","hits":"1","order":"5387",},
{"lineNum":"  128","line":"        positional+=(\"$@\")","class":"lineCov","hits":"1","order":"5535",},
{"lineNum":"  129","line":"        break","class":"lineCov","hits":"1","order":"5517",},
{"lineNum":"  130","line":"        ;;"},
{"lineNum":"  131","line":"      --*)"},
{"lineNum":"  132","line":"        # Caught before the combined-flag arm below, which strips one dash and reads the rest as single"},
{"lineNum":"  133","line":"        # letters — for a long option that means reporting \"Unknown option: --\" and losing the name."},
{"lineNum":"  134","line":"        die_usage \"Unknown option \'$1\'.\"","class":"lineCov","hits":"1","order":"5432",},
{"lineNum":"  135","line":"        ;;"},
{"lineNum":"  136","line":"      -*)"},
{"lineNum":"  137","line":"        local combined=\"${1#-}\"","class":"lineCov","hits":"1","order":"5423",},
{"lineNum":"  138","line":"        shift","class":"lineCov","hits":"1","order":"5385",},
{"lineNum":"  139","line":"        for (( i=0; i<${#combined}; i++ )); do","class":"lineCov","hits":"1","order":"5382",},
{"lineNum":"  140","line":"          case \"${combined:$i:1}\" in","class":"lineCov","hits":"1","order":"5412",},
{"lineNum":"  141","line":"            t) _opt_timestamps=true ;;","class":"lineCov","hits":"1","order":"5380",},
{"lineNum":"  142","line":"            c) _opt_checksums=true ;;","class":"lineCov","hits":"1","order":"5378",},
{"lineNum":"  143","line":"            i) _opt_ignore_case=true ;;","class":"lineCov","hits":"1","order":"5436",},
{"lineNum":"  144","line":"            d) _opt_no_dotfiles=true ;;","class":"lineCov","hits":"1","order":"5376",},
{"lineNum":"  145","line":"            x)"},
{"lineNum":"  146","line":"              if (( i + 1 < ${#combined} )); then","class":"lineCov","hits":"1","order":"5374",},
{"lineNum":"  147","line":"                die_usage \"-x must be last in a combined flag group (requires an argument)\"","class":"lineCov","hits":"1","order":"5425",},
{"lineNum":"  148","line":"              fi"},
{"lineNum":"  149","line":"              _opt_excludes+=(\"$1\")","class":"lineCov","hits":"1","order":"5402",},
{"lineNum":"  150","line":"              shift","class":"lineCov","hits":"1","order":"5418",},
{"lineNum":"  151","line":"              ;;"},
{"lineNum":"  152","line":"            n) _opt_no_color=true ;;","class":"lineNoCov","hits":"0",},
{"lineNum":"  153","line":"            h) show_usage; exit 0 ;;","class":"lineNoCov","hits":"0",},
{"lineNum":"  154","line":"            *)"},
{"lineNum":"  155","line":"              die_usage \"Unknown option: -${combined:$i:1}\"","class":"lineCov","hits":"1","order":"5457",},
{"lineNum":"  156","line":"              ;;"},
{"lineNum":"  157","line":"          esac"},
{"lineNum":"  158","line":"        done"},
{"lineNum":"  159","line":"        ;;"},
{"lineNum":"  160","line":"      *)"},
{"lineNum":"  161","line":"        positional+=(\"$1\")","class":"lineCov","hits":"1","order":"5369",},
{"lineNum":"  162","line":"        shift","class":"lineCov","hits":"1","order":"5479",},
{"lineNum":"  163","line":"        ;;"},
{"lineNum":"  164","line":"    esac"},
{"lineNum":"  165","line":"  done"},
{"lineNum":"  166","line":""},
{"lineNum":"  167","line":"  if [[ ${#positional[@]} -ne 2 ]]; then","class":"lineCov","hits":"1","order":"5447",},
{"lineNum":"  168","line":"    log_error \"Expected exactly 2 directory arguments, got ${#positional[@]}.\"","class":"lineCov","hits":"1","order":"5469",},
{"lineNum":"  169","line":"    show_usage","class":"lineCov","hits":"1","order":"5481",},
{"lineNum":"  170","line":"    exit 1","class":"lineCov","hits":"1","order":"5483",},
{"lineNum":"  171","line":"  fi"},
{"lineNum":"  172","line":""},
{"lineNum":"  173","line":"  _dir1=\"${positional[0]}\"","class":"lineCov","hits":"1","order":"5485",},
{"lineNum":"  174","line":"  _dir2=\"${positional[1]}\"","class":"lineCov","hits":"1","order":"5487",},
{"lineNum":"  175","line":""},
{"lineNum":"  176","line":"  if [[ ! -d \"${_dir1}\" ]]; then","class":"lineCov","hits":"1","order":"5489",},
{"lineNum":"  177","line":"    log_error \"\'${_dir1}\' is not a directory.\"","class":"lineCov","hits":"1","order":"5490",},
{"lineNum":"  178","line":"    exit 1","class":"lineCov","hits":"1","order":"5415",},
{"lineNum":"  179","line":"  fi"},
{"lineNum":"  180","line":"  if [[ ! -d \"${_dir2}\" ]]; then","class":"lineCov","hits":"1","order":"5491",},
{"lineNum":"  181","line":"    log_error \"\'${_dir2}\' is not a directory.\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  182","line":"    exit 1","class":"lineNoCov","hits":"0",},
{"lineNum":"  183","line":"  fi"},
{"lineNum":"  184","line":""},
{"lineNum":"  185","line":"  # Resolve to absolute paths for display"},
{"lineNum":"  186","line":"  _dir1=\"$(cd \"${_dir1}\" && pwd)\"","class":"lineCov","hits":"1","order":"5492",},
{"lineNum":"  187","line":"  _dir2=\"$(cd \"${_dir2}\" && pwd)\"","class":"lineCov","hits":"1","order":"5493",},
{"lineNum":"  188","line":"}"},
{"lineNum":"  189","line":""},
{"lineNum":"  190","line":"########################################"},
{"lineNum":"  191","line":"# Formats an epoch timestamp as a human-readable date string."},
{"lineNum":"  192","line":"# Arguments:"},
{"lineNum":"  193","line":"#   ts: Unix epoch timestamp."},
{"lineNum":"  194","line":"# Outputs:"},
{"lineNum":"  195","line":"#   Prints formatted date to stdout."},
{"lineNum":"  196","line":"########################################"},
{"lineNum":"  197","line":"format_mtime() {"},
{"lineNum":"  198","line":"  local ts=\"$1\"","class":"lineCov","hits":"1","order":"5495",},
{"lineNum":"  199","line":"  if date -d \"@${ts}\" \'+%Y-%m-%d %H:%M:%S\' 2>/dev/null; then","class":"lineCov","hits":"1","order":"5496",},
{"lineNum":"  200","line":"    return","class":"lineCov","hits":"1","order":"5498",},
{"lineNum":"  201","line":"  fi"},
{"lineNum":"  202","line":"  # BSD date fallback"},
{"lineNum":"  203","line":"  date -r \"${ts}\" \'+%Y-%m-%d %H:%M:%S\'","class":"lineNoCov","hits":"0",},
{"lineNum":"  204","line":"}"},
{"lineNum":"  205","line":""},
{"lineNum":"  206","line":"########################################"},
{"lineNum":"  207","line":"# Formats a byte count with thousands separators."},
{"lineNum":"  208","line":"# Arguments:"},
{"lineNum":"  209","line":"#   size: File size in bytes."},
{"lineNum":"  210","line":"# Outputs:"},
{"lineNum":"  211","line":"#   Prints formatted size to stdout."},
{"lineNum":"  212","line":"########################################"},
{"lineNum":"  213","line":"format_size() {"},
{"lineNum":"  214","line":"  printf \"%\'d bytes\" \"$1\"","class":"lineCov","hits":"1","order":"5501",},
{"lineNum":"  215","line":"}"},
{"lineNum":"  216","line":""},
{"lineNum":"  217","line":"########################################"},
{"lineNum":"  218","line":"# Determines the filesystem type of a path."},
{"lineNum":"  219","line":"# Arguments:"},
{"lineNum":"  220","line":"#   path: Filesystem path to inspect."},
{"lineNum":"  221","line":"# Outputs:"},
{"lineNum":"  222","line":"#   Prints one of: symlink, directory, file, other."},
{"lineNum":"  223","line":"########################################"},
{"lineNum":"  224","line":"get_type() {"},
{"lineNum":"  225","line":"  local path=\"$1\"","class":"lineCov","hits":"1","order":"5503",},
{"lineNum":"  226","line":"  if [[ -L \"${path}\" ]]; then","class":"lineCov","hits":"1","order":"5443",},
{"lineNum":"  227","line":"    echo \"symlink\"","class":"lineCov","hits":"1","order":"5472",},
{"lineNum":"  228","line":"  elif [[ -d \"${path}\" ]]; then","class":"lineCov","hits":"1","order":"5507",},
{"lineNum":"  229","line":"    echo \"directory\"","class":"lineCov","hits":"1","order":"5510",},
{"lineNum":"  230","line":"  elif [[ -f \"${path}\" ]]; then","class":"lineCov","hits":"1","order":"5439",},
{"lineNum":"  231","line":"    echo \"file\"","class":"lineCov","hits":"1","order":"5477",},
{"lineNum":"  232","line":"  else"},
{"lineNum":"  233","line":"    echo \"other\"","class":"lineCov","hits":"1","order":"5512",},
{"lineNum":"  234","line":"  fi"},
{"lineNum":"  235","line":"}"},
{"lineNum":"  236","line":""},
{"lineNum":"  237","line":"# --- Output Helpers ---"},
{"lineNum":"  238","line":""},
{"lineNum":"  239","line":"########################################"},
{"lineNum":"  240","line":"# Reports an item found only in the left directory."},
{"lineNum":"  241","line":"# Globals:"},
{"lineNum":"  242","line":"#   _C_RED, _C_BOLD, _C_RESET, _count_left_only"},
{"lineNum":"  243","line":"# Arguments:"},
{"lineNum":"  244","line":"#   Relative path of the item."},
{"lineNum":"  245","line":"########################################"},
{"lineNum":"  246","line":"print_left_only() {"},
{"lineNum":"  247","line":"  echo \"${_C_RED}← LEFT only:  ${_C_BOLD}${1}${_C_RESET}\"","class":"lineCov","hits":"1","order":"5394",},
{"lineNum":"  248","line":"  (( _count_left_only++ )) || true","class":"lineCov","hits":"1","order":"5514",},
{"lineNum":"  249","line":"}"},
{"lineNum":"  250","line":""},
{"lineNum":"  251","line":"########################################"},
{"lineNum":"  252","line":"# Reports an item found only in the right directory."},
{"lineNum":"  253","line":"# Globals:"},
{"lineNum":"  254","line":"#   _C_GREEN, _C_BOLD, _C_RESET, _count_right_only"},
{"lineNum":"  255","line":"# Arguments:"},
{"lineNum":"  256","line":"#   Relative path of the item."},
{"lineNum":"  257","line":"########################################"},
{"lineNum":"  258","line":"print_right_only() {"},
{"lineNum":"  259","line":"  echo \"${_C_GREEN}→ RIGHT only: ${_C_BOLD}${1}${_C_RESET}\"","class":"lineCov","hits":"1","order":"5516",},
{"lineNum":"  260","line":"  (( _count_right_only++ )) || true","class":"lineCov","hits":"1","order":"5520",},
{"lineNum":"  261","line":"}"},
{"lineNum":"  262","line":""},
{"lineNum":"  263","line":"########################################"},
{"lineNum":"  264","line":"# Reports a file size difference between left and right."},
{"lineNum":"  265","line":"# Globals:"},
{"lineNum":"  266","line":"#   _C_YELLOW, _C_BOLD, _C_RESET, _count_differences"},
{"lineNum":"  267","line":"# Arguments:"},
{"lineNum":"  268","line":"#   path: Relative path of the file."},
{"lineNum":"  269","line":"#   size1: Size in left directory (bytes)."},
{"lineNum":"  270","line":"#   size2: Size in right directory (bytes)."},
{"lineNum":"  271","line":"########################################"},
{"lineNum":"  272","line":"print_size_diff() {"},
{"lineNum":"  273","line":"  local path=\"$1\" size1=\"$2\" size2=\"$3\"","class":"lineCov","hits":"1","order":"5433",},
{"lineNum":"  274","line":"  echo \"${_C_YELLOW}≠ Size differs: ${_C_BOLD}${path}${_C_RESET}\"","class":"lineCov","hits":"1","order":"5427",},
{"lineNum":"  275","line":"  echo \"    LEFT:  $(format_size \"${size1}\")\"","class":"lineCov","hits":"1","order":"5521",},
{"lineNum":"  276","line":"  echo \"    RIGHT: $(format_size \"${size2}\")\"","class":"lineCov","hits":"1","order":"5405",},
{"lineNum":"  277","line":"  (( _count_differences++ )) || true","class":"lineCov","hits":"1","order":"5419",},
{"lineNum":"  278","line":"}"},
{"lineNum":"  279","line":""},
{"lineNum":"  280","line":"########################################"},
{"lineNum":"  281","line":"# Reports a modification time difference between left and right."},
{"lineNum":"  282","line":"# Globals:"},
{"lineNum":"  283","line":"#   _C_YELLOW, _C_BOLD, _C_RESET, _count_differences"},
{"lineNum":"  284","line":"# Arguments:"},
{"lineNum":"  285","line":"#   path: Relative path of the file."},
{"lineNum":"  286","line":"#   mtime1: Epoch timestamp in left directory."},
{"lineNum":"  287","line":"#   mtime2: Epoch timestamp in right directory."},
{"lineNum":"  288","line":"########################################"},
{"lineNum":"  289","line":"print_mtime_diff() {"},
{"lineNum":"  290","line":"  local path=\"$1\" mtime1=\"$2\" mtime2=\"$3\"","class":"lineCov","hits":"1","order":"5523",},
{"lineNum":"  291","line":"  echo \"${_C_YELLOW}≠ Mtime differs: ${_C_BOLD}${path}${_C_RESET}\"","class":"lineCov","hits":"1","order":"5460",},
{"lineNum":"  292","line":"  echo \"    LEFT:  $(format_mtime \"${mtime1}\")\"","class":"lineCov","hits":"1","order":"5455",},
{"lineNum":"  293","line":"  echo \"    RIGHT: $(format_mtime \"${mtime2}\")\"","class":"lineCov","hits":"1","order":"5451",},
{"lineNum":"  294","line":"  (( _count_differences++ )) || true","class":"lineCov","hits":"1","order":"5458",},
{"lineNum":"  295","line":"}"},
{"lineNum":"  296","line":""},
{"lineNum":"  297","line":"########################################"},
{"lineNum":"  298","line":"# Reports a checksum difference between left and right."},
{"lineNum":"  299","line":"# Globals:"},
{"lineNum":"  300","line":"#   _C_YELLOW, _C_BOLD, _C_RESET, _count_differences"},
{"lineNum":"  301","line":"# Arguments:"},
{"lineNum":"  302","line":"#   Relative path of the file."},
{"lineNum":"  303","line":"########################################"},
{"lineNum":"  304","line":"print_checksum_diff() {"},
{"lineNum":"  305","line":"  echo \"${_C_YELLOW}≠ Checksum differs: ${_C_BOLD}${1}${_C_RESET}\"","class":"lineCov","hits":"1","order":"5416",},
{"lineNum":"  306","line":"  (( _count_differences++ )) || true","class":"lineCov","hits":"1","order":"5524",},
{"lineNum":"  307","line":"}"},
{"lineNum":"  308","line":""},
{"lineNum":"  309","line":"########################################"},
{"lineNum":"  310","line":"# Reports a type mismatch (e.g., file vs directory)."},
{"lineNum":"  311","line":"# Globals:"},
{"lineNum":"  312","line":"#   _C_YELLOW, _C_BOLD, _C_RESET, _count_differences"},
{"lineNum":"  313","line":"# Arguments:"},
{"lineNum":"  314","line":"#   path: Relative path of the item."},
{"lineNum":"  315","line":"#   type1: Type in left directory."},
{"lineNum":"  316","line":"#   type2: Type in right directory."},
{"lineNum":"  317","line":"########################################"},
{"lineNum":"  318","line":"print_type_mismatch() {"},
{"lineNum":"  319","line":"  local path=\"$1\" type1=\"$2\" type2=\"$3\"","class":"lineCov","hits":"1","order":"5525",},
{"lineNum":"  320","line":"  echo \"${_C_YELLOW}⚡ Type mismatch: ${_C_BOLD}${path}${_C_RESET}\"","class":"lineCov","hits":"1","order":"5526",},
{"lineNum":"  321","line":"  echo \"    LEFT:  ${type1}\"","class":"lineCov","hits":"1","order":"5527",},
{"lineNum":"  322","line":"  echo \"    RIGHT: ${type2}\"","class":"lineCov","hits":"1","order":"5528",},
{"lineNum":"  323","line":"  (( _count_differences++ )) || true","class":"lineCov","hits":"1","order":"5529",},
{"lineNum":"  324","line":"}"},
{"lineNum":"  325","line":""},
{"lineNum":"  326","line":"########################################"},
{"lineNum":"  327","line":"# Reports a symlink target difference between left and right."},
{"lineNum":"  328","line":"# Globals:"},
{"lineNum":"  329","line":"#   _C_YELLOW, _C_BOLD, _C_RESET, _count_differences"},
{"lineNum":"  330","line":"# Arguments:"},
{"lineNum":"  331","line":"#   path: Relative path of the symlink."},
{"lineNum":"  332","line":"#   target1: Link target in left directory."},
{"lineNum":"  333","line":"#   target2: Link target in right directory."},
{"lineNum":"  334","line":"########################################"},
{"lineNum":"  335","line":"print_symlink_diff() {"},
{"lineNum":"  336","line":"  local path=\"$1\" target1=\"$2\" target2=\"$3\"","class":"lineCov","hits":"1","order":"5530",},
{"lineNum":"  337","line":"  echo \"${_C_YELLOW}≠ Symlink target differs: ${_C_BOLD}${path}${_C_RESET}\"","class":"lineCov","hits":"1","order":"5531",},
{"lineNum":"  338","line":"  echo \"    LEFT:  -> ${target1}\"","class":"lineCov","hits":"1","order":"5532",},
{"lineNum":"  339","line":"  echo \"    RIGHT: -> ${target2}\"","class":"lineCov","hits":"1","order":"5533",},
{"lineNum":"  340","line":"  (( _count_differences++ )) || true","class":"lineCov","hits":"1","order":"5464",},
{"lineNum":"  341","line":"}"},
{"lineNum":"  342","line":""},
{"lineNum":"  343","line":"########################################"},
{"lineNum":"  344","line":"# Tests whether a filename matches any of the given glob patterns."},
{"lineNum":"  345","line":"# Arguments:"},
{"lineNum":"  346","line":"#   name: The filename to test."},
{"lineNum":"  347","line":"#   ...: One or more glob patterns."},
{"lineNum":"  348","line":"# Returns:"},
{"lineNum":"  349","line":"#   0 if any pattern matches, 1 otherwise."},
{"lineNum":"  350","line":"########################################"},
{"lineNum":"  351","line":"matches_pattern() {"},
{"lineNum":"  352","line":"  local name=\"$1\"","class":"lineCov","hits":"1","order":"5505",},
{"lineNum":"  353","line":"  shift","class":"lineCov","hits":"1","order":"5461",},
{"lineNum":"  354","line":"  local pattern","class":"lineCov","hits":"1","order":"5473",},
{"lineNum":"  355","line":"  for pattern in \"$@\"; do","class":"lineCov","hits":"1","order":"5508",},
{"lineNum":"  356","line":"    # shellcheck disable=SC2254,SC2053"},
{"lineNum":"  357","line":"    if [[ \"${name}\" == ${pattern} ]]; then","class":"lineCov","hits":"1","order":"5470",},
{"lineNum":"  358","line":"      return 0","class":"lineCov","hits":"1","order":"5478",},
{"lineNum":"  359","line":"    fi"},
{"lineNum":"  360","line":"  done"},
{"lineNum":"  361","line":"  return 1","class":"lineCov","hits":"1","order":"5474",},
{"lineNum":"  362","line":"}"},
{"lineNum":"  363","line":""},
{"lineNum":"  364","line":"########################################"},
{"lineNum":"  365","line":"# Recursively compares two directory trees, printing differences."},
{"lineNum":"  366","line":"# Uses null-delimited I/O internally to handle arbitrary filenames."},
{"lineNum":"  367","line":"# Globals:"},
{"lineNum":"  368","line":"#   _opt_timestamps, _opt_checksums, _opt_ignore_case, _opt_no_dotfiles,"},
{"lineNum":"  369","line":"#   _opt_excludes, _opt_excludes_left, _opt_excludes_right,"},
{"lineNum":"  370","line":"#   _count_left_only, _count_right_only, _count_differences"},
{"lineNum":"  371","line":"# Arguments:"},
{"lineNum":"  372","line":"#   prefix: Relative path prefix for display (empty string for top level)."},
{"lineNum":"  373","line":"#   left:   Absolute path to the left directory being compared."},
{"lineNum":"  374","line":"#   right:  Absolute path to the right directory being compared."},
{"lineNum":"  375","line":"########################################"},
{"lineNum":"  376","line":"compare_dirs() {"},
{"lineNum":"  377","line":"  local prefix=\"$1\"","class":"lineCov","hits":"1","order":"5391",},
{"lineNum":"  378","line":"  local left=\"$2\"","class":"lineCov","hits":"1","order":"5389",},
{"lineNum":"  379","line":"  local right=\"$3\"","class":"lineCov","hits":"1","order":"5534",},
{"lineNum":"  380","line":""},
{"lineNum":"  381","line":"  # Build sorted lists of entries (null-delimited for filename safety)"},
{"lineNum":"  382","line":"  local -a left_sorted=()","class":"lineCov","hits":"1","order":"5448",},
{"lineNum":"  383","line":"  local -a right_sorted=()","class":"lineCov","hits":"1","order":"5440",},
{"lineNum":"  384","line":""},
{"lineNum":"  385","line":"  if [[ -d \"${left}\" ]]; then","class":"lineCov","hits":"1","order":"5536",},
{"lineNum":"  386","line":"    while IFS= read -r -d \'\' entry; do","class":"lineCov","hits":"1","order":"5518",},
{"lineNum":"  387","line":"      local base","class":"lineCov","hits":"1","order":"5368",},
{"lineNum":"  388","line":"      base=\"$(basename \"${entry}\")\"","class":"lineCov","hits":"1","order":"5367",},
{"lineNum":"  389","line":"      [[ \"${_opt_no_dotfiles}\" == true && \"${base}\" == .* ]] && continue","class":"lineCov","hits":"1","order":"5366",},
{"lineNum":"  390","line":"      [[ ${#_opt_excludes[@]} -gt 0 ]] && matches_pattern \"${base}\" \"${_opt_excludes[@]}\" && continue","class":"lineCov","hits":"1","order":"5365",},
{"lineNum":"  391","line":"      left_sorted+=(\"${base}\")","class":"lineCov","hits":"1","order":"5431",},
{"lineNum":"  392","line":"    done < <(find \"${left}\" -maxdepth 1 -mindepth 1 -print0 | sort -z)","class":"lineNoCov","hits":"0",},
{"lineNum":"  393","line":"  fi"},
{"lineNum":"  394","line":""},
{"lineNum":"  395","line":"  if [[ -d \"${right}\" ]]; then","class":"lineCov","hits":"1","order":"5384",},
{"lineNum":"  396","line":"    while IFS= read -r -d \'\' entry; do","class":"lineCov","hits":"1","order":"5381",},
{"lineNum":"  397","line":"      local base","class":"lineCov","hits":"1","order":"5411",},
{"lineNum":"  398","line":"      base=\"$(basename \"${entry}\")\"","class":"lineCov","hits":"1","order":"5379",},
{"lineNum":"  399","line":"      [[ \"${_opt_no_dotfiles}\" == true && \"${base}\" == .* ]] && continue","class":"lineCov","hits":"1","order":"5377",},
{"lineNum":"  400","line":"      [[ ${#_opt_excludes[@]} -gt 0 ]] && matches_pattern \"${base}\" \"${_opt_excludes[@]}\" && continue","class":"lineCov","hits":"1","order":"5435",},
{"lineNum":"  401","line":"      right_sorted+=(\"${base}\")","class":"lineCov","hits":"1","order":"5375",},
{"lineNum":"  402","line":"    done < <(find \"${right}\" -maxdepth 1 -mindepth 1 -print0 | sort -z)","class":"lineNoCov","hits":"0",},
{"lineNum":"  403","line":"  fi"},
{"lineNum":"  404","line":""},
{"lineNum":"  405","line":"  # Use associative arrays for O(1) set membership tests."},
{"lineNum":"  406","line":"  # Values store the original filename for path construction."},
{"lineNum":"  407","line":"  local -A left_set=()","class":"lineCov","hits":"1","order":"5417",},
{"lineNum":"  408","line":"  local -A right_set=()","class":"lineCov","hits":"1","order":"5364",},
{"lineNum":"  409","line":"  for e in \"${left_sorted[@]+\"${left_sorted[@]}\"}\"; do","class":"lineCov","hits":"1","order":"5371",},
{"lineNum":"  410","line":"    local norm=\"${e}\"","class":"lineCov","hits":"1","order":"5370",},
{"lineNum":"  411","line":"    [[ \"${_opt_ignore_case}\" == true ]] && norm=\"${e,,}\"","class":"lineCov","hits":"1","order":"5363",},
{"lineNum":"  412","line":"    left_set[\"${norm}\"]=\"${e}\"","class":"lineCov","hits":"1","order":"5456",},
{"lineNum":"  413","line":"  done"},
{"lineNum":"  414","line":"  for e in \"${right_sorted[@]+\"${right_sorted[@]}\"}\"; do","class":"lineCov","hits":"1","order":"5362",},
{"lineNum":"  415","line":"    local norm=\"${e}\"","class":"lineCov","hits":"1","order":"5361",},
{"lineNum":"  416","line":"    [[ \"${_opt_ignore_case}\" == true ]] && norm=\"${e,,}\"","class":"lineCov","hits":"1","order":"5360",},
{"lineNum":"  417","line":"    right_set[\"${norm}\"]=\"${e}\"","class":"lineCov","hits":"1","order":"5359",},
{"lineNum":"  418","line":"  done"},
{"lineNum":"  419","line":""},
{"lineNum":"  420","line":"  # Compute merged sorted unique list of normalized keys. Both sides accumulate into one array, which"},
{"lineNum":"  421","line":"  # the enclosing condition guarantees is non-empty, so its expansion needs no guarding."},
{"lineNum":"  422","line":"  local -a all_entries=()","class":"lineCov","hits":"1","order":"5358",},
{"lineNum":"  423","line":"  if [[ ${#left_sorted[@]} -gt 0 || ${#right_sorted[@]} -gt 0 ]]; then","class":"lineCov","hits":"1","order":"5357",},
{"lineNum":"  424","line":"    local -a norm_entries=()","class":"lineCov","hits":"1","order":"5446",},
{"lineNum":"  425","line":"    for e in \"${left_sorted[@]+\"${left_sorted[@]}\"}\"; do","class":"lineCov","hits":"1","order":"5468",},
{"lineNum":"  426","line":"      local n=\"${e}\"","class":"lineCov","hits":"1","order":"5480",},
{"lineNum":"  427","line":"      [[ \"${_opt_ignore_case}\" == true ]] && n=\"${e,,}\"","class":"lineCov","hits":"1","order":"5482",},
{"lineNum":"  428","line":"      norm_entries+=(\"${n}\")","class":"lineCov","hits":"1","order":"5356",},
{"lineNum":"  429","line":"    done"},
{"lineNum":"  430","line":"    for e in \"${right_sorted[@]+\"${right_sorted[@]}\"}\"; do","class":"lineCov","hits":"1","order":"5484",},
{"lineNum":"  431","line":"      local n=\"${e}\"","class":"lineCov","hits":"1","order":"5486",},
{"lineNum":"  432","line":"      [[ \"${_opt_ignore_case}\" == true ]] && n=\"${e,,}\"","class":"lineCov","hits":"1","order":"5355",},
{"lineNum":"  433","line":"      norm_entries+=(\"${n}\")","class":"lineCov","hits":"1","order":"5488",},
{"lineNum":"  434","line":"    done"},
{"lineNum":"  435","line":"    while IFS= read -r -d \'\' entry; do","class":"lineCov","hits":"1","order":"5414",},
{"lineNum":"  436","line":"      all_entries+=(\"${entry}\")","class":"lineCov","hits":"1","order":"5354",},
{"lineNum":"  437","line":"    done < <(printf \'%s\\0\' \"${norm_entries[@]}\" | sort -uz)","class":"lineNoCov","hits":"0",},
{"lineNum":"  438","line":"  fi"},
{"lineNum":"  439","line":""},
{"lineNum":"  440","line":"  for norm_entry in \"${all_entries[@]+\"${all_entries[@]}\"}\"; do","class":"lineCov","hits":"1","order":"5353",},
{"lineNum":"  441","line":"    local orig_left=\"${left_set[${norm_entry}]:-}\"","class":"lineCov","hits":"1","order":"5352",},
{"lineNum":"  442","line":"    local orig_right=\"${right_set[${norm_entry}]:-}\"","class":"lineCov","hits":"1","order":"5351",},
{"lineNum":"  443","line":""},
{"lineNum":"  444","line":"    # Use the left original name for display if available, otherwise right"},
{"lineNum":"  445","line":"    local display_name=\"${orig_left:-${orig_right}}\"","class":"lineCov","hits":"1","order":"5350",},
{"lineNum":"  446","line":"    local rel_path","class":"lineCov","hits":"1","order":"5349",},
{"lineNum":"  447","line":"    if [[ -n \"${prefix}\" ]]; then","class":"lineCov","hits":"1","order":"5348",},
{"lineNum":"  448","line":"      rel_path=\"${prefix}${display_name}\"","class":"lineCov","hits":"1","order":"5347",},
{"lineNum":"  449","line":"    else"},
{"lineNum":"  450","line":"      rel_path=\"${display_name}\"","class":"lineCov","hits":"1","order":"5346",},
{"lineNum":"  451","line":"    fi"},
{"lineNum":"  452","line":""},
{"lineNum":"  453","line":"    if [[ -n \"${orig_left}\" && -z \"${orig_right}\" ]]; then","class":"lineCov","hits":"1","order":"5345",},
{"lineNum":"  454","line":"      if [[ ${#_opt_excludes_left[@]} -gt 0 ]] && matches_pattern \"${display_name}\" \"${_opt_excludes_left[@]}\"; then","class":"lineCov","hits":"1","order":"5344",},
{"lineNum":"  455","line":"        continue","class":"lineCov","hits":"1","order":"5494",},
{"lineNum":"  456","line":"      fi"},
{"lineNum":"  457","line":"      local type_l","class":"lineCov","hits":"1","order":"5497",},
{"lineNum":"  458","line":"      type_l=\"$(get_type \"${left}/${orig_left}\")\"","class":"lineCov","hits":"1","order":"5343",},
{"lineNum":"  459","line":"      if [[ \"${type_l}\" == \"directory\" ]]; then","class":"lineCov","hits":"1","order":"5342",},
{"lineNum":"  460","line":"        print_left_only \"${rel_path}/\"","class":"lineCov","hits":"1","order":"5499",},
{"lineNum":"  461","line":"      else"},
{"lineNum":"  462","line":"        print_left_only \"${rel_path}\"","class":"lineCov","hits":"1","order":"5341",},
{"lineNum":"  463","line":"      fi"},
{"lineNum":"  464","line":""},
{"lineNum":"  465","line":"    elif [[ -z \"${orig_left}\" && -n \"${orig_right}\" ]]; then","class":"lineCov","hits":"1","order":"5340",},
{"lineNum":"  466","line":"      if [[ ${#_opt_excludes_right[@]} -gt 0 ]] && matches_pattern \"${display_name}\" \"${_opt_excludes_right[@]}\"; then","class":"lineCov","hits":"1","order":"5339",},
{"lineNum":"  467","line":"        continue","class":"lineCov","hits":"1","order":"5338",},
{"lineNum":"  468","line":"      fi"},
{"lineNum":"  469","line":"      local type_r","class":"lineCov","hits":"1","order":"5337",},
{"lineNum":"  470","line":"      type_r=\"$(get_type \"${right}/${orig_right}\")\"","class":"lineCov","hits":"1","order":"5336",},
{"lineNum":"  471","line":"      if [[ \"${type_r}\" == \"directory\" ]]; then","class":"lineCov","hits":"1","order":"5500",},
{"lineNum":"  472","line":"        print_right_only \"${rel_path}/\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  473","line":"      else"},
{"lineNum":"  474","line":"        print_right_only \"${rel_path}\"","class":"lineCov","hits":"1","order":"5335",},
{"lineNum":"  475","line":"      fi"},
{"lineNum":"  476","line":""},
{"lineNum":"  477","line":"    else"},
{"lineNum":"  478","line":"      # Present in both — compare"},
{"lineNum":"  479","line":"      local left_path=\"${left}/${orig_left}\"","class":"lineCov","hits":"1","order":"5334",},
{"lineNum":"  480","line":"      local right_path=\"${right}/${orig_right}\"","class":"lineCov","hits":"1","order":"5333",},
{"lineNum":"  481","line":"      local type_l type_r","class":"lineCov","hits":"1","order":"5332",},
{"lineNum":"  482","line":"      type_l=\"$(get_type \"${left_path}\")\"","class":"lineCov","hits":"1","order":"5502",},
{"lineNum":"  483","line":"      type_r=\"$(get_type \"${right_path}\")\"","class":"lineCov","hits":"1","order":"5442",},
{"lineNum":"  484","line":""},
{"lineNum":"  485","line":"      if [[ \"${type_l}\" != \"${type_r}\" ]]; then","class":"lineCov","hits":"1","order":"5506",},
{"lineNum":"  486","line":"        print_type_mismatch \"${rel_path}\" \"${type_l}\" \"${type_r}\"","class":"lineCov","hits":"1","order":"5509",},
{"lineNum":"  487","line":"      elif [[ \"${type_l}\" == \"directory\" ]]; then","class":"lineCov","hits":"1","order":"5438",},
{"lineNum":"  488","line":"        compare_dirs \"${rel_path}/\" \"${left_path}\" \"${right_path}\"","class":"lineCov","hits":"1","order":"5476",},
{"lineNum":"  489","line":"      elif [[ \"${type_l}\" == \"symlink\" ]]; then","class":"lineCov","hits":"1","order":"5331",},
{"lineNum":"  490","line":"        local target_l target_r","class":"lineCov","hits":"1","order":"5511",},
{"lineNum":"  491","line":"        target_l=\"$(readlink \"${left_path}\")\"","class":"lineCov","hits":"1","order":"5330",},
{"lineNum":"  492","line":"        target_r=\"$(readlink \"${right_path}\")\"","class":"lineCov","hits":"1","order":"5329",},
{"lineNum":"  493","line":"        if [[ \"${target_l}\" != \"${target_r}\" ]]; then","class":"lineCov","hits":"1","order":"5328",},
{"lineNum":"  494","line":"          print_symlink_diff \"${rel_path}\" \"${target_l}\" \"${target_r}\"","class":"lineCov","hits":"1","order":"5327",},
{"lineNum":"  495","line":"        fi"},
{"lineNum":"  496","line":"      elif [[ \"${type_l}\" == \"file\" ]]; then","class":"lineCov","hits":"1","order":"5326",},
{"lineNum":"  497","line":"        local size_l size_r","class":"lineCov","hits":"1","order":"5325",},
{"lineNum":"  498","line":"        size_l=\"$(stat_size \"${left_path}\")\"","class":"lineCov","hits":"1","order":"5324",},
{"lineNum":"  499","line":"        size_r=\"$(stat_size \"${right_path}\")\"","class":"lineCov","hits":"1","order":"5323",},
{"lineNum":"  500","line":""},
{"lineNum":"  501","line":"        if [[ \"${size_l}\" != \"${size_r}\" ]]; then","class":"lineCov","hits":"1","order":"5322",},
{"lineNum":"  502","line":"          print_size_diff \"${rel_path}\" \"${size_l}\" \"${size_r}\"","class":"lineCov","hits":"1","order":"5321",},
{"lineNum":"  503","line":"        elif [[ \"${_opt_checksums}\" == true ]]; then","class":"lineCov","hits":"1","order":"5320",},
{"lineNum":"  504","line":"          local cksum_l cksum_r","class":"lineCov","hits":"1","order":"5393",},
{"lineNum":"  505","line":"          cksum_l=\"$(file_checksum \"${left_path}\")\"","class":"lineCov","hits":"1","order":"5513",},
{"lineNum":"  506","line":"          cksum_r=\"$(file_checksum \"${right_path}\")\"","class":"lineCov","hits":"1","order":"5319",},
{"lineNum":"  507","line":"          if [[ \"${cksum_l}\" != \"${cksum_r}\" ]]; then","class":"lineCov","hits":"1","order":"5318",},
{"lineNum":"  508","line":"            print_checksum_diff \"${rel_path}\"","class":"lineCov","hits":"1","order":"5317",},
{"lineNum":"  509","line":"          fi"},
{"lineNum":"  510","line":"        fi"},
{"lineNum":"  511","line":""},
{"lineNum":"  512","line":"        if [[ \"${_opt_timestamps}\" == true ]]; then","class":"lineCov","hits":"1","order":"5316",},
{"lineNum":"  513","line":"          local mtime_l mtime_r","class":"lineCov","hits":"1","order":"5315",},
{"lineNum":"  514","line":"          mtime_l=\"$(stat_mtime \"${left_path}\")\"","class":"lineCov","hits":"1","order":"5314",},
{"lineNum":"  515","line":"          mtime_r=\"$(stat_mtime \"${right_path}\")\"","class":"lineCov","hits":"1","order":"5313",},
{"lineNum":"  516","line":"          if [[ \"${mtime_l}\" != \"${mtime_r}\" ]]; then","class":"lineCov","hits":"1","order":"5515",},
{"lineNum":"  517","line":"            print_mtime_diff \"${rel_path}\" \"${mtime_l}\" \"${mtime_r}\"","class":"lineCov","hits":"1","order":"5519",},
{"lineNum":"  518","line":"          fi"},
{"lineNum":"  519","line":"        fi"},
{"lineNum":"  520","line":"      fi"},
{"lineNum":"  521","line":"    fi"},
{"lineNum":"  522","line":"  done"},
{"lineNum":"  523","line":"}"},
{"lineNum":"  524","line":""},
{"lineNum":"  525","line":"########################################"},
{"lineNum":"  526","line":"# Main entry point."},
{"lineNum":"  527","line":"# Arguments:"},
{"lineNum":"  528","line":"#   Command-line arguments."},
{"lineNum":"  529","line":"########################################"},
{"lineNum":"  530","line":"main() {"},
{"lineNum":"  531","line":"  parse_options \"$@\"","class":"lineCov","hits":"1","order":"5426",},
{"lineNum":"  532","line":""},
{"lineNum":"  533","line":"  # Checked once, up front: without a checksum tool every comparison would fail one file at a time,"},
{"lineNum":"  534","line":"  # and the option promises something the machine cannot deliver."},
{"lineNum":"  535","line":"  if [[ \"${_opt_checksums}\" == true ]] && ! has_checksum_tool; then","class":"lineCov","hits":"1","order":"5312",},
{"lineNum":"  536","line":"    log_error \"No checksum tool found (sha256sum or shasum). Checksum comparison disabled.\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  537","line":"    _opt_checksums=false","class":"lineNoCov","hits":"0",},
{"lineNum":"  538","line":"  fi"},
{"lineNum":"  539","line":"  setup_colors \"${_opt_no_color}\"","class":"lineCov","hits":"1","order":"5372",},
{"lineNum":"  540","line":""},
{"lineNum":"  541","line":"  # Print header"},
{"lineNum":"  542","line":"  echo \"${_C_CYAN}Comparing:${_C_RESET}\"","class":"lineCov","hits":"1","order":"5311",},
{"lineNum":"  543","line":"  echo \"  LEFT:  ${_C_BOLD}${_dir1}${_C_RESET}\"","class":"lineCov","hits":"1","order":"5429",},
{"lineNum":"  544","line":"  echo \"  RIGHT: ${_C_BOLD}${_dir2}${_C_RESET}\"","class":"lineCov","hits":"1","order":"5409",},
{"lineNum":"  545","line":"  echo \"─────────────────────────────────\"","class":"lineCov","hits":"1","order":"5406",},
{"lineNum":"  546","line":"  echo \"\"","class":"lineCov","hits":"1","order":"5421",},
{"lineNum":"  547","line":""},
{"lineNum":"  548","line":"  # Run comparison"},
{"lineNum":"  549","line":"  compare_dirs \"\" \"${_dir1}\" \"${_dir2}\"","class":"lineCov","hits":"1","order":"5454",},
{"lineNum":"  550","line":""},
{"lineNum":"  551","line":"  # Print footer"},
{"lineNum":"  552","line":"  echo \"\"","class":"lineCov","hits":"1","order":"5452",},
{"lineNum":"  553","line":"  echo \"─────────────────────────────────\"","class":"lineCov","hits":"1","order":"5449",},
{"lineNum":"  554","line":"  local total=$(( _count_left_only + _count_right_only + _count_differences ))","class":"lineCov","hits":"1","order":"5444",},
{"lineNum":"  555","line":"  if [[ ${total} -eq 0 ]]; then","class":"lineCov","hits":"1","order":"5466",},
{"lineNum":"  556","line":"    echo \"${_C_GREEN}Directories are identical.${_C_RESET}\"","class":"lineCov","hits":"1","order":"5310",},
{"lineNum":"  557","line":"    exit 0","class":"lineCov","hits":"1","order":"5309",},
{"lineNum":"  558","line":"  else"},
{"lineNum":"  559","line":"    echo \"${_C_CYAN}Summary:${_C_RESET} ${_count_left_only} only in LEFT, ${_count_right_only} only in RIGHT, ${_count_differences} differences\"","class":"lineCov","hits":"1","order":"5308",},
{"lineNum":"  560","line":"    exit 1","class":"lineCov","hits":"1","order":"5307",},
{"lineNum":"  561","line":"  fi"},
{"lineNum":"  562","line":"}"},
{"lineNum":"  563","line":""},
{"lineNum":"  564","line":"# Only run when executed, not when sourced — the test suite sources this file to exercise its"},
{"lineNum":"  565","line":"# individual functions."},
{"lineNum":"  566","line":"if [[ \"${BASH_SOURCE[0]}\" == \"${0}\" ]]; then","class":"lineCov","hits":"1","order":"5306",},
{"lineNum":"  567","line":"  main \"$@\"","class":"lineCov","hits":"1","order":"5305",},
{"lineNum":"  568","line":"fi"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "update-all-indexes.sh", "date" : "2026-10-06 08:35:09", "instrumented" : 243, "covered" : 232,};
var merged_data = [];
