var data = {lines:[
{"lineNum":"    1","line":"#!/usr/bin/env bash"},
{"lineNum":"    2","line":"#"},
{"lineNum":"    3","line":"# memory-pressure-alert.sh — warn while a Mac is filling up, not once it has"},
{"lineNum":"    4","line":"# already ground to a halt."},
{"lineNum":"    5","line":"#"},
{"lineNum":"    6","line":"# macOS does not run out of memory so much as it slides: pages compress, then"},
{"lineNum":"    7","line":"# swap grows, and the machine stays usable for days. Then free swap reaches zero"},
{"lineNum":"    8","line":"# and everything stalls at once — a load average in the hundreds, every process"},
{"lineNum":"    9","line":"# blocked on memory, and no single culprit visible in Activity Monitor."},
{"lineNum":"   10","line":"#"},
{"lineNum":"   11","line":"# Free memory is useless as a signal here, because macOS keeps almost none: it"},
{"lineNum":"   12","line":"# lends the rest to the file cache and reclaims it on demand, so \"free\" sits near"},
{"lineNum":"   13","line":"# zero on a perfectly healthy machine. The numbers that move are:"},
{"lineNum":"   14","line":"#"},
{"lineNum":"   15","line":"#   * swap in use — the leading indicator. It accrues over days of uptime and is"},
{"lineNum":"   16","line":"#     the only one that is near zero on a healthy machine, so a modest threshold"},
{"lineNum":"   17","line":"#     gives days of notice."},
{"lineNum":"   18","line":"#   * memory used — counted the way Activity Monitor and Stats count it, as"},
{"lineNum":"   19","line":"#     anonymous plus wired plus compressed pages, with the file cache and"},
{"lineNum":"   20","line":"#     purgeable pages excluded because the kernel can take those back at will."},
{"lineNum":"   21","line":"#     A naive total-minus-free reads ~99% at all times and says nothing."},
{"lineNum":"   22","line":"#   * the compressor — how much has been squeezed rather than paged out."},
{"lineNum":"   23","line":"#"},
{"lineNum":"   24","line":"# The alert names the heaviest applications, and it measures them by resident"},
{"lineNum":"   25","line":"# plus *compressed* memory. Resident size alone is actively misleading here: a"},
{"lineNum":"   26","line":"# browser holding tens of gigabytes across dozens of helper processes reports a"},
{"lineNum":"   27","line":"# few hundred megabytes each, so the real cause looks innocent while some idle"},
{"lineNum":"   28","line":"# background process looks like the problem. Totals are aggregated per"},
{"lineNum":"   29","line":"# application, since blame belongs to the app, not to its 56th renderer."},
{"lineNum":"   30","line":"#"},
{"lineNum":"   31","line":"# Designed to be run from a launchd agent every few minutes. It raises nothing"},
{"lineNum":"   32","line":"# and exits 0 while the machine is healthy, so it can be left running"},
{"lineNum":"   33","line":"# indefinitely."},
{"lineNum":"   34","line":"#"},
{"lineNum":"   35","line":"# Usage:"},
{"lineNum":"   36","line":"#   ./memory-pressure-alert.sh [OPTIONS]"},
{"lineNum":"   37","line":""},
{"lineNum":"   38","line":"set -o errexit","class":"lineCov","hits":"1","order":"3416",},
{"lineNum":"   39","line":"set -o nounset","class":"lineCov","hits":"1","order":"3438",},
{"lineNum":"   40","line":"set -o pipefail","class":"lineCov","hits":"1","order":"3454",},
{"lineNum":"   41","line":""},
{"lineNum":"   42","line":"# --- Shared Library ---"},
{"lineNum":"   43","line":"# shellcheck source=../../lib/colors.sh"},
{"lineNum":"   44","line":"source \"$(cd \"$(dirname \"$0\")\" && pwd -P)/../../lib/colors.sh\"","class":"lineCov","hits":"1","order":"3425",},
{"lineNum":"   45","line":"# @include ../../lib/colors.sh"},
{"lineNum":"   46","line":"# shellcheck source=../../lib/cli.sh"},
{"lineNum":"   47","line":"source \"$(cd \"$(dirname \"$0\")\" && pwd -P)/../../lib/cli.sh\"","class":"lineCov","hits":"1","order":"3422",},
{"lineNum":"   48","line":"# @include ../../lib/cli.sh"},
{"lineNum":"   49","line":"# shellcheck source=../../lib/core.sh"},
{"lineNum":"   50","line":"source \"$(cd \"$(dirname \"$0\")\" && pwd -P)/../../lib/core.sh\"","class":"lineCov","hits":"1","order":"3406",},
{"lineNum":"   51","line":"# @include ../../lib/core.sh"},
{"lineNum":"   52","line":"# shellcheck source=../../lib/config.sh"},
{"lineNum":"   53","line":"source \"$(cd \"$(dirname \"$0\")\" && pwd -P)/../../lib/config.sh\"","class":"lineCov","hits":"1","order":"3455",},
{"lineNum":"   54","line":"# @include ../../lib/config.sh"},
{"lineNum":"   55","line":"# shellcheck source=../../lib/program.sh"},
{"lineNum":"   56","line":"source \"$(cd \"$(dirname \"$0\")\" && pwd -P)/../../lib/program.sh\"","class":"lineCov","hits":"1","order":"3418",},
{"lineNum":"   57","line":"# @include ../../lib/program.sh"},
{"lineNum":"   58","line":""},
{"lineNum":"   59","line":"# --- Constants ---"},
{"lineNum":"   60","line":"# The three readings come from the environment when set. They are live kernel"},
{"lineNum":"   61","line":"# state that cannot be conjured on demand, so pointing them at fixtures is what"},
{"lineNum":"   62","line":"# makes the threshold logic and the reporting testable at all; unset, they run"},
{"lineNum":"   63","line":"# the real commands."},
{"lineNum":"   64","line":": \"${SWAPUSAGE_CMD:=sysctl -n vm.swapusage}\"","class":"lineCov","hits":"1","order":"3446",},
{"lineNum":"   65","line":": \"${MEMSIZE_CMD:=sysctl -n hw.memsize}\"","class":"lineCov","hits":"1","order":"3441",},
{"lineNum":"   66","line":": \"${VMSTAT_CMD:=vm_stat}\"","class":"lineCov","hits":"1","order":"3433",},
{"lineNum":"   67","line":": \"${PS_CMD:=ps -Ao rss=,comm=}\"","class":"lineCov","hits":"1","order":"3413",},
{"lineNum":"   68","line":": \"${TOP_CMD:=top -l 1 -stats command,mem,cmprs -n 400}\"","class":"lineCov","hits":"1","order":"3409",},
{"lineNum":"   69","line":": \"${NOTIFY_CMD:=osascript}\"","class":"lineCov","hits":"1","order":"3432",},
{"lineNum":"   70","line":"# The launchd installation targets are seams for the same reason: --install"},
{"lineNum":"   71","line":"# writes into the user\'s real agent directory and loads it for real, which a test"},
{"lineNum":"   72","line":"# must be able to redirect somewhere harmless."},
{"lineNum":"   73","line":": \"${LAUNCHCTL_CMD:=launchctl}\"","class":"lineCov","hits":"1","order":"3429",},
{"lineNum":"   74","line":": \"${LAUNCH_AGENTS_DIR:=${HOME}/Library/LaunchAgents}\"","class":"lineCov","hits":"1","order":"3398",},
{"lineNum":"   75","line":": \"${AGENT_LOG_DIR:=${HOME}/Library/Logs}\"","class":"lineCov","hits":"1","order":"3448",},
{"lineNum":"   76","line":"readonly SWAPUSAGE_CMD MEMSIZE_CMD VMSTAT_CMD PS_CMD TOP_CMD NOTIFY_CMD","class":"lineCov","hits":"1","order":"3424",},
{"lineNum":"   77","line":"readonly LAUNCHCTL_CMD LAUNCH_AGENTS_DIR AGENT_LOG_DIR","class":"lineCov","hits":"1","order":"3396",},
{"lineNum":"   78","line":""},
{"lineNum":"   79","line":"# How many applications the alert names. Enough to identify the cause without"},
{"lineNum":"   80","line":"# turning a notification into a list nobody reads on a lock screen."},
{"lineNum":"   81","line":"readonly TOP_OFFENDERS=3","class":"lineCov","hits":"1","order":"3451",},
{"lineNum":"   82","line":""},
{"lineNum":"   83","line":"# launchd identifies an agent by a reverse-DNS label, which is also the plist\'s"},
{"lineNum":"   84","line":"# basename, so the two can never drift apart."},
{"lineNum":"   85","line":"readonly AGENT_LABEL=\"si.merhar.memory-pressure-alert\"","class":"lineCov","hits":"1","order":"3420",},
{"lineNum":"   86","line":""},
{"lineNum":"   87","line":"# How often the installed agent runs. Swap accrues over days, so five minutes is"},
{"lineNum":"   88","line":"# far more often than the signal changes — chosen to keep the notice prompt"},
{"lineNum":"   89","line":"# without the check ever being noticeable."},
{"lineNum":"   90","line":"readonly DEFAULT_INTERVAL_SECONDS=300","class":"lineCov","hits":"1","order":"3456",},
{"lineNum":"   91","line":""},
{"lineNum":"   92","line":"# --- Configuration Defaults ---"},
{"lineNum":"   93","line":"# Swap first: on a healthy machine it is near zero, so any sustained growth is"},
{"lineNum":"   94","line":"# already news. Used memory is the confirming signal — it climbs through the day"},
{"lineNum":"   95","line":"# and sits high on a machine that is coping, so only a high threshold means"},
{"lineNum":"   96","line":"# trouble."},
{"lineNum":"   97","line":"SWAP_WARN_MB=2048","class":"lineCov","hits":"1","order":"3463",},
{"lineNum":"   98","line":"USED_WARN_PERCENT=85","class":"lineCov","hits":"1","order":"3465",},
{"lineNum":"   99","line":"COMPRESSOR_WARN_MB=8192","class":"lineCov","hits":"1","order":"3467",},
{"lineNum":"  100","line":""},
{"lineNum":"  101","line":"# The threshold\'s meaning inverted when the reading became \"used\" rather than \"free\", so an old"},
{"lineNum":"  102","line":"# setting left in a config file would mean the opposite of what its author intended — 25 would read"},
{"lineNum":"  103","line":"# as \"warn above 25% used\", which is always. The old name is therefore refused rather than honoured."},
{"lineNum":"  104","line":"readonly RETIRED_CONFIG_KEY=\"PRESSURE_WARN_PERCENT\"","class":"lineCov","hits":"1","order":"3449",},
{"lineNum":"  105","line":""},
{"lineNum":"  106","line":"########################################"},
{"lineNum":"  107","line":"# Print the usage text."},
{"lineNum":"  108","line":"# Outputs:"},
{"lineNum":"  109","line":"#   Writes the usage message to stdout."},
{"lineNum":"  110","line":"########################################"},
{"lineNum":"  111","line":"show_usage() {"},
{"lineNum":"  112","line":"  cat <<USAGE","class":"lineCov","hits":"1","order":"3472",},
{"lineNum":"  113","line":"${_C_BOLD}Usage:${_C_RESET} ${SCRIPT_NAME} [OPTIONS]"},
{"lineNum":"  114","line":""},
{"lineNum":"  115","line":"Warns while a Mac is filling up — growing swap and rising memory use — rather"},
{"lineNum":"  116","line":"than once it has already stalled. Names the heaviest applications by resident"},
{"lineNum":"  117","line":"plus compressed memory, aggregated per application."},
{"lineNum":"  118","line":""},
{"lineNum":"  119","line":"Raises nothing and exits 0 while healthy, so it suits a launchd agent."},
{"lineNum":"  120","line":""},
{"lineNum":"  121","line":"${_C_BOLD}Options:${_C_RESET}"},
{"lineNum":"  122","line":"  -s, --swap-mb MB        Warn at this much swap in use (default: ${SWAP_WARN_MB})"},
{"lineNum":"  123","line":"  -u, --used PERCENT      Warn at this much memory in use (default: ${USED_WARN_PERCENT})"},
{"lineNum":"  124","line":"  -c, --compressor MB     Warn at this much compressed memory (default: ${COMPRESSOR_WARN_MB})"},
{"lineNum":"  125","line":"  -r, --report            Print the current readings and exit, whatever their values"},
{"lineNum":"  126","line":"  -n, --no-notify         Print to stdout instead of sending a notification"},
{"lineNum":"  127","line":"      --install           Install a launchd agent that runs this periodically"},
{"lineNum":"  128","line":"      --uninstall         Remove the launchd agent"},
{"lineNum":"  129","line":"  -i, --interval SECONDS  How often the agent runs, with --install (default: ${DEFAULT_INTERVAL_SECONDS})"},
{"lineNum":"  130","line":"      --no-color          Disable coloured output"},
{"lineNum":"  131","line":"  -d, --debug             Enable debug logging"},
{"lineNum":"  132","line":"  -h, --help              Show this help message"},
{"lineNum":"  133","line":""},
{"lineNum":"  134","line":"${_C_BOLD}Exit Codes:${_C_RESET}"},
{"lineNum":"  135","line":"  0  Healthy, a report was printed, or the agent was installed or removed"},
{"lineNum":"  136","line":"  1  Usage error, or the agent could not be loaded"},
{"lineNum":"  137","line":"  2  A threshold was crossed and an alert was raised"},
{"lineNum":"  138","line":"USAGE"},
{"lineNum":"  139","line":"}"},
{"lineNum":"  140","line":""},
{"lineNum":"  141","line":"########################################"},
{"lineNum":"  142","line":"# Read swap in use, in whole MB."},
{"lineNum":"  143","line":"# Globals:"},
{"lineNum":"  144","line":"#   SWAPUSAGE_CMD"},
{"lineNum":"  145","line":"# Outputs:"},
{"lineNum":"  146","line":"#   Writes the integer MB to stdout, or 0 when the figure cannot be read."},
{"lineNum":"  147","line":"########################################"},
{"lineNum":"  148","line":"read_swap_mb() {"},
{"lineNum":"  149","line":"  local raw","class":"lineCov","hits":"1","order":"3457",},
{"lineNum":"  150","line":"  raw=$(${SWAPUSAGE_CMD} 2>/dev/null) || raw=\"\"","class":"lineCov","hits":"1","order":"3477",},
{"lineNum":"  151","line":"  # vm.swapusage reports \"total = 1024.00M used = 512.25M free = 511.75M\"."},
{"lineNum":"  152","line":"  # Sizes carry an M suffix in every macOS release that has this sysctl, so the"},
{"lineNum":"  153","line":"  # suffix is stripped rather than interpreted."},
{"lineNum":"  154","line":"  local used","class":"lineCov","hits":"1","order":"3436",},
{"lineNum":"  155","line":"  used=$(printf \'%s\\n\' \"${raw}\" | sed -n \'s/.*used = \\([0-9.]*\\)M.*/\\1/p\')","class":"lineCov","hits":"1","order":"3479",},
{"lineNum":"  156","line":"  [[ -z ${used} ]] && { printf \'0\\n\'; return 0; }","class":"lineCov","hits":"1","order":"3415",},
{"lineNum":"  157","line":"  printf \'%.0f\\n\' \"${used}\"","class":"lineCov","hits":"1","order":"3481",},
{"lineNum":"  158","line":"}"},
{"lineNum":"  159","line":""},
{"lineNum":"  160","line":"########################################"},
{"lineNum":"  161","line":"# Read used memory as a percentage of the total."},
{"lineNum":"  162","line":"#"},
{"lineNum":"  163","line":"# Counted the way Activity Monitor and Stats count it: anonymous, wired and"},
{"lineNum":"  164","line":"# compressed pages, with the file cache and purgeable pages subtracted because the"},
{"lineNum":"  165","line":"# kernel reclaims those on demand and they are not a shortage. A plain"},
{"lineNum":"  166","line":"# total-minus-free would read about 99% on any healthy Mac and never move."},
{"lineNum":"  167","line":"#"},
{"lineNum":"  168","line":"# All of it comes from one vm_stat call, so every figure describes the same instant"},
{"lineNum":"  169","line":"# — sampling them separately would let the parts disagree and push the total past"},
{"lineNum":"  170","line":"# 100%."},
{"lineNum":"  171","line":"# Globals:"},
{"lineNum":"  172","line":"#   VMSTAT_CMD, MEMSIZE_CMD"},
{"lineNum":"  173","line":"# Outputs:"},
{"lineNum":"  174","line":"#   Writes the integer percentage to stdout, or 0 when it cannot be read."},
{"lineNum":"  175","line":"########################################"},
{"lineNum":"  176","line":"read_used_percent() {"},
{"lineNum":"  177","line":"  local out total","class":"lineCov","hits":"1","order":"3405",},
{"lineNum":"  178","line":"  out=$(${VMSTAT_CMD} 2>/dev/null) || out=\"\"","class":"lineCov","hits":"1","order":"3403",},
{"lineNum":"  179","line":"  total=$(${MEMSIZE_CMD} 2>/dev/null) || total=\"\"","class":"lineCov","hits":"1","order":"3443",},
{"lineNum":"  180","line":"  # A missing reading must not look like an emergency: this runs unattended, and a"},
{"lineNum":"  181","line":"  # false alarm every few minutes teaches the user to ignore the real one."},
{"lineNum":"  182","line":"  [[ ${total} =~ ^[0-9]+$ ]] && (( total > 0 )) || { printf \'0\\n\'; return 0; }","class":"lineCov","hits":"1","order":"3442",},
{"lineNum":"  183","line":""},
{"lineNum":"  184","line":"  local prog","class":"lineCov","hits":"1","order":"3487",},
{"lineNum":"  185","line":"  prog=$(load_program used-percent.awk)  # @embed used-percent.awk","class":"lineCov","hits":"1","order":"3411",},
{"lineNum":"  186","line":"  printf \'%s\\n\' \"${out}\" | awk -v total=\"${total}\" \"${prog}\"","class":"lineCov","hits":"1","order":"3407",},
{"lineNum":"  187","line":"}"},
{"lineNum":"  188","line":""},
{"lineNum":"  189","line":"########################################"},
{"lineNum":"  190","line":"# Read compressed memory, in whole MB."},
{"lineNum":"  191","line":"# Globals:"},
{"lineNum":"  192","line":"#   VMSTAT_CMD"},
{"lineNum":"  193","line":"# Outputs:"},
{"lineNum":"  194","line":"#   Writes the integer MB to stdout, or 0 when it cannot be read."},
{"lineNum":"  195","line":"########################################"},
{"lineNum":"  196","line":"read_compressor_mb() {"},
{"lineNum":"  197","line":"  local out pages page_size","class":"lineCov","hits":"1","order":"3430",},
{"lineNum":"  198","line":"  out=$(${VMSTAT_CMD} 2>/dev/null) || out=\"\"","class":"lineCov","hits":"1","order":"3401",},
{"lineNum":"  199","line":"  pages=$(printf \'%s\\n\' \"${out}\" \\","class":"lineNoCov","hits":"0",},
{"lineNum":"  200","line":"    | sed -n \'s/^Pages occupied by compressor: *\\([0-9]*\\)\\..*$/\\1/p\')"},
{"lineNum":"  201","line":"  [[ -z ${pages} ]] && { printf \'0\\n\'; return 0; }","class":"lineCov","hits":"1","order":"3397",},
{"lineNum":"  202","line":"  # vm_stat states its own page size, which differs between Intel and Apple"},
{"lineNum":"  203","line":"  # silicon; reading it back avoids assuming either."},
{"lineNum":"  204","line":"  page_size=$(printf \'%s\\n\' \"${out}\" \\","class":"lineNoCov","hits":"0",},
{"lineNum":"  205","line":"    | sed -n \'s/^Mach Virtual Memory Statistics: (page size of \\([0-9]*\\) bytes).*$/\\1/p\')"},
{"lineNum":"  206","line":"  [[ -z ${page_size} ]] && page_size=16384","class":"lineCov","hits":"1","order":"3489",},
{"lineNum":"  207","line":"  printf \'%s\\n\' $(( pages * page_size / 1048576 ))","class":"lineCov","hits":"1","order":"3394",},
{"lineNum":"  208","line":"}"},
{"lineNum":"  209","line":""},
{"lineNum":"  210","line":"########################################"},
{"lineNum":"  211","line":"# List the heaviest applications by resident plus compressed memory."},
{"lineNum":"  212","line":"# Globals:"},
{"lineNum":"  213","line":"#   TOP_CMD, TOP_OFFENDERS"},
{"lineNum":"  214","line":"# Outputs:"},
{"lineNum":"  215","line":"#   Writes \"<MB> <processes> <app>\" lines, heaviest first."},
{"lineNum":"  216","line":"########################################"},
{"lineNum":"  217","line":"read_top_offenders() {"},
{"lineNum":"  218","line":"  local prog","class":"lineCov","hits":"1","order":"3392",},
{"lineNum":"  219","line":"  prog=$(load_program offenders.awk)  # @embed offenders.awk","class":"lineCov","hits":"1","order":"3492",},
{"lineNum":"  220","line":"  ${TOP_CMD} 2>/dev/null \\","class":"lineCov","hits":"1","order":"3494",},
{"lineNum":"  221","line":"    | awk -v want=\"${TOP_OFFENDERS}\" \"${prog}\" \\"},
{"lineNum":"  222","line":"    | sort -rn \\"},
{"lineNum":"  223","line":"    | head -n \"${TOP_OFFENDERS}\""},
{"lineNum":"  224","line":"}"},
{"lineNum":"  225","line":""},
{"lineNum":"  226","line":"########################################"},
{"lineNum":"  227","line":"# Format the readings as a single human-readable line."},
{"lineNum":"  228","line":"# Arguments:"},
{"lineNum":"  229","line":"#   $1 - swap MB, $2 - used percent, $3 - compressor MB"},
{"lineNum":"  230","line":"# Outputs:"},
{"lineNum":"  231","line":"#   Writes the summary to stdout."},
{"lineNum":"  232","line":"########################################"},
{"lineNum":"  233","line":"format_readings() {"},
{"lineNum":"  234","line":"  printf \'swap %s MB · used %s%% · compressed %s MB\\n\' \"$1\" \"$2\" \"$3\"","class":"lineCov","hits":"1","order":"3391",},
{"lineNum":"  235","line":"}"},
{"lineNum":"  236","line":""},
{"lineNum":"  237","line":"########################################"},
{"lineNum":"  238","line":"# Deliver a message, as a notification or on stdout."},
{"lineNum":"  239","line":"# Globals:"},
{"lineNum":"  240","line":"#   NOTIFY_CMD, SCRIPT_NAME"},
{"lineNum":"  241","line":"# Arguments:"},
{"lineNum":"  242","line":"#   $1 - the message body"},
{"lineNum":"  243","line":"#   $2 - \"true\" to print instead of notifying"},
{"lineNum":"  244","line":"# Returns:"},
{"lineNum":"  245","line":"#   0 always — a failed notification must not mask the condition it describes."},
{"lineNum":"  246","line":"########################################"},
{"lineNum":"  247","line":"deliver() {"},
{"lineNum":"  248","line":"  local body=$1 print_only=$2","class":"lineCov","hits":"1","order":"3390",},
{"lineNum":"  249","line":"  if [[ ${print_only} == true ]]; then","class":"lineCov","hits":"1","order":"3389",},
{"lineNum":"  250","line":"    printf \'%s\\n\' \"${body}\"","class":"lineCov","hits":"1","order":"3428",},
{"lineNum":"  251","line":"    return 0","class":"lineCov","hits":"1","order":"3447",},
{"lineNum":"  252","line":"  fi"},
{"lineNum":"  253","line":"  # A notification is best-effort: under heavy memory pressure osascript is"},
{"lineNum":"  254","line":"  # itself liable to be slow or refused, and the log line is what survives."},
{"lineNum":"  255","line":"  ${NOTIFY_CMD} -e \"display notification \\\"${body//\\\"/}\\\" with title \\\"Memory pressure\\\"\" \\","class":"lineCov","hits":"1","order":"3388",},
{"lineNum":"  256","line":"    >/dev/null 2>&1 || log_error \"Could not post the notification: ${body}\""},
{"lineNum":"  257","line":"  return 0","class":"lineCov","hits":"1","order":"3400",},
{"lineNum":"  258","line":"}"},
{"lineNum":"  259","line":""},
{"lineNum":"  260","line":"########################################"},
{"lineNum":"  261","line":"# Print the path of the launchd agent\'s plist."},
{"lineNum":"  262","line":"# Globals:"},
{"lineNum":"  263","line":"#   LAUNCH_AGENTS_DIR, AGENT_LABEL"},
{"lineNum":"  264","line":"# Outputs:"},
{"lineNum":"  265","line":"#   Writes the path to stdout."},
{"lineNum":"  266","line":"########################################"},
{"lineNum":"  267","line":"agent_plist_path() {"},
{"lineNum":"  268","line":"  printf \'%s/%s.plist\\n\' \"${LAUNCH_AGENTS_DIR}\" \"${AGENT_LABEL}\"","class":"lineCov","hits":"1","order":"3459",},
{"lineNum":"  269","line":"}"},
{"lineNum":"  270","line":""},
{"lineNum":"  271","line":"########################################"},
{"lineNum":"  272","line":"# Print the path launchd should invoke."},
{"lineNum":"  273","line":"#"},
{"lineNum":"  274","line":"# The directory is resolved physically but a symlinked file is left as it is: a"},
{"lineNum":"  275","line":"# Homebrew install is a symlink into the versioned Cellar, and an agent pointed at"},
{"lineNum":"  276","line":"# the stable symlink keeps working across upgrades, where one pointed into the"},
{"lineNum":"  277","line":"# Cellar breaks at the next version bump."},
{"lineNum":"  278","line":"# Outputs:"},
{"lineNum":"  279","line":"#   Writes the absolute path to stdout."},
{"lineNum":"  280","line":"########################################"},
{"lineNum":"  281","line":"self_path() {"},
{"lineNum":"  282","line":"  printf \'%s/%s\\n\' \"$(cd \"$(dirname \"$0\")\" && pwd -P)\" \"$(basename \"$0\")\"","class":"lineCov","hits":"1","order":"3387",},
{"lineNum":"  283","line":"}"},
{"lineNum":"  284","line":""},
{"lineNum":"  285","line":"########################################"},
{"lineNum":"  286","line":"# Escape a string for inclusion in XML character data."},
{"lineNum":"  287","line":"#"},
{"lineNum":"  288","line":"# Paths reach the plist from $0 and $HOME, so they are not under this script\'s control: an ampersand"},
{"lineNum":"  289","line":"# in a directory name is legal on macOS and would otherwise produce a plist that is not well-formed,"},
{"lineNum":"  290","line":"# which launchd rejects wholesale rather than reading around."},
{"lineNum":"  291","line":"# Arguments:"},
{"lineNum":"  292","line":"#   $1 - the string to escape"},
{"lineNum":"  293","line":"# Outputs:"},
{"lineNum":"  294","line":"#   Writes the escaped string to stdout."},
{"lineNum":"  295","line":"########################################"},
{"lineNum":"  296","line":"xml_escape() {"},
{"lineNum":"  297","line":"  # Ampersand first: escaping it after the others would corrupt the entities they introduce."},
{"lineNum":"  298","line":"  local out=${1//&/\\&amp;}","class":"lineCov","hits":"1","order":"3427",},
{"lineNum":"  299","line":"  out=${out//</\\&lt;}","class":"lineCov","hits":"1","order":"3460",},
{"lineNum":"  300","line":"  printf \'%s\\n\' \"${out//>/\\&gt;}\"","class":"lineCov","hits":"1","order":"3461",},
{"lineNum":"  301","line":"}"},
{"lineNum":"  302","line":""},
{"lineNum":"  303","line":"########################################"},
{"lineNum":"  304","line":"# Render the launchd agent plist."},
{"lineNum":"  305","line":"#"},
{"lineNum":"  306","line":"# Thresholds are deliberately not passed as arguments: the agent reads the config"},
{"lineNum":"  307","line":"# file like any other invocation, so tuning one is editing that file rather than"},
{"lineNum":"  308","line":"# rewriting and reloading an agent. Output is redirected to a log file because a"},
{"lineNum":"  309","line":"# launchd agent\'s stdout and stderr are otherwise discarded, which leaves \"it"},
{"lineNum":"  310","line":"# never warned me\" impossible to investigate."},
{"lineNum":"  311","line":"# Globals:"},
{"lineNum":"  312","line":"#   AGENT_LABEL, AGENT_LOG_DIR"},
{"lineNum":"  313","line":"# Arguments:"},
{"lineNum":"  314","line":"#   $1 - absolute path to the executable"},
{"lineNum":"  315","line":"#   $2 - interval between runs, in seconds"},
{"lineNum":"  316","line":"# Outputs:"},
{"lineNum":"  317","line":"#   Writes the plist XML to stdout."},
{"lineNum":"  318","line":"########################################"},
{"lineNum":"  319","line":"render_agent_plist() {"},
{"lineNum":"  320","line":"  local program interval log_path","class":"lineCov","hits":"1","order":"3431",},
{"lineNum":"  321","line":"  program=$(xml_escape \"$1\")","class":"lineCov","hits":"1","order":"3445",},
{"lineNum":"  322","line":"  interval=$2","class":"lineCov","hits":"1","order":"3440",},
{"lineNum":"  323","line":"  log_path=$(xml_escape \"${AGENT_LOG_DIR}/${AGENT_LABEL}.log\")","class":"lineCov","hits":"1","order":"3434",},
{"lineNum":"  324","line":"  cat <<PLIST","class":"lineCov","hits":"1","order":"3412",},
{"lineNum":"  325","line":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>"},
{"lineNum":"  326","line":"<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">"},
{"lineNum":"  327","line":"<plist version=\"1.0\">"},
{"lineNum":"  328","line":"<dict>"},
{"lineNum":"  329","line":"  <key>Label</key>             <string>${AGENT_LABEL}</string>"},
{"lineNum":"  330","line":"  <key>ProgramArguments</key>  <array><string>${program}</string></array>"},
{"lineNum":"  331","line":"  <key>StartInterval</key>     <integer>${interval}</integer>"},
{"lineNum":"  332","line":"  <key>RunAtLoad</key>         <true/>"},
{"lineNum":"  333","line":"  <key>StandardOutPath</key>   <string>${log_path}</string>"},
{"lineNum":"  334","line":"  <key>StandardErrorPath</key> <string>${log_path}</string>"},
{"lineNum":"  335","line":"</dict>"},
{"lineNum":"  336","line":"</plist>"},
{"lineNum":"  337","line":"PLIST"},
{"lineNum":"  338","line":"}"},
{"lineNum":"  339","line":""},
{"lineNum":"  340","line":"########################################"},
{"lineNum":"  341","line":"# Install the launchd agent and load it."},
{"lineNum":"  342","line":"#"},
{"lineNum":"  343","line":"# Idempotent, so reinstalling is how the interval is changed: an already-loaded"},
{"lineNum":"  344","line":"# agent keeps running with the plist it was loaded from, so the old one is"},
{"lineNum":"  345","line":"# unloaded before the new one is loaded rather than only rewritten on disk."},
{"lineNum":"  346","line":"# Globals:"},
{"lineNum":"  347","line":"#   LAUNCHCTL_CMD, LAUNCH_AGENTS_DIR, AGENT_LOG_DIR, AGENT_LABEL"},
{"lineNum":"  348","line":"# Arguments:"},
{"lineNum":"  349","line":"#   $1 - interval between runs, in seconds"},
{"lineNum":"  350","line":"# Returns:"},
{"lineNum":"  351","line":"#   0 on success, 1 if launchd refused to load the agent."},
{"lineNum":"  352","line":"########################################"},
{"lineNum":"  353","line":"install_agent() {"},
{"lineNum":"  354","line":"  local interval=$1 plist program","class":"lineCov","hits":"1","order":"3464",},
{"lineNum":"  355","line":"  plist=$(agent_plist_path)","class":"lineCov","hits":"1","order":"3466",},
{"lineNum":"  356","line":"  program=$(self_path)","class":"lineCov","hits":"1","order":"3468",},
{"lineNum":"  357","line":""},
{"lineNum":"  358","line":"  mkdir -p \"${LAUNCH_AGENTS_DIR}\" \"${AGENT_LOG_DIR}\"","class":"lineCov","hits":"1","order":"3450",},
{"lineNum":"  359","line":"  render_agent_plist \"${program}\" \"${interval}\" >\"${plist}\"","class":"lineCov","hits":"1","order":"3469",},
{"lineNum":"  360","line":""},
{"lineNum":"  361","line":"  # Absent on a first install, so this failing is the normal case and says"},
{"lineNum":"  362","line":"  # nothing about whether the load below will succeed."},
{"lineNum":"  363","line":"  ${LAUNCHCTL_CMD} unload \"${plist}\" >/dev/null 2>&1 || true","class":"lineCov","hits":"1","order":"3470",},
{"lineNum":"  364","line":""},
{"lineNum":"  365","line":"  if ! ${LAUNCHCTL_CMD} load \"${plist}\"; then","class":"lineCov","hits":"1","order":"3471",},
{"lineNum":"  366","line":"    log_error \"Wrote ${plist}, but launchctl refused to load it.\"","class":"lineCov","hits":"1","order":"3502",},
{"lineNum":"  367","line":"    return 1","class":"lineCov","hits":"1","order":"3503",},
{"lineNum":"  368","line":"  fi"},
{"lineNum":"  369","line":"  log_info \"Installed — runs ${program} every ${interval}s.\"","class":"lineCov","hits":"1","order":"3473",},
{"lineNum":"  370","line":"  log_info \"Agent: ${plist}\"","class":"lineCov","hits":"1","order":"3474",},
{"lineNum":"  371","line":"  log_info \"Log:   ${AGENT_LOG_DIR}/${AGENT_LABEL}.log\"","class":"lineCov","hits":"1","order":"3475",},
{"lineNum":"  372","line":"  return 0","class":"lineCov","hits":"1","order":"3476",},
{"lineNum":"  373","line":"}"},
{"lineNum":"  374","line":""},
{"lineNum":"  375","line":"########################################"},
{"lineNum":"  376","line":"# Unload the launchd agent and remove its plist."},
{"lineNum":"  377","line":"# Globals:"},
{"lineNum":"  378","line":"#   LAUNCHCTL_CMD"},
{"lineNum":"  379","line":"# Returns:"},
{"lineNum":"  380","line":"#   0 always — an agent that is already absent is the desired end state."},
{"lineNum":"  381","line":"########################################"},
{"lineNum":"  382","line":"uninstall_agent() {"},
{"lineNum":"  383","line":"  local plist","class":"lineCov","hits":"1","order":"3504",},
{"lineNum":"  384","line":"  plist=$(agent_plist_path)","class":"lineCov","hits":"1","order":"3500",},
{"lineNum":"  385","line":"  if [[ ! -f \"${plist}\" ]]; then","class":"lineCov","hits":"1","order":"3505",},
{"lineNum":"  386","line":"    log_info \"Not installed (no ${plist}).\"","class":"lineCov","hits":"1","order":"3506",},
{"lineNum":"  387","line":"    return 0","class":"lineCov","hits":"1","order":"3507",},
{"lineNum":"  388","line":"  fi"},
{"lineNum":"  389","line":"  # Unloaded before the plist goes, since launchctl needs the file to identify"},
{"lineNum":"  390","line":"  # what to stop; a stale in-memory job would otherwise keep running until logout."},
{"lineNum":"  391","line":"  ${LAUNCHCTL_CMD} unload \"${plist}\" >/dev/null 2>&1 || true","class":"lineCov","hits":"1","order":"3508",},
{"lineNum":"  392","line":"  rm -f \"${plist}\"","class":"lineCov","hits":"1","order":"3509",},
{"lineNum":"  393","line":"  log_info \"Uninstalled — removed ${plist}.\"","class":"lineCov","hits":"1","order":"3510",},
{"lineNum":"  394","line":"  return 0","class":"lineCov","hits":"1","order":"3511",},
{"lineNum":"  395","line":"}"},
{"lineNum":"  396","line":""},
{"lineNum":"  397","line":"########################################"},
{"lineNum":"  398","line":"# Main entry point."},
{"lineNum":"  399","line":"# Globals:"},
{"lineNum":"  400","line":"#   All configuration and command globals."},
{"lineNum":"  401","line":"# Arguments:"},
{"lineNum":"  402","line":"#   Command-line arguments."},
{"lineNum":"  403","line":"# Returns:"},
{"lineNum":"  404","line":"#   0 healthy or reported, 2 alert raised. Usage errors exit 1 via die_usage."},
{"lineNum":"  405","line":"########################################"},
{"lineNum":"  406","line":"main() {"},
{"lineNum":"  407","line":"  local opt_report=false opt_no_notify=false wanted_color=auto","class":"lineCov","hits":"1","order":"3478",},
{"lineNum":"  408","line":"  # CLI values are held separately from the config globals and applied after the"},
{"lineNum":"  409","line":"  # config is read. Writing them straight into the globals would let the config"},
{"lineNum":"  410","line":"  # file silently overwrite an explicit flag, since it is loaded afterwards."},
{"lineNum":"  411","line":"  local opt_swap=\"\" opt_used=\"\" opt_compressor=\"\"","class":"lineCov","hits":"1","order":"3437",},
{"lineNum":"  412","line":"  local opt_install=false opt_uninstall=false opt_interval=\"\"","class":"lineCov","hits":"1","order":"3480",},
{"lineNum":"  413","line":""},
{"lineNum":"  414","line":"  while [[ $# -gt 0 ]]; do","class":"lineCov","hits":"1","order":"3482",},
{"lineNum":"  415","line":"    case \"$1\" in","class":"lineCov","hits":"1","order":"3483",},
{"lineNum":"  416","line":"      -s|--swap-mb)"},
{"lineNum":"  417","line":"        require_option_value \"$1\" \"${2:-}\"","class":"lineCov","hits":"1","order":"3484",},
{"lineNum":"  418","line":"        opt_swap=$2","class":"lineCov","hits":"1","order":"3485",},
{"lineNum":"  419","line":"        shift 2","class":"lineCov","hits":"1","order":"3417",},
{"lineNum":"  420","line":"        ;;"},
{"lineNum":"  421","line":"      -u|--used)"},
{"lineNum":"  422","line":"        require_option_value \"$1\" \"${2:-}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  423","line":"        opt_used=$2","class":"lineNoCov","hits":"0",},
{"lineNum":"  424","line":"        shift 2","class":"lineNoCov","hits":"0",},
{"lineNum":"  425","line":"        ;;"},
{"lineNum":"  426","line":"      -c|--compressor)"},
{"lineNum":"  427","line":"        require_option_value \"$1\" \"${2:-}\"","class":"lineCov","hits":"1","order":"3462",},
{"lineNum":"  428","line":"        opt_compressor=$2","class":"lineCov","hits":"1","order":"3423",},
{"lineNum":"  429","line":"        shift 2","class":"lineCov","hits":"1","order":"3486",},
{"lineNum":"  430","line":"        ;;"},
{"lineNum":"  431","line":"      -r|--report)"},
{"lineNum":"  432","line":"        opt_report=true","class":"lineCov","hits":"1","order":"3404",},
{"lineNum":"  433","line":"        shift","class":"lineCov","hits":"1","order":"3402",},
{"lineNum":"  434","line":"        ;;"},
{"lineNum":"  435","line":"      -n|--no-notify)"},
{"lineNum":"  436","line":"        opt_no_notify=true","class":"lineCov","hits":"1","order":"3444",},
{"lineNum":"  437","line":"        shift","class":"lineCov","hits":"1","order":"3419",},
{"lineNum":"  438","line":"        ;;"},
{"lineNum":"  439","line":"      --install)"},
{"lineNum":"  440","line":"        opt_install=true","class":"lineCov","hits":"1","order":"3408",},
{"lineNum":"  441","line":"        shift","class":"lineCov","hits":"1","order":"3488",},
{"lineNum":"  442","line":"        ;;"},
{"lineNum":"  443","line":"      --uninstall)"},
{"lineNum":"  444","line":"        opt_uninstall=true","class":"lineCov","hits":"1","order":"3512",},
{"lineNum":"  445","line":"        shift","class":"lineCov","hits":"1","order":"3501",},
{"lineNum":"  446","line":"        ;;"},
{"lineNum":"  447","line":"      -i|--interval)"},
{"lineNum":"  448","line":"        require_option_value \"$1\" \"${2:-}\"","class":"lineCov","hits":"1","order":"3414",},
{"lineNum":"  449","line":"        opt_interval=$2","class":"lineCov","hits":"1","order":"3410",},
{"lineNum":"  450","line":"        shift 2","class":"lineCov","hits":"1","order":"3435",},
{"lineNum":"  451","line":"        ;;"},
{"lineNum":"  452","line":"      --no-color)"},
{"lineNum":"  453","line":"        wanted_color=never","class":"lineNoCov","hits":"0",},
{"lineNum":"  454","line":"        shift","class":"lineNoCov","hits":"0",},
{"lineNum":"  455","line":"        ;;"},
{"lineNum":"  456","line":"      -d|--debug)"},
{"lineNum":"  457","line":"        enable_debug_mode","class":"lineNoCov","hits":"0",},
{"lineNum":"  458","line":"        shift","class":"lineNoCov","hits":"0",},
{"lineNum":"  459","line":"        ;;"},
{"lineNum":"  460","line":"      -h|--help)"},
{"lineNum":"  461","line":"        setup_colors \"${wanted_color}\"","class":"lineCov","hits":"1","order":"3395",},
{"lineNum":"  462","line":"        show_usage","class":"lineCov","hits":"1","order":"3452",},
{"lineNum":"  463","line":"        return 0","class":"lineCov","hits":"1","order":"3490",},
{"lineNum":"  464","line":"        ;;"},
{"lineNum":"  465","line":"      *)"},
{"lineNum":"  466","line":"        setup_colors \"${wanted_color}\"","class":"lineCov","hits":"1","order":"3421",},
{"lineNum":"  467","line":"        die_usage \"Unknown option \'$1\'.\"","class":"lineCov","hits":"1","order":"3491",},
{"lineNum":"  468","line":"        ;;"},
{"lineNum":"  469","line":"    esac"},
{"lineNum":"  470","line":"  done"},
{"lineNum":"  471","line":""},
{"lineNum":"  472","line":"  setup_colors \"${wanted_color}\"","class":"lineCov","hits":"1","order":"3393",},
{"lineNum":"  473","line":""},
{"lineNum":"  474","line":"  # Handled before the config is read, because installing the agent does not"},
{"lineNum":"  475","line":"  # depend on any threshold: the agent reads the config itself at each run."},
{"lineNum":"  476","line":"  if [[ ${opt_install} == true && ${opt_uninstall} == true ]]; then","class":"lineCov","hits":"1","order":"3493",},
{"lineNum":"  477","line":"    die_usage \"--install and --uninstall cannot be combined.\"","class":"lineCov","hits":"1","order":"3513",},
{"lineNum":"  478","line":"  fi"},
{"lineNum":"  479","line":"  if [[ -n ${opt_interval} && ${opt_install} != true ]]; then","class":"lineCov","hits":"1","order":"3439",},
{"lineNum":"  480","line":"    die_usage \"--interval applies only to --install.\"","class":"lineCov","hits":"1","order":"3498",},
{"lineNum":"  481","line":"  fi"},
{"lineNum":"  482","line":"  if [[ ${opt_install} == true ]]; then","class":"lineCov","hits":"1","order":"3386",},
{"lineNum":"  483","line":"    local interval=${opt_interval:-${DEFAULT_INTERVAL_SECONDS}}","class":"lineCov","hits":"1","order":"3385",},
{"lineNum":"  484","line":"    # Rejected here rather than left to launchd, which accepts a nonsensical"},
{"lineNum":"  485","line":"    # StartInterval by ignoring the key and running the agent only at load."},
{"lineNum":"  486","line":"    [[ ${interval} =~ ^[1-9][0-9]*$ ]] \\","class":"lineCov","hits":"1","order":"3384",},
{"lineNum":"  487","line":"      || die_usage \"--interval must be a whole number of seconds above zero.\""},
{"lineNum":"  488","line":"    if install_agent \"${interval}\"; then","class":"lineCov","hits":"1","order":"3383",},
{"lineNum":"  489","line":"      return 0","class":"lineCov","hits":"1","order":"3382",},
{"lineNum":"  490","line":"    fi"},
{"lineNum":"  491","line":"    return 1","class":"lineCov","hits":"1","order":"3499",},
{"lineNum":"  492","line":"  fi"},
{"lineNum":"  493","line":"  if [[ ${opt_uninstall} == true ]]; then","class":"lineCov","hits":"1","order":"3381",},
{"lineNum":"  494","line":"    uninstall_agent","class":"lineCov","hits":"1","order":"3497",},
{"lineNum":"  495","line":"    return 0","class":"lineCov","hits":"1","order":"3496",},
{"lineNum":"  496","line":"  fi"},
{"lineNum":"  497","line":""},
{"lineNum":"  498","line":"  load_optional_config","class":"lineCov","hits":"1","order":"3380",},
{"lineNum":"  499","line":""},
{"lineNum":"  500","line":"  # Said out loud rather than ignored quietly: a config written against the old free-memory threshold"},
{"lineNum":"  501","line":"  # would otherwise keep its setting silently dropped, and the user would believe a threshold was in"},
{"lineNum":"  502","line":"  # force that is not."},
{"lineNum":"  503","line":"  if [[ -n ${!RETIRED_CONFIG_KEY:-} ]]; then","class":"lineCov","hits":"1","order":"3379",},
{"lineNum":"  504","line":"    log_error \"${RETIRED_CONFIG_KEY} is no longer read — the reading is now memory *used*, so its\" \\","class":"lineCov","hits":"1","order":"3495",},
{"lineNum":"  505","line":"      \"meaning inverted. Replace it with USED_WARN_PERCENT (default ${USED_WARN_PERCENT}).\""},
{"lineNum":"  506","line":"  fi"},
{"lineNum":"  507","line":""},
{"lineNum":"  508","line":"  # Explicit flags win over the config file."},
{"lineNum":"  509","line":"  [[ -n ${opt_swap} ]] && SWAP_WARN_MB=${opt_swap}","class":"lineCov","hits":"1","order":"3378",},
{"lineNum":"  510","line":"  [[ -n ${opt_used} ]] && USED_WARN_PERCENT=${opt_used}","class":"lineCov","hits":"1","order":"3377",},
{"lineNum":"  511","line":"  [[ -n ${opt_compressor} ]] && COMPRESSOR_WARN_MB=${opt_compressor}","class":"lineCov","hits":"1","order":"3376",},
{"lineNum":"  512","line":""},
{"lineNum":"  513","line":"  local swap_mb used_percent compressor_mb readings","class":"lineCov","hits":"1","order":"3375",},
{"lineNum":"  514","line":"  swap_mb=$(read_swap_mb)","class":"lineCov","hits":"1","order":"3399",},
{"lineNum":"  515","line":"  used_percent=$(read_used_percent)","class":"lineCov","hits":"1","order":"3374",},
{"lineNum":"  516","line":"  compressor_mb=$(read_compressor_mb)","class":"lineCov","hits":"1","order":"3373",},
{"lineNum":"  517","line":"  readings=$(format_readings \"${swap_mb}\" \"${used_percent}\" \"${compressor_mb}\")","class":"lineCov","hits":"1","order":"3372",},
{"lineNum":"  518","line":"  log_debug \"${readings}\"","class":"lineCov","hits":"1","order":"3371",},
{"lineNum":"  519","line":""},
{"lineNum":"  520","line":"  if [[ ${opt_report} == true ]]; then","class":"lineCov","hits":"1","order":"3370",},
{"lineNum":"  521","line":"    printf \'%s\\n\' \"${readings}\"","class":"lineCov","hits":"1","order":"3369",},
{"lineNum":"  522","line":"    read_top_offenders | while read -r mb procs app; do","class":"lineCov","hits":"1","order":"3368",},
{"lineNum":"  523","line":"      printf \'  %6s MB  %3s proc  %s\\n\' \"${mb}\" \"${procs}\" \"${app}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  524","line":"    done"},
{"lineNum":"  525","line":"    return 0","class":"lineCov","hits":"1","order":"3458",},
{"lineNum":"  526","line":"  fi"},
{"lineNum":"  527","line":""},
{"lineNum":"  528","line":"  local -a reasons=()","class":"lineCov","hits":"1","order":"3367",},
{"lineNum":"  529","line":"  (( swap_mb >= SWAP_WARN_MB )) && reasons+=(\"swap ${swap_mb} MB\")"},
{"lineNum":"  530","line":"  (( used_percent >= USED_WARN_PERCENT )) && reasons+=(\"${used_percent}% memory used\")"},
{"lineNum":"  531","line":"  (( compressor_mb >= COMPRESSOR_WARN_MB )) && reasons+=(\"${compressor_mb} MB compressed\")"},
{"lineNum":"  532","line":""},
{"lineNum":"  533","line":"  if (( ${#reasons[@]} == 0 )); then","class":"lineCov","hits":"1","order":"3366",},
{"lineNum":"  534","line":"    log_debug \"Healthy — no threshold crossed.\"","class":"lineCov","hits":"1","order":"3365",},
{"lineNum":"  535","line":"    return 0","class":"lineCov","hits":"1","order":"3364",},
{"lineNum":"  536","line":"  fi"},
{"lineNum":"  537","line":""},
{"lineNum":"  538","line":"  local offenders","class":"lineCov","hits":"1","order":"3363",},
{"lineNum":"  539","line":"  # Named in the alert because identifying the cause is the whole point: without"},
{"lineNum":"  540","line":"  # it the user is told the machine is filling up and left to guess by what."},
{"lineNum":"  541","line":"  offenders=$(read_top_offenders | awk \'{printf \"%s %.1f GB; \", $3, $1/1024}\' | sed \'s/; $//\')","class":"lineCov","hits":"1","order":"3362",},
{"lineNum":"  542","line":"  local body","class":"lineCov","hits":"1","order":"3361",},
{"lineNum":"  543","line":"  body=$(printf \'%s. Heaviest: %s\' \\","class":"lineNoCov","hits":"0",},
{"lineNum":"  544","line":"    \"$(IFS=\', \'; printf \'%s\' \"${reasons[*]}\")\" \"${offenders:-unknown}\")"},
{"lineNum":"  545","line":"  log_error \"${body}\"","class":"lineCov","hits":"1","order":"3360",},
{"lineNum":"  546","line":"  deliver \"${body}\" \"${opt_no_notify}\"","class":"lineCov","hits":"1","order":"3359",},
{"lineNum":"  547","line":"  # 2 rather than 1, matching dmarc-report: 1 is what cli.sh\'s die_usage exits for"},
{"lineNum":"  548","line":"  # a usage error, so a raised condition needs its own code to stay distinguishable."},
{"lineNum":"  549","line":"  return 2","class":"lineCov","hits":"1","order":"3358",},
{"lineNum":"  550","line":"}"},
{"lineNum":"  551","line":""},
{"lineNum":"  552","line":"# Guarded so the test harness can source this file and call individual functions;"},
{"lineNum":"  553","line":"# an unguarded call would run the whole tool the moment it is sourced."},
{"lineNum":"  554","line":"if [[ \"${BASH_SOURCE[0]}\" == \"${0}\" ]]; then","class":"lineCov","hits":"1","order":"3453",},
{"lineNum":"  555","line":"  main \"$@\"","class":"lineCov","hits":"1","order":"3426",},
{"lineNum":"  556","line":"fi"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "update-all-indexes.sh", "date" : "2026-08-21 11:44:22", "instrumented" : 167, "covered" : 156,};
var merged_data = [];
