var data = {lines:[
{"lineNum":"    1","line":"#!/usr/bin/env bash"},
{"lineNum":"    2","line":"#"},
{"lineNum":"    3","line":"# memory-pressure-alert.sh — warn while a Mac is filling up, not once it has"},
{"lineNum":"    4","line":"# already ground to a halt."},
{"lineNum":"    5","line":"#"},
{"lineNum":"    6","line":"# macOS does not run out of memory so much as it slides: pages compress, then"},
{"lineNum":"    7","line":"# swap grows, and the machine stays usable for days. Then free swap reaches zero"},
{"lineNum":"    8","line":"# and everything stalls at once — a load average in the hundreds, every process"},
{"lineNum":"    9","line":"# blocked on memory, and no single culprit visible in Activity Monitor."},
{"lineNum":"   10","line":"#"},
{"lineNum":"   11","line":"# \"Memory used\" cannot warn about that, because it is pinned near the installed"},
{"lineNum":"   12","line":"# total at all times. The numbers that move are:"},
{"lineNum":"   13","line":"#"},
{"lineNum":"   14","line":"#   * swap in use — the leading indicator. It accrues over days of uptime and is"},
{"lineNum":"   15","line":"#     the only one that is near zero on a healthy machine, so a modest threshold"},
{"lineNum":"   16","line":"#     gives days of notice."},
{"lineNum":"   17","line":"#   * free-memory percentage (kern.memorystatus_level) — what the kernel itself"},
{"lineNum":"   18","line":"#     watches. It falls as the stall approaches."},
{"lineNum":"   19","line":"#   * the compressor — how much has been squeezed rather than paged out."},
{"lineNum":"   20","line":"#"},
{"lineNum":"   21","line":"# The alert names the heaviest applications, and it measures them by resident"},
{"lineNum":"   22","line":"# plus *compressed* memory. Resident size alone is actively misleading here: a"},
{"lineNum":"   23","line":"# browser holding tens of gigabytes across dozens of helper processes reports a"},
{"lineNum":"   24","line":"# few hundred megabytes each, so the real cause looks innocent while some idle"},
{"lineNum":"   25","line":"# background process looks like the problem. Totals are aggregated per"},
{"lineNum":"   26","line":"# application, since blame belongs to the app, not to its 56th renderer."},
{"lineNum":"   27","line":"#"},
{"lineNum":"   28","line":"# Designed to be run from a launchd agent every few minutes. It raises nothing"},
{"lineNum":"   29","line":"# and exits 0 while the machine is healthy, so it can be left running"},
{"lineNum":"   30","line":"# indefinitely."},
{"lineNum":"   31","line":"#"},
{"lineNum":"   32","line":"# Usage:"},
{"lineNum":"   33","line":"#   ./memory-pressure-alert.sh [OPTIONS]"},
{"lineNum":"   34","line":""},
{"lineNum":"   35","line":"set -o errexit","class":"lineCov","hits":"1","order":"3380",},
{"lineNum":"   36","line":"set -o nounset","class":"lineCov","hits":"1","order":"3384",},
{"lineNum":"   37","line":"set -o pipefail","class":"lineCov","hits":"1","order":"3394",},
{"lineNum":"   38","line":""},
{"lineNum":"   39","line":"# --- Shared Library ---"},
{"lineNum":"   40","line":"# shellcheck source=../../lib/colors.sh"},
{"lineNum":"   41","line":"source \"$(cd \"$(dirname \"$0\")\" && pwd -P)/../../lib/colors.sh\"","class":"lineCov","hits":"1","order":"3371",},
{"lineNum":"   42","line":"# @include ../../lib/colors.sh"},
{"lineNum":"   43","line":"# shellcheck source=../../lib/cli.sh"},
{"lineNum":"   44","line":"source \"$(cd \"$(dirname \"$0\")\" && pwd -P)/../../lib/cli.sh\"","class":"lineCov","hits":"1","order":"3373",},
{"lineNum":"   45","line":"# @include ../../lib/cli.sh"},
{"lineNum":"   46","line":"# shellcheck source=../../lib/core.sh"},
{"lineNum":"   47","line":"source \"$(cd \"$(dirname \"$0\")\" && pwd -P)/../../lib/core.sh\"","class":"lineCov","hits":"1","order":"3374",},
{"lineNum":"   48","line":"# @include ../../lib/core.sh"},
{"lineNum":"   49","line":"# shellcheck source=../../lib/config.sh"},
{"lineNum":"   50","line":"source \"$(cd \"$(dirname \"$0\")\" && pwd -P)/../../lib/config.sh\"","class":"lineCov","hits":"1","order":"3364",},
{"lineNum":"   51","line":"# @include ../../lib/config.sh"},
{"lineNum":"   52","line":"# shellcheck source=../../lib/program.sh"},
{"lineNum":"   53","line":"source \"$(cd \"$(dirname \"$0\")\" && pwd -P)/../../lib/program.sh\"","class":"lineCov","hits":"1","order":"3377",},
{"lineNum":"   54","line":"# @include ../../lib/program.sh"},
{"lineNum":"   55","line":""},
{"lineNum":"   56","line":"# --- Constants ---"},
{"lineNum":"   57","line":"# The three readings come from the environment when set. They are live kernel"},
{"lineNum":"   58","line":"# state that cannot be conjured on demand, so pointing them at fixtures is what"},
{"lineNum":"   59","line":"# makes the threshold logic and the reporting testable at all; unset, they run"},
{"lineNum":"   60","line":"# the real commands."},
{"lineNum":"   61","line":": \"${SWAPUSAGE_CMD:=sysctl -n vm.swapusage}\"","class":"lineCov","hits":"1","order":"3355",},
{"lineNum":"   62","line":": \"${PRESSURE_CMD:=sysctl -n kern.memorystatus_level}\"","class":"lineCov","hits":"1","order":"3358",},
{"lineNum":"   63","line":": \"${VMSTAT_CMD:=vm_stat}\"","class":"lineCov","hits":"1","order":"3366",},
{"lineNum":"   64","line":": \"${PS_CMD:=ps -Ao rss=,comm=}\"","class":"lineCov","hits":"1","order":"3381",},
{"lineNum":"   65","line":": \"${TOP_CMD:=top -l 1 -stats command,mem,cmprs -n 400}\"","class":"lineCov","hits":"1","order":"3385",},
{"lineNum":"   66","line":": \"${NOTIFY_CMD:=osascript}\"","class":"lineCov","hits":"1","order":"3362",},
{"lineNum":"   67","line":"readonly SWAPUSAGE_CMD PRESSURE_CMD VMSTAT_CMD PS_CMD TOP_CMD NOTIFY_CMD","class":"lineCov","hits":"1","order":"3401",},
{"lineNum":"   68","line":""},
{"lineNum":"   69","line":"# How many applications the alert names. Enough to identify the cause without"},
{"lineNum":"   70","line":"# turning a notification into a list nobody reads on a lock screen."},
{"lineNum":"   71","line":"readonly TOP_OFFENDERS=3","class":"lineCov","hits":"1","order":"3354",},
{"lineNum":"   72","line":""},
{"lineNum":"   73","line":"# --- Configuration Defaults ---"},
{"lineNum":"   74","line":"# Swap first: on a healthy machine it is near zero, so any sustained growth is"},
{"lineNum":"   75","line":"# already news. The pressure figure is a confirming signal rather than an early"},
{"lineNum":"   76","line":"# one — by the time free memory is low, the slide is under way."},
{"lineNum":"   77","line":"SWAP_WARN_MB=2048","class":"lineCov","hits":"1","order":"3352",},
{"lineNum":"   78","line":"PRESSURE_WARN_PERCENT=25","class":"lineCov","hits":"1","order":"3351",},
{"lineNum":"   79","line":"COMPRESSOR_WARN_MB=8192","class":"lineCov","hits":"1","order":"3363",},
{"lineNum":"   80","line":""},
{"lineNum":"   81","line":"########################################"},
{"lineNum":"   82","line":"# Print the usage text."},
{"lineNum":"   83","line":"# Outputs:"},
{"lineNum":"   84","line":"#   Writes the usage message to stdout."},
{"lineNum":"   85","line":"########################################"},
{"lineNum":"   86","line":"show_usage() {"},
{"lineNum":"   87","line":"  cat <<USAGE","class":"lineCov","hits":"1","order":"3349",},
{"lineNum":"   88","line":"${_C_BOLD}Usage:${_C_RESET} ${SCRIPT_NAME} [OPTIONS]"},
{"lineNum":"   89","line":""},
{"lineNum":"   90","line":"Warns while a Mac is filling up — growing swap and falling free memory — rather"},
{"lineNum":"   91","line":"than once it has already stalled. Names the heaviest applications by resident"},
{"lineNum":"   92","line":"plus compressed memory, aggregated per application."},
{"lineNum":"   93","line":""},
{"lineNum":"   94","line":"Raises nothing and exits 0 while healthy, so it suits a launchd agent."},
{"lineNum":"   95","line":""},
{"lineNum":"   96","line":"${_C_BOLD}Options:${_C_RESET}"},
{"lineNum":"   97","line":"  -s, --swap-mb MB        Warn at this much swap in use (default: ${SWAP_WARN_MB})"},
{"lineNum":"   98","line":"  -p, --pressure PERCENT  Warn when free memory falls below this (default: ${PRESSURE_WARN_PERCENT})"},
{"lineNum":"   99","line":"  -c, --compressor MB     Warn at this much compressed memory (default: ${COMPRESSOR_WARN_MB})"},
{"lineNum":"  100","line":"  -r, --report            Print the current readings and exit, whatever their values"},
{"lineNum":"  101","line":"  -n, --no-notify         Print to stdout instead of sending a notification"},
{"lineNum":"  102","line":"      --no-color          Disable coloured output"},
{"lineNum":"  103","line":"  -d, --debug             Enable debug logging"},
{"lineNum":"  104","line":"  -h, --help              Show this help message"},
{"lineNum":"  105","line":""},
{"lineNum":"  106","line":"${_C_BOLD}Exit Codes:${_C_RESET}"},
{"lineNum":"  107","line":"  0  Healthy, or a report was printed"},
{"lineNum":"  108","line":"  1  Usage error"},
{"lineNum":"  109","line":"  2  A threshold was crossed and an alert was raised"},
{"lineNum":"  110","line":"USAGE"},
{"lineNum":"  111","line":"}"},
{"lineNum":"  112","line":""},
{"lineNum":"  113","line":"########################################"},
{"lineNum":"  114","line":"# Read swap in use, in whole MB."},
{"lineNum":"  115","line":"# Globals:"},
{"lineNum":"  116","line":"#   SWAPUSAGE_CMD"},
{"lineNum":"  117","line":"# Outputs:"},
{"lineNum":"  118","line":"#   Writes the integer MB to stdout, or 0 when the figure cannot be read."},
{"lineNum":"  119","line":"########################################"},
{"lineNum":"  120","line":"read_swap_mb() {"},
{"lineNum":"  121","line":"  local raw","class":"lineCov","hits":"1","order":"3359",},
{"lineNum":"  122","line":"  raw=$(${SWAPUSAGE_CMD} 2>/dev/null) || raw=\"\"","class":"lineCov","hits":"1","order":"3410",},
{"lineNum":"  123","line":"  # vm.swapusage reports \"total = 1024.00M used = 512.25M free = 511.75M\"."},
{"lineNum":"  124","line":"  # Sizes carry an M suffix in every macOS release that has this sysctl, so the"},
{"lineNum":"  125","line":"  # suffix is stripped rather than interpreted."},
{"lineNum":"  126","line":"  local used","class":"lineCov","hits":"1","order":"3346",},
{"lineNum":"  127","line":"  used=$(printf \'%s\\n\' \"${raw}\" | sed -n \'s/.*used = \\([0-9.]*\\)M.*/\\1/p\')","class":"lineCov","hits":"1","order":"3345",},
{"lineNum":"  128","line":"  [[ -z ${used} ]] && { printf \'0\\n\'; return 0; }","class":"lineCov","hits":"1","order":"3369",},
{"lineNum":"  129","line":"  printf \'%.0f\\n\' \"${used}\"","class":"lineCov","hits":"1","order":"3353",},
{"lineNum":"  130","line":"}"},
{"lineNum":"  131","line":""},
{"lineNum":"  132","line":"########################################"},
{"lineNum":"  133","line":"# Read the kernel\'s free-memory percentage."},
{"lineNum":"  134","line":"# Globals:"},
{"lineNum":"  135","line":"#   PRESSURE_CMD"},
{"lineNum":"  136","line":"# Outputs:"},
{"lineNum":"  137","line":"#   Writes the integer percentage to stdout, or 100 when it cannot be read."},
{"lineNum":"  138","line":"########################################"},
{"lineNum":"  139","line":"read_free_percent() {"},
{"lineNum":"  140","line":"  local level","class":"lineCov","hits":"1","order":"3375",},
{"lineNum":"  141","line":"  level=$(${PRESSURE_CMD} 2>/dev/null) || level=\"\"","class":"lineCov","hits":"1","order":"3343",},
{"lineNum":"  142","line":"  # A missing reading must not look like an emergency, so it reads as healthy —"},
{"lineNum":"  143","line":"  # this runs unattended, and a false alarm every few minutes trains the user to"},
{"lineNum":"  144","line":"  # ignore the real one."},
{"lineNum":"  145","line":"  [[ ${level} =~ ^[0-9]+$ ]] || { printf \'100\\n\'; return 0; }","class":"lineCov","hits":"1","order":"3348",},
{"lineNum":"  146","line":"  printf \'%s\\n\' \"${level}\"","class":"lineCov","hits":"1","order":"3350",},
{"lineNum":"  147","line":"}"},
{"lineNum":"  148","line":""},
{"lineNum":"  149","line":"########################################"},
{"lineNum":"  150","line":"# Read compressed memory, in whole MB."},
{"lineNum":"  151","line":"# Globals:"},
{"lineNum":"  152","line":"#   VMSTAT_CMD"},
{"lineNum":"  153","line":"# Outputs:"},
{"lineNum":"  154","line":"#   Writes the integer MB to stdout, or 0 when it cannot be read."},
{"lineNum":"  155","line":"########################################"},
{"lineNum":"  156","line":"read_compressor_mb() {"},
{"lineNum":"  157","line":"  local out pages page_size","class":"lineCov","hits":"1","order":"3387",},
{"lineNum":"  158","line":"  out=$(${VMSTAT_CMD} 2>/dev/null) || out=\"\"","class":"lineCov","hits":"1","order":"3389",},
{"lineNum":"  159","line":"  pages=$(printf \'%s\\n\' \"${out}\" \\","class":"lineNoCov","hits":"0",},
{"lineNum":"  160","line":"    | sed -n \'s/^Pages occupied by compressor: *\\([0-9]*\\)\\..*$/\\1/p\')"},
{"lineNum":"  161","line":"  [[ -z ${pages} ]] && { printf \'0\\n\'; return 0; }","class":"lineCov","hits":"1","order":"3392",},
{"lineNum":"  162","line":"  # vm_stat states its own page size, which differs between Intel and Apple"},
{"lineNum":"  163","line":"  # silicon; reading it back avoids assuming either."},
{"lineNum":"  164","line":"  page_size=$(printf \'%s\\n\' \"${out}\" \\","class":"lineNoCov","hits":"0",},
{"lineNum":"  165","line":"    | sed -n \'s/^Mach Virtual Memory Statistics: (page size of \\([0-9]*\\) bytes).*$/\\1/p\')"},
{"lineNum":"  166","line":"  [[ -z ${page_size} ]] && page_size=16384","class":"lineCov","hits":"1","order":"3396",},
{"lineNum":"  167","line":"  printf \'%s\\n\' $(( pages * page_size / 1048576 ))","class":"lineCov","hits":"1","order":"3397",},
{"lineNum":"  168","line":"}"},
{"lineNum":"  169","line":""},
{"lineNum":"  170","line":"########################################"},
{"lineNum":"  171","line":"# List the heaviest applications by resident plus compressed memory."},
{"lineNum":"  172","line":"# Globals:"},
{"lineNum":"  173","line":"#   TOP_CMD, TOP_OFFENDERS"},
{"lineNum":"  174","line":"# Outputs:"},
{"lineNum":"  175","line":"#   Writes \"<MB> <processes> <app>\" lines, heaviest first."},
{"lineNum":"  176","line":"########################################"},
{"lineNum":"  177","line":"read_top_offenders() {"},
{"lineNum":"  178","line":"  local prog","class":"lineCov","hits":"1","order":"3398",},
{"lineNum":"  179","line":"  prog=$(load_program offenders.awk)  # @embed offenders.awk","class":"lineCov","hits":"1","order":"3356",},
{"lineNum":"  180","line":"  ${TOP_CMD} 2>/dev/null \\","class":"lineCov","hits":"1","order":"3376",},
{"lineNum":"  181","line":"    | awk -v want=\"${TOP_OFFENDERS}\" \"${prog}\" \\"},
{"lineNum":"  182","line":"    | sort -rn \\"},
{"lineNum":"  183","line":"    | head -n \"${TOP_OFFENDERS}\""},
{"lineNum":"  184","line":"}"},
{"lineNum":"  185","line":""},
{"lineNum":"  186","line":"########################################"},
{"lineNum":"  187","line":"# Format the readings as a single human-readable line."},
{"lineNum":"  188","line":"# Arguments:"},
{"lineNum":"  189","line":"#   $1 - swap MB, $2 - free percent, $3 - compressor MB"},
{"lineNum":"  190","line":"# Outputs:"},
{"lineNum":"  191","line":"#   Writes the summary to stdout."},
{"lineNum":"  192","line":"########################################"},
{"lineNum":"  193","line":"format_readings() {"},
{"lineNum":"  194","line":"  printf \'swap %s MB · free %s%% · compressed %s MB\\n\' \"$1\" \"$2\" \"$3\"","class":"lineCov","hits":"1","order":"3402",},
{"lineNum":"  195","line":"}"},
{"lineNum":"  196","line":""},
{"lineNum":"  197","line":"########################################"},
{"lineNum":"  198","line":"# Deliver a message, as a notification or on stdout."},
{"lineNum":"  199","line":"# Globals:"},
{"lineNum":"  200","line":"#   NOTIFY_CMD, SCRIPT_NAME"},
{"lineNum":"  201","line":"# Arguments:"},
{"lineNum":"  202","line":"#   $1 - the message body"},
{"lineNum":"  203","line":"#   $2 - \"true\" to print instead of notifying"},
{"lineNum":"  204","line":"# Returns:"},
{"lineNum":"  205","line":"#   0 always — a failed notification must not mask the condition it describes."},
{"lineNum":"  206","line":"########################################"},
{"lineNum":"  207","line":"deliver() {"},
{"lineNum":"  208","line":"  local body=$1 print_only=$2","class":"lineCov","hits":"1","order":"3403",},
{"lineNum":"  209","line":"  if [[ ${print_only} == true ]]; then","class":"lineCov","hits":"1","order":"3404",},
{"lineNum":"  210","line":"    printf \'%s\\n\' \"${body}\"","class":"lineCov","hits":"1","order":"3405",},
{"lineNum":"  211","line":"    return 0","class":"lineCov","hits":"1","order":"3406",},
{"lineNum":"  212","line":"  fi"},
{"lineNum":"  213","line":"  # A notification is best-effort: under heavy memory pressure osascript is"},
{"lineNum":"  214","line":"  # itself liable to be slow or refused, and the log line is what survives."},
{"lineNum":"  215","line":"  ${NOTIFY_CMD} -e \"display notification \\\"${body//\\\"/}\\\" with title \\\"Memory pressure\\\"\" \\","class":"lineCov","hits":"1","order":"3407",},
{"lineNum":"  216","line":"    >/dev/null 2>&1 || log_error \"Could not post the notification: ${body}\""},
{"lineNum":"  217","line":"  return 0","class":"lineCov","hits":"1","order":"3390",},
{"lineNum":"  218","line":"}"},
{"lineNum":"  219","line":""},
{"lineNum":"  220","line":"########################################"},
{"lineNum":"  221","line":"# Main entry point."},
{"lineNum":"  222","line":"# Globals:"},
{"lineNum":"  223","line":"#   All configuration and command globals."},
{"lineNum":"  224","line":"# Arguments:"},
{"lineNum":"  225","line":"#   Command-line arguments."},
{"lineNum":"  226","line":"# Returns:"},
{"lineNum":"  227","line":"#   0 healthy or reported, 2 alert raised. Usage errors exit 1 via die_usage."},
{"lineNum":"  228","line":"########################################"},
{"lineNum":"  229","line":"main() {"},
{"lineNum":"  230","line":"  local opt_report=false opt_no_notify=false wanted_color=auto","class":"lineCov","hits":"1","order":"3378",},
{"lineNum":"  231","line":"  # CLI values are held separately from the config globals and applied after the"},
{"lineNum":"  232","line":"  # config is read. Writing them straight into the globals would let the config"},
{"lineNum":"  233","line":"  # file silently overwrite an explicit flag, since it is loaded afterwards."},
{"lineNum":"  234","line":"  local opt_swap=\"\" opt_pressure=\"\" opt_compressor=\"\"","class":"lineCov","hits":"1","order":"3408",},
{"lineNum":"  235","line":""},
{"lineNum":"  236","line":"  while [[ $# -gt 0 ]]; do","class":"lineCov","hits":"1","order":"3409",},
{"lineNum":"  237","line":"    case \"$1\" in","class":"lineCov","hits":"1","order":"3399",},
{"lineNum":"  238","line":"      -s|--swap-mb)"},
{"lineNum":"  239","line":"        require_option_value \"$1\" \"${2:-}\"","class":"lineCov","hits":"1","order":"3360",},
{"lineNum":"  240","line":"        opt_swap=$2","class":"lineCov","hits":"1","order":"3367",},
{"lineNum":"  241","line":"        shift 2","class":"lineCov","hits":"1","order":"3382",},
{"lineNum":"  242","line":"        ;;"},
{"lineNum":"  243","line":"      -p|--pressure)"},
{"lineNum":"  244","line":"        require_option_value \"$1\" \"${2:-}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  245","line":"        opt_pressure=$2","class":"lineNoCov","hits":"0",},
{"lineNum":"  246","line":"        shift 2","class":"lineNoCov","hits":"0",},
{"lineNum":"  247","line":"        ;;"},
{"lineNum":"  248","line":"      -c|--compressor)"},
{"lineNum":"  249","line":"        require_option_value \"$1\" \"${2:-}\"","class":"lineCov","hits":"1","order":"3411",},
{"lineNum":"  250","line":"        opt_compressor=$2","class":"lineCov","hits":"1","order":"3412",},
{"lineNum":"  251","line":"        shift 2","class":"lineCov","hits":"1","order":"3342",},
{"lineNum":"  252","line":"        ;;"},
{"lineNum":"  253","line":"      -r|--report)"},
{"lineNum":"  254","line":"        opt_report=true","class":"lineCov","hits":"1","order":"3344",},
{"lineNum":"  255","line":"        shift","class":"lineCov","hits":"1","order":"3368",},
{"lineNum":"  256","line":"        ;;"},
{"lineNum":"  257","line":"      -n|--no-notify)"},
{"lineNum":"  258","line":"        opt_no_notify=true","class":"lineCov","hits":"1","order":"3341",},
{"lineNum":"  259","line":"        shift","class":"lineCov","hits":"1","order":"3340",},
{"lineNum":"  260","line":"        ;;"},
{"lineNum":"  261","line":"      --no-color)"},
{"lineNum":"  262","line":"        wanted_color=never","class":"lineNoCov","hits":"0",},
{"lineNum":"  263","line":"        shift","class":"lineNoCov","hits":"0",},
{"lineNum":"  264","line":"        ;;"},
{"lineNum":"  265","line":"      -d|--debug)"},
{"lineNum":"  266","line":"        enable_debug_mode","class":"lineNoCov","hits":"0",},
{"lineNum":"  267","line":"        shift","class":"lineNoCov","hits":"0",},
{"lineNum":"  268","line":"        ;;"},
{"lineNum":"  269","line":"      -h|--help)"},
{"lineNum":"  270","line":"        setup_colors \"${wanted_color}\"","class":"lineCov","hits":"1","order":"3339",},
{"lineNum":"  271","line":"        show_usage","class":"lineCov","hits":"1","order":"3338",},
{"lineNum":"  272","line":"        return 0","class":"lineCov","hits":"1","order":"3347",},
{"lineNum":"  273","line":"        ;;"},
{"lineNum":"  274","line":"      *)"},
{"lineNum":"  275","line":"        setup_colors \"${wanted_color}\"","class":"lineCov","hits":"1","order":"3337",},
{"lineNum":"  276","line":"        die_usage \"Unknown option \'$1\'.\"","class":"lineCov","hits":"1","order":"3336",},
{"lineNum":"  277","line":"        ;;"},
{"lineNum":"  278","line":"    esac"},
{"lineNum":"  279","line":"  done"},
{"lineNum":"  280","line":""},
{"lineNum":"  281","line":"  setup_colors \"${wanted_color}\"","class":"lineCov","hits":"1","order":"3335",},
{"lineNum":"  282","line":"  load_optional_config","class":"lineCov","hits":"1","order":"3334",},
{"lineNum":"  283","line":"  # Explicit flags win over the config file."},
{"lineNum":"  284","line":"  [[ -n ${opt_swap} ]] && SWAP_WARN_MB=${opt_swap}","class":"lineCov","hits":"1","order":"3386",},
{"lineNum":"  285","line":"  [[ -n ${opt_pressure} ]] && PRESSURE_WARN_PERCENT=${opt_pressure}","class":"lineCov","hits":"1","order":"3388",},
{"lineNum":"  286","line":"  [[ -n ${opt_compressor} ]] && COMPRESSOR_WARN_MB=${opt_compressor}","class":"lineCov","hits":"1","order":"3372",},
{"lineNum":"  287","line":""},
{"lineNum":"  288","line":"  local swap_mb free_percent compressor_mb readings","class":"lineCov","hits":"1","order":"3391",},
{"lineNum":"  289","line":"  swap_mb=$(read_swap_mb)","class":"lineCov","hits":"1","order":"3379",},
{"lineNum":"  290","line":"  free_percent=$(read_free_percent)","class":"lineCov","hits":"1","order":"3383",},
{"lineNum":"  291","line":"  compressor_mb=$(read_compressor_mb)","class":"lineCov","hits":"1","order":"3393",},
{"lineNum":"  292","line":"  readings=$(format_readings \"${swap_mb}\" \"${free_percent}\" \"${compressor_mb}\")","class":"lineCov","hits":"1","order":"3333",},
{"lineNum":"  293","line":"  log_debug \"${readings}\"","class":"lineCov","hits":"1","order":"3395",},
{"lineNum":"  294","line":""},
{"lineNum":"  295","line":"  if [[ ${opt_report} == true ]]; then","class":"lineCov","hits":"1","order":"3370",},
{"lineNum":"  296","line":"    printf \'%s\\n\' \"${readings}\"","class":"lineCov","hits":"1","order":"3332",},
{"lineNum":"  297","line":"    read_top_offenders | while read -r mb procs app; do","class":"lineCov","hits":"1","order":"3331",},
{"lineNum":"  298","line":"      printf \'  %6s MB  %3s proc  %s\\n\' \"${mb}\" \"${procs}\" \"${app}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  299","line":"    done"},
{"lineNum":"  300","line":"    return 0","class":"lineCov","hits":"1","order":"3330",},
{"lineNum":"  301","line":"  fi"},
{"lineNum":"  302","line":""},
{"lineNum":"  303","line":"  local -a reasons=()","class":"lineCov","hits":"1","order":"3329",},
{"lineNum":"  304","line":"  (( swap_mb >= SWAP_WARN_MB )) && reasons+=(\"swap ${swap_mb} MB\")"},
{"lineNum":"  305","line":"  (( free_percent <= PRESSURE_WARN_PERCENT )) && reasons+=(\"only ${free_percent}% free\")"},
{"lineNum":"  306","line":"  (( compressor_mb >= COMPRESSOR_WARN_MB )) && reasons+=(\"${compressor_mb} MB compressed\")"},
{"lineNum":"  307","line":""},
{"lineNum":"  308","line":"  if (( ${#reasons[@]} == 0 )); then","class":"lineCov","hits":"1","order":"3328",},
{"lineNum":"  309","line":"    log_debug \"Healthy — no threshold crossed.\"","class":"lineCov","hits":"1","order":"3327",},
{"lineNum":"  310","line":"    return 0","class":"lineCov","hits":"1","order":"3326",},
{"lineNum":"  311","line":"  fi"},
{"lineNum":"  312","line":""},
{"lineNum":"  313","line":"  local offenders","class":"lineCov","hits":"1","order":"3325",},
{"lineNum":"  314","line":"  # Named in the alert because identifying the cause is the whole point: without"},
{"lineNum":"  315","line":"  # it the user is told the machine is filling up and left to guess by what."},
{"lineNum":"  316","line":"  offenders=$(read_top_offenders | awk \'{printf \"%s %.1f GB; \", $3, $1/1024}\' | sed \'s/; $//\')","class":"lineCov","hits":"1","order":"3357",},
{"lineNum":"  317","line":"  local body","class":"lineCov","hits":"1","order":"3365",},
{"lineNum":"  318","line":"  body=$(printf \'%s. Heaviest: %s\' \\","class":"lineNoCov","hits":"0",},
{"lineNum":"  319","line":"    \"$(IFS=\', \'; printf \'%s\' \"${reasons[*]}\")\" \"${offenders:-unknown}\")"},
{"lineNum":"  320","line":"  log_error \"${body}\"","class":"lineCov","hits":"1","order":"3361",},
{"lineNum":"  321","line":"  deliver \"${body}\" \"${opt_no_notify}\"","class":"lineCov","hits":"1","order":"3400",},
{"lineNum":"  322","line":"  # 2 rather than 1, matching dmarc-report: 1 is what cli.sh\'s die_usage exits for"},
{"lineNum":"  323","line":"  # a usage error, so a raised condition needs its own code to stay distinguishable."},
{"lineNum":"  324","line":"  return 2","class":"lineCov","hits":"1","order":"3324",},
{"lineNum":"  325","line":"}"},
{"lineNum":"  326","line":""},
{"lineNum":"  327","line":"# Guarded so the test harness can source this file and call individual functions;"},
{"lineNum":"  328","line":"# an unguarded call would run the whole tool the moment it is sourced."},
{"lineNum":"  329","line":"if [[ \"${BASH_SOURCE[0]}\" == \"${0}\" ]]; then","class":"lineCov","hits":"1","order":"3323",},
{"lineNum":"  330","line":"  main \"$@\"","class":"lineCov","hits":"1","order":"3322",},
{"lineNum":"  331","line":"fi"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "update-all-indexes.sh", "date" : "2026-08-20 20:56:25", "instrumented" : 102, "covered" : 91,};
var merged_data = [];
