var data = {lines:[
{"lineNum":"    1","line":"#!/usr/bin/env bash"},
{"lineNum":"    2","line":"#"},
{"lineNum":"    3","line":"# memory-pressure-alert.sh — warn while a Mac is filling up, not once it has"},
{"lineNum":"    4","line":"# already ground to a halt."},
{"lineNum":"    5","line":"#"},
{"lineNum":"    6","line":"# macOS does not run out of memory so much as it slides: pages compress, then"},
{"lineNum":"    7","line":"# swap grows, and the machine stays usable for days. Then free swap reaches zero"},
{"lineNum":"    8","line":"# and everything stalls at once — a load average in the hundreds, every process"},
{"lineNum":"    9","line":"# blocked on memory, and no single culprit visible in Activity Monitor."},
{"lineNum":"   10","line":"#"},
{"lineNum":"   11","line":"# Free memory is useless as a signal here, because macOS keeps almost none: it"},
{"lineNum":"   12","line":"# lends the rest to the file cache and reclaims it on demand, so \"free\" sits near"},
{"lineNum":"   13","line":"# zero on a perfectly healthy machine. The numbers that move are:"},
{"lineNum":"   14","line":"#"},
{"lineNum":"   15","line":"#   * swap in use — the leading indicator. It accrues over days of uptime and is"},
{"lineNum":"   16","line":"#     the only one that is near zero on a healthy machine, so a modest threshold"},
{"lineNum":"   17","line":"#     gives days of notice."},
{"lineNum":"   18","line":"#   * memory used — counted the way Activity Monitor and Stats count it, as"},
{"lineNum":"   19","line":"#     anonymous plus wired plus compressed pages, with the file cache and"},
{"lineNum":"   20","line":"#     purgeable pages excluded because the kernel can take those back at will."},
{"lineNum":"   21","line":"#     A naive total-minus-free reads ~99% at all times and says nothing."},
{"lineNum":"   22","line":"#   * the compressor — how much of that used memory the kernel is holding"},
{"lineNum":"   23","line":"#     squeezed in place instead of paging it out, since RAM is faster than disk."},
{"lineNum":"   24","line":"#     It is already counted inside \"memory used\", and a large figure is ordinary:"},
{"lineNum":"   25","line":"#     it measures how hard the machine is working to stay out of swap, not how"},
{"lineNum":"   26","line":"#     short of memory it is."},
{"lineNum":"   27","line":"#"},
{"lineNum":"   28","line":"# Memory and the compressor are read as shares of installed RAM rather than as"},
{"lineNum":"   29","line":"# sizes, so one set of thresholds fits an 8 GB laptop and a 128 GB desktop alike:"},
{"lineNum":"   30","line":"# what a healthy machine compresses grows with the RAM it has, so a fixed size in"},
{"lineNum":"   31","line":"# MB is either deafening on a small machine or silent on a large one. Swap stays a"},
{"lineNum":"   32","line":"# size, because what makes it dangerous does not scale with RAM — a healthy"},
{"lineNum":"   33","line":"# machine of any size sits near zero, and the pages it writes cost the same disk"},
{"lineNum":"   34","line":"# round trip whatever the total."},
{"lineNum":"   35","line":"#"},
{"lineNum":"   36","line":"# The alert names the heaviest applications, and it measures them by resident"},
{"lineNum":"   37","line":"# plus *compressed* memory. Resident size alone is actively misleading here: a"},
{"lineNum":"   38","line":"# browser holding tens of gigabytes across dozens of helper processes reports a"},
{"lineNum":"   39","line":"# few hundred megabytes each, so the real cause looks innocent while some idle"},
{"lineNum":"   40","line":"# background process looks like the problem. Totals are aggregated per"},
{"lineNum":"   41","line":"# application, since blame belongs to the app, not to its 56th renderer."},
{"lineNum":"   42","line":"#"},
{"lineNum":"   43","line":"# Every alert carries all three readings and marks the one that crossed, rather"},
{"lineNum":"   44","line":"# than reporting the crossed reading alone. None of them means anything by itself"},
{"lineNum":"   45","line":"# — 12 GB compressed is unremarkable on a machine whose swap is empty and alarming"},
{"lineNum":"   46","line":"# on one that has been paging for days — so the figure that tripped the threshold"},
{"lineNum":"   47","line":"# is of no use without the two that say how bad the situation actually is."},
{"lineNum":"   48","line":"#"},
{"lineNum":"   49","line":"# Designed to be run from a launchd agent every few minutes. It raises nothing"},
{"lineNum":"   50","line":"# and exits 0 while the machine is healthy, so it can be left running"},
{"lineNum":"   51","line":"# indefinitely."},
{"lineNum":"   52","line":"#"},
{"lineNum":"   53","line":"# Usage:"},
{"lineNum":"   54","line":"#   ./memory-pressure-alert.sh [OPTIONS]"},
{"lineNum":"   55","line":""},
{"lineNum":"   56","line":"set -o errexit","class":"lineCov","hits":"1","order":"3428",},
{"lineNum":"   57","line":"set -o nounset","class":"lineCov","hits":"1","order":"3406",},
{"lineNum":"   58","line":"set -o pipefail","class":"lineCov","hits":"1","order":"3401",},
{"lineNum":"   59","line":""},
{"lineNum":"   60","line":"# --- Shared Library ---"},
{"lineNum":"   61","line":"# shellcheck source=../../lib/colors.sh"},
{"lineNum":"   62","line":"source \"$(cd \"$(dirname \"$0\")\" && pwd -P)/../../lib/colors.sh\"","class":"lineCov","hits":"1","order":"3466",},
{"lineNum":"   63","line":"# @include ../../lib/colors.sh"},
{"lineNum":"   64","line":"# shellcheck source=../../lib/cli.sh"},
{"lineNum":"   65","line":"source \"$(cd \"$(dirname \"$0\")\" && pwd -P)/../../lib/cli.sh\"","class":"lineCov","hits":"1","order":"3434",},
{"lineNum":"   66","line":"# @include ../../lib/cli.sh"},
{"lineNum":"   67","line":"# shellcheck source=../../lib/core.sh"},
{"lineNum":"   68","line":"source \"$(cd \"$(dirname \"$0\")\" && pwd -P)/../../lib/core.sh\"","class":"lineCov","hits":"1","order":"3433",},
{"lineNum":"   69","line":"# @include ../../lib/core.sh"},
{"lineNum":"   70","line":"# shellcheck source=../../lib/config.sh"},
{"lineNum":"   71","line":"source \"$(cd \"$(dirname \"$0\")\" && pwd -P)/../../lib/config.sh\"","class":"lineCov","hits":"1","order":"3448",},
{"lineNum":"   72","line":"# @include ../../lib/config.sh"},
{"lineNum":"   73","line":"# shellcheck source=../../lib/program.sh"},
{"lineNum":"   74","line":"source \"$(cd \"$(dirname \"$0\")\" && pwd -P)/../../lib/program.sh\"","class":"lineCov","hits":"1","order":"3482",},
{"lineNum":"   75","line":"# @include ../../lib/program.sh"},
{"lineNum":"   76","line":""},
{"lineNum":"   77","line":"# --- Constants ---"},
{"lineNum":"   78","line":"# The three readings come from the environment when set. They are live kernel"},
{"lineNum":"   79","line":"# state that cannot be conjured on demand, so pointing them at fixtures is what"},
{"lineNum":"   80","line":"# makes the threshold logic and the reporting testable at all; unset, they run"},
{"lineNum":"   81","line":"# the real commands."},
{"lineNum":"   82","line":": \"${SWAPUSAGE_CMD:=sysctl -n vm.swapusage}\"","class":"lineCov","hits":"1","order":"3460",},
{"lineNum":"   83","line":": \"${MEMSIZE_CMD:=sysctl -n hw.memsize}\"","class":"lineCov","hits":"1","order":"3457",},
{"lineNum":"   84","line":": \"${VMSTAT_CMD:=vm_stat}\"","class":"lineCov","hits":"1","order":"3446",},
{"lineNum":"   85","line":": \"${PS_CMD:=ps -Ao rss=,comm=}\"","class":"lineCov","hits":"1","order":"3426",},
{"lineNum":"   86","line":": \"${TOP_CMD:=top -l 1 -stats command,mem,cmprs -n 400}\"","class":"lineCov","hits":"1","order":"3425",},
{"lineNum":"   87","line":": \"${NOTIFY_CMD:=osascript}\"","class":"lineCov","hits":"1","order":"3453",},
{"lineNum":"   88","line":"# The launchd installation targets are seams for the same reason: --install"},
{"lineNum":"   89","line":"# writes into the user\'s real agent directory and loads it for real, which a test"},
{"lineNum":"   90","line":"# must be able to redirect somewhere harmless."},
{"lineNum":"   91","line":": \"${LAUNCHCTL_CMD:=launchctl}\"","class":"lineCov","hits":"1","order":"3440",},
{"lineNum":"   92","line":": \"${LAUNCH_AGENTS_DIR:=${HOME}/Library/LaunchAgents}\"","class":"lineCov","hits":"1","order":"3463",},
{"lineNum":"   93","line":": \"${AGENT_LOG_DIR:=${HOME}/Library/Logs}\"","class":"lineCov","hits":"1","order":"3473",},
{"lineNum":"   94","line":"readonly SWAPUSAGE_CMD MEMSIZE_CMD VMSTAT_CMD PS_CMD TOP_CMD NOTIFY_CMD","class":"lineCov","hits":"1","order":"3485",},
{"lineNum":"   95","line":"readonly LAUNCHCTL_CMD LAUNCH_AGENTS_DIR AGENT_LOG_DIR","class":"lineCov","hits":"1","order":"3488",},
{"lineNum":"   96","line":""},
{"lineNum":"   97","line":"# How many applications the alert names. Enough to identify the cause without"},
{"lineNum":"   98","line":"# turning a notification into a list nobody reads on a lock screen."},
{"lineNum":"   99","line":"readonly TOP_OFFENDERS=3","class":"lineCov","hits":"1","order":"3475",},
{"lineNum":"  100","line":""},
{"lineNum":"  101","line":"# Marks the reading that crossed its threshold, so an alert carrying all three"},
{"lineNum":"  102","line":"# still says which of them it is about."},
{"lineNum":"  103","line":"readonly READING_MARK=\"⚠\"","class":"lineCov","hits":"1","order":"3429",},
{"lineNum":"  104","line":""},
{"lineNum":"  105","line":"# launchd identifies an agent by a reverse-DNS label, which is also the plist\'s"},
{"lineNum":"  106","line":"# basename, so the two can never drift apart."},
{"lineNum":"  107","line":"readonly AGENT_LABEL=\"si.merhar.memory-pressure-alert\"","class":"lineCov","hits":"1","order":"3477",},
{"lineNum":"  108","line":""},
{"lineNum":"  109","line":"# How often the installed agent runs. Swap accrues over days, so five minutes is"},
{"lineNum":"  110","line":"# far more often than the signal changes — chosen to keep the notice prompt"},
{"lineNum":"  111","line":"# without the check ever being noticeable."},
{"lineNum":"  112","line":"readonly DEFAULT_INTERVAL_SECONDS=300","class":"lineCov","hits":"1","order":"3493",},
{"lineNum":"  113","line":""},
{"lineNum":"  114","line":"# --- Configuration Defaults ---"},
{"lineNum":"  115","line":"# Swap first: on a healthy machine it is near zero, so any sustained growth is"},
{"lineNum":"  116","line":"# already news. Used memory is the confirming signal — it climbs through the day"},
{"lineNum":"  117","line":"# and sits high on a machine that is coping, so only a high threshold means"},
{"lineNum":"  118","line":"# trouble."},
{"lineNum":"  119","line":"SWAP_WARN_MB=2048","class":"lineCov","hits":"1","order":"3499",},
{"lineNum":"  120","line":"USED_WARN_PERCENT=85","class":"lineCov","hits":"1","order":"3443",},
{"lineNum":"  121","line":"COMPRESSOR_WARN_PERCENT=50","class":"lineCov","hits":"1","order":"3469",},
{"lineNum":"  122","line":""},
{"lineNum":"  123","line":"########################################"},
{"lineNum":"  124","line":"# Refuse a configuration key whose value cannot be carried over."},
{"lineNum":"  125","line":"#"},
{"lineNum":"  126","line":"# A key whose reading changed unit or sense cannot simply be renamed: the number a"},
{"lineNum":"  127","line":"# config file already holds would mean something else under the new name, and the"},
{"lineNum":"  128","line":"# author would go on believing a threshold is in force that is not. Saying so is the"},
{"lineNum":"  129","line":"# only way they find out, since a threshold that never fires looks like a quiet"},
{"lineNum":"  130","line":"# machine."},
{"lineNum":"  131","line":"# Globals:"},
{"lineNum":"  132","line":"#   Reads the variable named by $1."},
{"lineNum":"  133","line":"# Arguments:"},
{"lineNum":"  134","line":"#   $1 - the retired key, $2 - the key that replaces it, $3 - why the value cannot"},
{"lineNum":"  135","line":"#        carry over, $4 - the replacement\'s default"},
{"lineNum":"  136","line":"# Outputs:"},
{"lineNum":"  137","line":"#   Writes an error when the retired key is set."},
{"lineNum":"  138","line":"########################################"},
{"lineNum":"  139","line":"reject_retired_key() {"},
{"lineNum":"  140","line":"  [[ -n ${!1:-} ]] || return 0","class":"lineCov","hits":"1","order":"3415",},
{"lineNum":"  141","line":"  log_error \"$1 is no longer read — $3. Replace it with $2 (default $4).\"","class":"lineCov","hits":"1","order":"3533",},
{"lineNum":"  142","line":"}"},
{"lineNum":"  143","line":""},
{"lineNum":"  144","line":"########################################"},
{"lineNum":"  145","line":"# Reject a threshold that is not a whole percentage."},
{"lineNum":"  146","line":"#"},
{"lineNum":"  147","line":"# A percentage above 100 can never be reached, so it silently disables the reading it"},
{"lineNum":"  148","line":"# governs. That is the shape a stale size in MB takes once a threshold becomes a"},
{"lineNum":"  149","line":"# share of memory, and it is indistinguishable from a healthy machine."},
{"lineNum":"  150","line":"# Arguments:"},
{"lineNum":"  151","line":"#   $1 - the threshold\'s name, $2 - its value"},
{"lineNum":"  152","line":"# Returns:"},
{"lineNum":"  153","line":"#   0 when valid; exits 1 through die_usage otherwise."},
{"lineNum":"  154","line":"########################################"},
{"lineNum":"  155","line":"validate_percent() {"},
{"lineNum":"  156","line":"  if [[ $2 =~ ^[0-9]+$ ]] && (( $2 <= 100 )); then","class":"lineCov","hits":"1","order":"3409",},
{"lineNum":"  157","line":"    return 0","class":"lineCov","hits":"1","order":"3423",},
{"lineNum":"  158","line":"  fi"},
{"lineNum":"  159","line":"  die_usage \"$1 must be a whole percentage from 0 to 100, not \'$2\'.\"","class":"lineCov","hits":"1","order":"3421",},
{"lineNum":"  160","line":"}"},
{"lineNum":"  161","line":""},
{"lineNum":"  162","line":"########################################"},
{"lineNum":"  163","line":"# Print the usage text."},
{"lineNum":"  164","line":"# Outputs:"},
{"lineNum":"  165","line":"#   Writes the usage message to stdout."},
{"lineNum":"  166","line":"########################################"},
{"lineNum":"  167","line":"show_usage() {"},
{"lineNum":"  168","line":"  cat <<USAGE","class":"lineCov","hits":"1","order":"3420",},
{"lineNum":"  169","line":"${_C_BOLD}Usage:${_C_RESET} ${SCRIPT_NAME} [OPTIONS]"},
{"lineNum":"  170","line":""},
{"lineNum":"  171","line":"Warns while a Mac is filling up — growing swap and rising memory use — rather"},
{"lineNum":"  172","line":"than once it has already stalled. Names the heaviest applications by resident"},
{"lineNum":"  173","line":"plus compressed memory, aggregated per application."},
{"lineNum":"  174","line":""},
{"lineNum":"  175","line":"Raises nothing and exits 0 while healthy, so it suits a launchd agent."},
{"lineNum":"  176","line":""},
{"lineNum":"  177","line":"An alert reports all three readings and marks the one that crossed with ${READING_MARK}."},
{"lineNum":"  178","line":"Memory and the compressor are shares of installed RAM, so one threshold suits any"},
{"lineNum":"  179","line":"machine; --report adds the other form of every figure. See ${_C_BOLD}Readings${_C_RESET} below for what"},
{"lineNum":"  180","line":"each of them means."},
{"lineNum":"  181","line":""},
{"lineNum":"  182","line":"${_C_BOLD}Options:${_C_RESET}"},
{"lineNum":"  183","line":"  -s, --swap-mb MB        Warn at this much swap in use (default: ${SWAP_WARN_MB})"},
{"lineNum":"  184","line":"  -u, --used PERCENT      Warn at this much memory in use (default: ${USED_WARN_PERCENT})"},
{"lineNum":"  185","line":"  -c, --compressor PCT    Warn at this much of RAM held compressed (default: ${COMPRESSOR_WARN_PERCENT})"},
{"lineNum":"  186","line":"  -r, --report            Print the current readings and exit, whatever their values"},
{"lineNum":"  187","line":"  -n, --no-notify         Print to stdout instead of sending a notification"},
{"lineNum":"  188","line":"      --install           Install a launchd agent that runs this periodically"},
{"lineNum":"  189","line":"      --uninstall         Remove the launchd agent"},
{"lineNum":"  190","line":"  -i, --interval SECONDS  How often the agent runs, with --install (default: ${DEFAULT_INTERVAL_SECONDS})"},
{"lineNum":"  191","line":"      --no-color          Disable coloured output"},
{"lineNum":"  192","line":"  -d, --debug             Enable debug logging"},
{"lineNum":"  193","line":"  -h, --help              Show this help message"},
{"lineNum":"  194","line":""},
{"lineNum":"  195","line":"${_C_BOLD}Readings:${_C_RESET}"},
{"lineNum":"  196","line":"  used        How much of RAM is in use, counted the way Activity Monitor and"},
{"lineNum":"  197","line":"              Stats count it: anonymous, wired and compressed pages, less the"},
{"lineNum":"  198","line":"              file cache and purgeable pages the kernel reclaims on demand. A"},
{"lineNum":"  199","line":"              healthy Mac runs high here — 70% is unremarkable — because macOS"},
{"lineNum":"  200","line":"              lends every spare page to the cache rather than leaving it idle."},
{"lineNum":"  201","line":""},
{"lineNum":"  202","line":"  swap        How much has been written out to disk. The one reading that is"},
{"lineNum":"  203","line":"              near zero on a healthy Mac, and it accrues over days of uptime,"},
{"lineNum":"  204","line":"              so it gives the earliest warning. Once free swap reaches zero the"},
{"lineNum":"  205","line":"              machine stalls outright."},
{"lineNum":"  206","line":""},
{"lineNum":"  207","line":"  compressed  How much of RAM the kernel is holding squeezed in place instead of"},
{"lineNum":"  208","line":"              paging it out, since RAM is faster than disk. It is already part of"},
{"lineNum":"  209","line":"              \"used\", so it is not memory consumed on top of that figure, and a"},
{"lineNum":"  210","line":"              third of RAM is ordinary. Read it as how hard the machine is working"},
{"lineNum":"  211","line":"              to stay out of swap: high with empty swap means the compressor is"},
{"lineNum":"  212","line":"              coping, high alongside growing swap means it has run out of room to"},
{"lineNum":"  213","line":"              squeeze."},
{"lineNum":"  214","line":""},
{"lineNum":"  215","line":"${_C_BOLD}Exit Codes:${_C_RESET}"},
{"lineNum":"  216","line":"  0  Healthy, a report was printed, or the agent was installed or removed"},
{"lineNum":"  217","line":"  1  Usage error, or the agent could not be loaded"},
{"lineNum":"  218","line":"  2  A threshold was crossed and an alert was raised"},
{"lineNum":"  219","line":"USAGE"},
{"lineNum":"  220","line":"}"},
{"lineNum":"  221","line":""},
{"lineNum":"  222","line":"########################################"},
{"lineNum":"  223","line":"# Read swap in use, in whole MB."},
{"lineNum":"  224","line":"# Globals:"},
{"lineNum":"  225","line":"#   SWAPUSAGE_CMD"},
{"lineNum":"  226","line":"# Outputs:"},
{"lineNum":"  227","line":"#   Writes the integer MB to stdout, or 0 when the figure cannot be read."},
{"lineNum":"  228","line":"########################################"},
{"lineNum":"  229","line":"read_swap_mb() {"},
{"lineNum":"  230","line":"  local raw","class":"lineCov","hits":"1","order":"3430",},
{"lineNum":"  231","line":"  raw=$(${SWAPUSAGE_CMD} 2>/dev/null) || raw=\"\"","class":"lineCov","hits":"1","order":"3478",},
{"lineNum":"  232","line":"  # vm.swapusage reports \"total = 1024.00M used = 512.25M free = 511.75M\"."},
{"lineNum":"  233","line":"  # Sizes carry an M suffix in every macOS release that has this sysctl, so the"},
{"lineNum":"  234","line":"  # suffix is stripped rather than interpreted."},
{"lineNum":"  235","line":"  local used","class":"lineCov","hits":"1","order":"3449",},
{"lineNum":"  236","line":"  used=$(printf \'%s\\n\' \"${raw}\" | sed -n \'s/.*used = \\([0-9.]*\\)M.*/\\1/p\')","class":"lineCov","hits":"1","order":"3417",},
{"lineNum":"  237","line":"  [[ -z ${used} ]] && { printf \'0\\n\'; return 0; }","class":"lineCov","hits":"1","order":"3480",},
{"lineNum":"  238","line":"  printf \'%.0f\\n\' \"${used}\"","class":"lineCov","hits":"1","order":"3441",},
{"lineNum":"  239","line":"}"},
{"lineNum":"  240","line":""},
{"lineNum":"  241","line":"########################################"},
{"lineNum":"  242","line":"# Read used memory, as a percentage of the total and in whole MB."},
{"lineNum":"  243","line":"#"},
{"lineNum":"  244","line":"# Counted the way Activity Monitor and Stats count it: anonymous, wired and"},
{"lineNum":"  245","line":"# compressed pages, with the file cache and purgeable pages subtracted because the"},
{"lineNum":"  246","line":"# kernel reclaims those on demand and they are not a shortage. A plain"},
{"lineNum":"  247","line":"# total-minus-free would read about 99% on any healthy Mac and never move."},
{"lineNum":"  248","line":"#"},
{"lineNum":"  249","line":"# Both forms come back from one call, and one vm_stat sample, so every figure"},
{"lineNum":"  250","line":"# describes the same instant — sampling them separately would let the parts"},
{"lineNum":"  251","line":"# disagree and push the total past 100%, or print a size that contradicts the"},
{"lineNum":"  252","line":"# percentage beside it."},
{"lineNum":"  253","line":"# Globals:"},
{"lineNum":"  254","line":"#   VMSTAT_CMD, MEMSIZE_CMD"},
{"lineNum":"  255","line":"# Outputs:"},
{"lineNum":"  256","line":"#   Writes \"<percentage> <MB>\" to stdout, or \"0 0\" when it cannot be read."},
{"lineNum":"  257","line":"########################################"},
{"lineNum":"  258","line":"read_used() {"},
{"lineNum":"  259","line":"  local out total","class":"lineCov","hits":"1","order":"3459",},
{"lineNum":"  260","line":"  out=$(${VMSTAT_CMD} 2>/dev/null) || out=\"\"","class":"lineCov","hits":"1","order":"3454",},
{"lineNum":"  261","line":"  total=$(${MEMSIZE_CMD} 2>/dev/null) || total=\"\"","class":"lineCov","hits":"1","order":"3444",},
{"lineNum":"  262","line":"  # A missing reading must not look like an emergency: this runs unattended, and a"},
{"lineNum":"  263","line":"  # false alarm every few minutes teaches the user to ignore the real one."},
{"lineNum":"  264","line":"  [[ ${total} =~ ^[0-9]+$ ]] && (( total > 0 )) || { printf \'0 0\\n\'; return 0; }","class":"lineCov","hits":"1","order":"3451",},
{"lineNum":"  265","line":""},
{"lineNum":"  266","line":"  local prog","class":"lineCov","hits":"1","order":"3416",},
{"lineNum":"  267","line":"  prog=$(load_program used-memory.awk)  # @embed used-memory.awk","class":"lineCov","hits":"1","order":"3413",},
{"lineNum":"  268","line":"  printf \'%s\\n\' \"${out}\" | awk -v total=\"${total}\" \"${prog}\"","class":"lineCov","hits":"1","order":"3437",},
{"lineNum":"  269","line":"}"},
{"lineNum":"  270","line":""},
{"lineNum":"  271","line":"########################################"},
{"lineNum":"  272","line":"# Read installed memory, in whole MB."},
{"lineNum":"  273","line":"#"},
{"lineNum":"  274","line":"# Wanted separately from the used reading because it is the denominator every"},
{"lineNum":"  275","line":"# other share is taken against, and because a size is only interpretable beside it."},
{"lineNum":"  276","line":"# Globals:"},
{"lineNum":"  277","line":"#   MEMSIZE_CMD"},
{"lineNum":"  278","line":"# Outputs:"},
{"lineNum":"  279","line":"#   Writes the integer MB to stdout, or 0 when it cannot be read."},
{"lineNum":"  280","line":"########################################"},
{"lineNum":"  281","line":"read_total_mb() {"},
{"lineNum":"  282","line":"  local total","class":"lineCov","hits":"1","order":"3411",},
{"lineNum":"  283","line":"  total=$(${MEMSIZE_CMD} 2>/dev/null) || total=\"\"","class":"lineCov","hits":"1","order":"3408",},
{"lineNum":"  284","line":"  [[ ${total} =~ ^[0-9]+$ ]] || { printf \'0\\n\'; return 0; }","class":"lineCov","hits":"1","order":"3515",},
{"lineNum":"  285","line":"  printf \'%s\\n\' $(( total / 1048576 ))","class":"lineCov","hits":"1","order":"3517",},
{"lineNum":"  286","line":"}"},
{"lineNum":"  287","line":""},
{"lineNum":"  288","line":"########################################"},
{"lineNum":"  289","line":"# Express a size as a percentage of installed memory."},
{"lineNum":"  290","line":"#"},
{"lineNum":"  291","line":"# Zero when the total is unknown, which keeps an unreadable machine looking healthy"},
{"lineNum":"  292","line":"# rather than raising an alarm nobody can act on every few minutes."},
{"lineNum":"  293","line":"# Arguments:"},
{"lineNum":"  294","line":"#   $1 - the size in MB, $2 - installed memory in MB"},
{"lineNum":"  295","line":"# Outputs:"},
{"lineNum":"  296","line":"#   Writes the integer percentage to stdout."},
{"lineNum":"  297","line":"########################################"},
{"lineNum":"  298","line":"percent_of_ram() {"},
{"lineNum":"  299","line":"  (( $2 > 0 )) || { printf \'0\\n\'; return 0; }","class":"lineCov","hits":"1","order":"3525",},
{"lineNum":"  300","line":"  printf \'%s\\n\' $(( $1 * 100 / $2 ))","class":"lineCov","hits":"1","order":"3407",},
{"lineNum":"  301","line":"}"},
{"lineNum":"  302","line":""},
{"lineNum":"  303","line":"########################################"},
{"lineNum":"  304","line":"# Read compressed memory, in whole MB."},
{"lineNum":"  305","line":"# Globals:"},
{"lineNum":"  306","line":"#   VMSTAT_CMD"},
{"lineNum":"  307","line":"# Outputs:"},
{"lineNum":"  308","line":"#   Writes the integer MB to stdout, or 0 when it cannot be read."},
{"lineNum":"  309","line":"########################################"},
{"lineNum":"  310","line":"read_compressor_mb() {"},
{"lineNum":"  311","line":"  local out pages page_size","class":"lineCov","hits":"1","order":"3404",},
{"lineNum":"  312","line":"  out=$(${VMSTAT_CMD} 2>/dev/null) || out=\"\"","class":"lineCov","hits":"1","order":"3400",},
{"lineNum":"  313","line":"  pages=$(printf \'%s\\n\' \"${out}\" | sed -n \'s/^Pages occupied by compressor: *\\([0-9]*\\)\\..*$/\\1/p\')","class":"lineCov","hits":"1","order":"3427",},
{"lineNum":"  314","line":"  [[ -z ${pages} ]] && { printf \'0\\n\'; return 0; }","class":"lineCov","hits":"1","order":"3405",},
{"lineNum":"  315","line":"  # vm_stat states its own page size, which differs between Intel and Apple"},
{"lineNum":"  316","line":"  # silicon; reading it back avoids assuming either."},
{"lineNum":"  317","line":"  page_size=$(printf \'%s\\n\' \"${out}\" | sed -n \'s/^Mach Virtual Memory Statistics: (page size of \\([0-9]*\\) bytes).*$/\\1/p\')","class":"lineCov","hits":"1","order":"3461",},
{"lineNum":"  318","line":"  [[ -z ${page_size} ]] && page_size=16384","class":"lineCov","hits":"1","order":"3458",},
{"lineNum":"  319","line":"  printf \'%s\\n\' $(( pages * page_size / 1048576 ))","class":"lineCov","hits":"1","order":"3465",},
{"lineNum":"  320","line":"}"},
{"lineNum":"  321","line":""},
{"lineNum":"  322","line":"########################################"},
{"lineNum":"  323","line":"# List the heaviest applications by resident plus compressed memory."},
{"lineNum":"  324","line":"# Globals:"},
{"lineNum":"  325","line":"#   TOP_CMD, TOP_OFFENDERS"},
{"lineNum":"  326","line":"# Outputs:"},
{"lineNum":"  327","line":"#   Writes \"<MB> <processes> <app>\" lines, heaviest first."},
{"lineNum":"  328","line":"########################################"},
{"lineNum":"  329","line":"read_top_offenders() {"},
{"lineNum":"  330","line":"  local prog","class":"lineCov","hits":"1","order":"3435",},
{"lineNum":"  331","line":"  prog=$(load_program offenders.awk)  # @embed offenders.awk","class":"lineCov","hits":"1","order":"3483",},
{"lineNum":"  332","line":"  ${TOP_CMD} 2>/dev/null | awk -v want=\"${TOP_OFFENDERS}\" \"${prog}\" | sort -rn | head -n \"${TOP_OFFENDERS}\"","class":"lineCov","hits":"1","order":"3484",},
{"lineNum":"  333","line":"}"},
{"lineNum":"  334","line":""},
{"lineNum":"  335","line":"########################################"},
{"lineNum":"  336","line":"# Format one reading for display."},
{"lineNum":"  337","line":"#"},
{"lineNum":"  338","line":"# The leading figure is the one the reading\'s threshold is written in, so an alert"},
{"lineNum":"  339","line":"# speaks the same units as the config file it is tuned by. The other form follows in"},
{"lineNum":"  340","line":"# brackets only when there is room for it: a notification is read at a glance and on"},
{"lineNum":"  341","line":"# a lock screen, where a second number for each reading crowds out the application"},
{"lineNum":"  342","line":"# names that say what to close."},
{"lineNum":"  343","line":"# Arguments:"},
{"lineNum":"  344","line":"#   $1 - label, $2 - the figure its threshold is written in, $3 - the same reading"},
{"lineNum":"  345","line":"#        in the other form, $4 - \"true\" when it crossed its threshold,"},
{"lineNum":"  346","line":"#   $5 - \"true\" to include the other form"},
{"lineNum":"  347","line":"# Outputs:"},
{"lineNum":"  348","line":"#   Writes the formatted reading to stdout."},
{"lineNum":"  349","line":"########################################"},
{"lineNum":"  350","line":"format_reading() {"},
{"lineNum":"  351","line":"  local text=\"$1 $2\"","class":"lineCov","hits":"1","order":"3486",},
{"lineNum":"  352","line":"  [[ $5 == true ]] && text=\"${text} ($3)\"","class":"lineCov","hits":"1","order":"3489",},
{"lineNum":"  353","line":"  [[ $4 == true ]] && text=\"${READING_MARK} ${text}\"","class":"lineCov","hits":"1","order":"3476",},
{"lineNum":"  354","line":"  printf \'%s\\n\' \"${text}\"","class":"lineCov","hits":"1","order":"3491",},
{"lineNum":"  355","line":"}"},
{"lineNum":"  356","line":""},
{"lineNum":"  357","line":"########################################"},
{"lineNum":"  358","line":"# Deliver a message, as a notification or on stdout."},
{"lineNum":"  359","line":"# Globals:"},
{"lineNum":"  360","line":"#   NOTIFY_CMD, SCRIPT_NAME"},
{"lineNum":"  361","line":"# Arguments:"},
{"lineNum":"  362","line":"#   $1 - the message body"},
{"lineNum":"  363","line":"#   $2 - \"true\" to print instead of notifying"},
{"lineNum":"  364","line":"# Returns:"},
{"lineNum":"  365","line":"#   0 always — a failed notification must not mask the condition it describes."},
{"lineNum":"  366","line":"########################################"},
{"lineNum":"  367","line":"deliver() {"},
{"lineNum":"  368","line":"  local body=$1 print_only=$2","class":"lineCov","hits":"1","order":"3492",},
{"lineNum":"  369","line":"  if [[ ${print_only} == true ]]; then","class":"lineCov","hits":"1","order":"3494",},
{"lineNum":"  370","line":"    printf \'%s\\n\' \"${body}\"","class":"lineCov","hits":"1","order":"3495",},
{"lineNum":"  371","line":"    return 0","class":"lineCov","hits":"1","order":"3497",},
{"lineNum":"  372","line":"  fi"},
{"lineNum":"  373","line":"  # A notification is best-effort: under heavy memory pressure osascript is"},
{"lineNum":"  374","line":"  # itself liable to be slow or refused, and the log line is what survives."},
{"lineNum":"  375","line":"  ${NOTIFY_CMD} -e \"display notification \\\"${body//\\\"/}\\\" with title \\\"Memory pressure\\\"\" >/dev/null 2>&1 || log_error \"Could not post the notification: ${body}\"","class":"lineCov","hits":"1","order":"3471",},
{"lineNum":"  376","line":"  return 0","class":"lineCov","hits":"1","order":"3500",},
{"lineNum":"  377","line":"}"},
{"lineNum":"  378","line":""},
{"lineNum":"  379","line":"########################################"},
{"lineNum":"  380","line":"# Print the path of the launchd agent\'s plist."},
{"lineNum":"  381","line":"# Globals:"},
{"lineNum":"  382","line":"#   LAUNCH_AGENTS_DIR, AGENT_LABEL"},
{"lineNum":"  383","line":"# Outputs:"},
{"lineNum":"  384","line":"#   Writes the path to stdout."},
{"lineNum":"  385","line":"########################################"},
{"lineNum":"  386","line":"agent_plist_path() {"},
{"lineNum":"  387","line":"  printf \'%s/%s.plist\\n\' \"${LAUNCH_AGENTS_DIR}\" \"${AGENT_LABEL}\"","class":"lineCov","hits":"1","order":"3456",},
{"lineNum":"  388","line":"}"},
{"lineNum":"  389","line":""},
{"lineNum":"  390","line":"########################################"},
{"lineNum":"  391","line":"# Print the path launchd should invoke."},
{"lineNum":"  392","line":"#"},
{"lineNum":"  393","line":"# The directory is resolved physically but a symlinked file is left as it is: a"},
{"lineNum":"  394","line":"# Homebrew install is a symlink into the versioned Cellar, and an agent pointed at"},
{"lineNum":"  395","line":"# the stable symlink keeps working across upgrades, where one pointed into the"},
{"lineNum":"  396","line":"# Cellar breaks at the next version bump."},
{"lineNum":"  397","line":"# Outputs:"},
{"lineNum":"  398","line":"#   Writes the absolute path to stdout."},
{"lineNum":"  399","line":"########################################"},
{"lineNum":"  400","line":"self_path() {"},
{"lineNum":"  401","line":"  printf \'%s/%s\\n\' \"$(cd \"$(dirname \"$0\")\" && pwd -P)\" \"$(basename \"$0\")\"","class":"lineCov","hits":"1","order":"3502",},
{"lineNum":"  402","line":"}"},
{"lineNum":"  403","line":""},
{"lineNum":"  404","line":"########################################"},
{"lineNum":"  405","line":"# Escape a string for inclusion in XML character data."},
{"lineNum":"  406","line":"#"},
{"lineNum":"  407","line":"# Paths reach the plist from $0 and $HOME, so they are not under this script\'s control: an ampersand"},
{"lineNum":"  408","line":"# in a directory name is legal on macOS and would otherwise produce a plist that is not well-formed,"},
{"lineNum":"  409","line":"# which launchd rejects wholesale rather than reading around."},
{"lineNum":"  410","line":"# Arguments:"},
{"lineNum":"  411","line":"#   $1 - the string to escape"},
{"lineNum":"  412","line":"# Outputs:"},
{"lineNum":"  413","line":"#   Writes the escaped string to stdout."},
{"lineNum":"  414","line":"########################################"},
{"lineNum":"  415","line":"xml_escape() {"},
{"lineNum":"  416","line":"  # Ampersand first: escaping it after the others would corrupt the entities they introduce."},
{"lineNum":"  417","line":"  local out=${1//&/\\&amp;}","class":"lineCov","hits":"1","order":"3503",},
{"lineNum":"  418","line":"  out=${out//</\\&lt;}","class":"lineCov","hits":"1","order":"3504",},
{"lineNum":"  419","line":"  printf \'%s\\n\' \"${out//>/\\&gt;}\"","class":"lineCov","hits":"1","order":"3505",},
{"lineNum":"  420","line":"}"},
{"lineNum":"  421","line":""},
{"lineNum":"  422","line":"########################################"},
{"lineNum":"  423","line":"# Render the launchd agent plist."},
{"lineNum":"  424","line":"#"},
{"lineNum":"  425","line":"# Thresholds are deliberately not passed as arguments: the agent reads the config"},
{"lineNum":"  426","line":"# file like any other invocation, so tuning one is editing that file rather than"},
{"lineNum":"  427","line":"# rewriting and reloading an agent. Output is redirected to a log file because a"},
{"lineNum":"  428","line":"# launchd agent\'s stdout and stderr are otherwise discarded, which leaves \"it"},
{"lineNum":"  429","line":"# never warned me\" impossible to investigate."},
{"lineNum":"  430","line":"# Globals:"},
{"lineNum":"  431","line":"#   AGENT_LABEL, AGENT_LOG_DIR"},
{"lineNum":"  432","line":"# Arguments:"},
{"lineNum":"  433","line":"#   $1 - absolute path to the executable"},
{"lineNum":"  434","line":"#   $2 - interval between runs, in seconds"},
{"lineNum":"  435","line":"# Outputs:"},
{"lineNum":"  436","line":"#   Writes the plist XML to stdout."},
{"lineNum":"  437","line":"########################################"},
{"lineNum":"  438","line":"render_agent_plist() {"},
{"lineNum":"  439","line":"  local program interval log_path","class":"lineCov","hits":"1","order":"3402",},
{"lineNum":"  440","line":"  program=$(xml_escape \"$1\")","class":"lineCov","hits":"1","order":"3397",},
{"lineNum":"  441","line":"  interval=$2","class":"lineCov","hits":"1","order":"3396",},
{"lineNum":"  442","line":"  log_path=$(xml_escape \"${AGENT_LOG_DIR}/${AGENT_LABEL}.log\")","class":"lineCov","hits":"1","order":"3507",},
{"lineNum":"  443","line":"  cat <<PLIST","class":"lineCov","hits":"1","order":"3467",},
{"lineNum":"  444","line":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>"},
{"lineNum":"  445","line":"<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">"},
{"lineNum":"  446","line":"<plist version=\"1.0\">"},
{"lineNum":"  447","line":"<dict>"},
{"lineNum":"  448","line":"  <key>Label</key>             <string>${AGENT_LABEL}</string>"},
{"lineNum":"  449","line":"  <key>ProgramArguments</key>  <array><string>${program}</string></array>"},
{"lineNum":"  450","line":"  <key>StartInterval</key>     <integer>${interval}</integer>"},
{"lineNum":"  451","line":"  <key>RunAtLoad</key>         <true/>"},
{"lineNum":"  452","line":"  <key>StandardOutPath</key>   <string>${log_path}</string>"},
{"lineNum":"  453","line":"  <key>StandardErrorPath</key> <string>${log_path}</string>"},
{"lineNum":"  454","line":"</dict>"},
{"lineNum":"  455","line":"</plist>"},
{"lineNum":"  456","line":"PLIST"},
{"lineNum":"  457","line":"}"},
{"lineNum":"  458","line":""},
{"lineNum":"  459","line":"########################################"},
{"lineNum":"  460","line":"# Install the launchd agent and load it."},
{"lineNum":"  461","line":"#"},
{"lineNum":"  462","line":"# Idempotent, so reinstalling is how the interval is changed: an already-loaded"},
{"lineNum":"  463","line":"# agent keeps running with the plist it was loaded from, so the old one is"},
{"lineNum":"  464","line":"# unloaded before the new one is loaded rather than only rewritten on disk."},
{"lineNum":"  465","line":"# Globals:"},
{"lineNum":"  466","line":"#   LAUNCHCTL_CMD, LAUNCH_AGENTS_DIR, AGENT_LOG_DIR, AGENT_LABEL"},
{"lineNum":"  467","line":"# Arguments:"},
{"lineNum":"  468","line":"#   $1 - interval between runs, in seconds"},
{"lineNum":"  469","line":"# Returns:"},
{"lineNum":"  470","line":"#   0 on success, 1 if launchd refused to load the agent."},
{"lineNum":"  471","line":"########################################"},
{"lineNum":"  472","line":"install_agent() {"},
{"lineNum":"  473","line":"  local interval=$1 plist program","class":"lineCov","hits":"1","order":"3464",},
{"lineNum":"  474","line":"  plist=$(agent_plist_path)","class":"lineCov","hits":"1","order":"3474",},
{"lineNum":"  475","line":"  program=$(self_path)","class":"lineCov","hits":"1","order":"3436",},
{"lineNum":"  476","line":""},
{"lineNum":"  477","line":"  mkdir -p \"${LAUNCH_AGENTS_DIR}\" \"${AGENT_LOG_DIR}\"","class":"lineCov","hits":"1","order":"3508",},
{"lineNum":"  478","line":"  render_agent_plist \"${program}\" \"${interval}\" >\"${plist}\"","class":"lineCov","hits":"1","order":"3487",},
{"lineNum":"  479","line":""},
{"lineNum":"  480","line":"  # Absent on a first install, so this failing is the normal case and says"},
{"lineNum":"  481","line":"  # nothing about whether the load below will succeed."},
{"lineNum":"  482","line":"  ${LAUNCHCTL_CMD} unload \"${plist}\" >/dev/null 2>&1 || true","class":"lineCov","hits":"1","order":"3509",},
{"lineNum":"  483","line":""},
{"lineNum":"  484","line":"  if ! ${LAUNCHCTL_CMD} load \"${plist}\"; then","class":"lineCov","hits":"1","order":"3431",},
{"lineNum":"  485","line":"    log_error \"Wrote ${plist}, but launchctl refused to load it.\"","class":"lineCov","hits":"1","order":"3530",},
{"lineNum":"  486","line":"    return 1","class":"lineCov","hits":"1","order":"3540",},
{"lineNum":"  487","line":"  fi"},
{"lineNum":"  488","line":"  log_info \"Installed — runs ${program} every ${interval}s.\"","class":"lineCov","hits":"1","order":"3479",},
{"lineNum":"  489","line":"  log_info \"Agent: ${plist}\"","class":"lineCov","hits":"1","order":"3450",},
{"lineNum":"  490","line":"  log_info \"Log:   ${AGENT_LOG_DIR}/${AGENT_LABEL}.log\"","class":"lineCov","hits":"1","order":"3418",},
{"lineNum":"  491","line":"  return 0","class":"lineCov","hits":"1","order":"3481",},
{"lineNum":"  492","line":"}"},
{"lineNum":"  493","line":""},
{"lineNum":"  494","line":"########################################"},
{"lineNum":"  495","line":"# Unload the launchd agent and remove its plist."},
{"lineNum":"  496","line":"# Globals:"},
{"lineNum":"  497","line":"#   LAUNCHCTL_CMD"},
{"lineNum":"  498","line":"# Returns:"},
{"lineNum":"  499","line":"#   0 always — an agent that is already absent is the desired end state."},
{"lineNum":"  500","line":"########################################"},
{"lineNum":"  501","line":"uninstall_agent() {"},
{"lineNum":"  502","line":"  local plist","class":"lineCov","hits":"1","order":"3536",},
{"lineNum":"  503","line":"  plist=$(agent_plist_path)","class":"lineCov","hits":"1","order":"3539",},
{"lineNum":"  504","line":"  if [[ ! -f \"${plist}\" ]]; then","class":"lineCov","hits":"1","order":"3541",},
{"lineNum":"  505","line":"    log_info \"Not installed (no ${plist}).\"","class":"lineCov","hits":"1","order":"3542",},
{"lineNum":"  506","line":"    return 0","class":"lineCov","hits":"1","order":"3543",},
{"lineNum":"  507","line":"  fi"},
{"lineNum":"  508","line":"  # Unloaded before the plist goes, since launchctl needs the file to identify"},
{"lineNum":"  509","line":"  # what to stop; a stale in-memory job would otherwise keep running until logout."},
{"lineNum":"  510","line":"  ${LAUNCHCTL_CMD} unload \"${plist}\" >/dev/null 2>&1 || true","class":"lineCov","hits":"1","order":"3544",},
{"lineNum":"  511","line":"  rm -f \"${plist}\"","class":"lineCov","hits":"1","order":"3545",},
{"lineNum":"  512","line":"  log_info \"Uninstalled — removed ${plist}.\"","class":"lineCov","hits":"1","order":"3546",},
{"lineNum":"  513","line":"  return 0","class":"lineCov","hits":"1","order":"3534",},
{"lineNum":"  514","line":"}"},
{"lineNum":"  515","line":""},
{"lineNum":"  516","line":"########################################"},
{"lineNum":"  517","line":"# Main entry point."},
{"lineNum":"  518","line":"# Globals:"},
{"lineNum":"  519","line":"#   All configuration and command globals."},
{"lineNum":"  520","line":"# Arguments:"},
{"lineNum":"  521","line":"#   Command-line arguments."},
{"lineNum":"  522","line":"# Returns:"},
{"lineNum":"  523","line":"#   0 healthy or reported, 2 alert raised. Usage errors exit 1 via die_usage."},
{"lineNum":"  524","line":"########################################"},
{"lineNum":"  525","line":"main() {"},
{"lineNum":"  526","line":"  local opt_report=false opt_no_notify=false wanted_color=auto","class":"lineCov","hits":"1","order":"3510",},
{"lineNum":"  527","line":"  # CLI values are held separately from the config globals and applied after the"},
{"lineNum":"  528","line":"  # config is read. Writing them straight into the globals would let the config"},
{"lineNum":"  529","line":"  # file silently overwrite an explicit flag, since it is loaded afterwards."},
{"lineNum":"  530","line":"  local opt_swap=\"\" opt_used=\"\" opt_compressor=\"\"","class":"lineCov","hits":"1","order":"3511",},
{"lineNum":"  531","line":"  local opt_install=false opt_uninstall=false opt_interval=\"\"","class":"lineCov","hits":"1","order":"3512",},
{"lineNum":"  532","line":""},
{"lineNum":"  533","line":"  while [[ $# -gt 0 ]]; do","class":"lineCov","hits":"1","order":"3513",},
{"lineNum":"  534","line":"    case \"$1\" in","class":"lineCov","hits":"1","order":"3514",},
{"lineNum":"  535","line":"      -s|--swap-mb)"},
{"lineNum":"  536","line":"        require_option_value \"$1\" \"${2:-}\"","class":"lineCov","hits":"1","order":"3412",},
{"lineNum":"  537","line":"        opt_swap=$2","class":"lineCov","hits":"1","order":"3410",},
{"lineNum":"  538","line":"        shift 2","class":"lineCov","hits":"1","order":"3424",},
{"lineNum":"  539","line":"        ;;"},
{"lineNum":"  540","line":"      -u|--used)"},
{"lineNum":"  541","line":"        require_option_value \"$1\" \"${2:-}\"","class":"lineCov","hits":"1","order":"3516",},
{"lineNum":"  542","line":"        opt_used=$2","class":"lineCov","hits":"1","order":"3518",},
{"lineNum":"  543","line":"        shift 2","class":"lineCov","hits":"1","order":"3519",},
{"lineNum":"  544","line":"        ;;"},
{"lineNum":"  545","line":"      -c|--compressor)"},
{"lineNum":"  546","line":"        require_option_value \"$1\" \"${2:-}\"","class":"lineCov","hits":"1","order":"3506",},
{"lineNum":"  547","line":"        opt_compressor=$2","class":"lineCov","hits":"1","order":"3520",},
{"lineNum":"  548","line":"        shift 2","class":"lineCov","hits":"1","order":"3521",},
{"lineNum":"  549","line":"        ;;"},
{"lineNum":"  550","line":"      -r|--report)"},
{"lineNum":"  551","line":"        opt_report=true","class":"lineCov","hits":"1","order":"3522",},
{"lineNum":"  552","line":"        shift","class":"lineCov","hits":"1","order":"3523",},
{"lineNum":"  553","line":"        ;;"},
{"lineNum":"  554","line":"      -n|--no-notify)"},
{"lineNum":"  555","line":"        opt_no_notify=true","class":"lineCov","hits":"1","order":"3524",},
{"lineNum":"  556","line":"        shift","class":"lineCov","hits":"1","order":"3526",},
{"lineNum":"  557","line":"        ;;"},
{"lineNum":"  558","line":"      --install)"},
{"lineNum":"  559","line":"        opt_install=true","class":"lineCov","hits":"1","order":"3527",},
{"lineNum":"  560","line":"        shift","class":"lineCov","hits":"1","order":"3528",},
{"lineNum":"  561","line":"        ;;"},
{"lineNum":"  562","line":"      --uninstall)"},
{"lineNum":"  563","line":"        opt_uninstall=true","class":"lineCov","hits":"1","order":"3547",},
{"lineNum":"  564","line":"        shift","class":"lineCov","hits":"1","order":"3532",},
{"lineNum":"  565","line":"        ;;"},
{"lineNum":"  566","line":"      -i|--interval)"},
{"lineNum":"  567","line":"        require_option_value \"$1\" \"${2:-}\"","class":"lineCov","hits":"1","order":"3398",},
{"lineNum":"  568","line":"        opt_interval=$2","class":"lineCov","hits":"1","order":"3403",},
{"lineNum":"  569","line":"        shift 2","class":"lineCov","hits":"1","order":"3399",},
{"lineNum":"  570","line":"        ;;"},
{"lineNum":"  571","line":"      --no-color)"},
{"lineNum":"  572","line":"        wanted_color=never","class":"lineNoCov","hits":"0",},
{"lineNum":"  573","line":"        shift","class":"lineNoCov","hits":"0",},
{"lineNum":"  574","line":"        ;;"},
{"lineNum":"  575","line":"      -d|--debug)"},
{"lineNum":"  576","line":"        enable_debug_mode","class":"lineNoCov","hits":"0",},
{"lineNum":"  577","line":"        shift","class":"lineNoCov","hits":"0",},
{"lineNum":"  578","line":"        ;;"},
{"lineNum":"  579","line":"      -h|--help)"},
{"lineNum":"  580","line":"        setup_colors \"${wanted_color}\"","class":"lineCov","hits":"1","order":"3395",},
{"lineNum":"  581","line":"        show_usage","class":"lineCov","hits":"1","order":"3394",},
{"lineNum":"  582","line":"        return 0","class":"lineCov","hits":"1","order":"3432",},
{"lineNum":"  583","line":"        ;;"},
{"lineNum":"  584","line":"      *)"},
{"lineNum":"  585","line":"        setup_colors \"${wanted_color}\"","class":"lineCov","hits":"1","order":"3447",},
{"lineNum":"  586","line":"        die_usage \"Unknown option \'$1\'.\"","class":"lineCov","hits":"1","order":"3393",},
{"lineNum":"  587","line":"        ;;"},
{"lineNum":"  588","line":"    esac"},
{"lineNum":"  589","line":"  done"},
{"lineNum":"  590","line":""},
{"lineNum":"  591","line":"  setup_colors \"${wanted_color}\"","class":"lineCov","hits":"1","order":"3392",},
{"lineNum":"  592","line":""},
{"lineNum":"  593","line":"  # Handled before the config is read, because installing the agent does not"},
{"lineNum":"  594","line":"  # depend on any threshold: the agent reads the config itself at each run."},
{"lineNum":"  595","line":"  if [[ ${opt_install} == true && ${opt_uninstall} == true ]]; then","class":"lineCov","hits":"1","order":"3391",},
{"lineNum":"  596","line":"    die_usage \"--install and --uninstall cannot be combined.\"","class":"lineCov","hits":"1","order":"3535",},
{"lineNum":"  597","line":"  fi"},
{"lineNum":"  598","line":"  if [[ -n ${opt_interval} && ${opt_install} != true ]]; then","class":"lineCov","hits":"1","order":"3445",},
{"lineNum":"  599","line":"    die_usage \"--interval applies only to --install.\"","class":"lineCov","hits":"1","order":"3531",},
{"lineNum":"  600","line":"  fi"},
{"lineNum":"  601","line":"  if [[ ${opt_install} == true ]]; then","class":"lineCov","hits":"1","order":"3452",},
{"lineNum":"  602","line":"    local interval=${opt_interval:-${DEFAULT_INTERVAL_SECONDS}}","class":"lineCov","hits":"1","order":"3390",},
{"lineNum":"  603","line":"    # Rejected here rather than left to launchd, which accepts a nonsensical"},
{"lineNum":"  604","line":"    # StartInterval by ignoring the key and running the agent only at load."},
{"lineNum":"  605","line":"    [[ ${interval} =~ ^[1-9][0-9]*$ ]] || die_usage \"--interval must be a whole number of seconds above zero.\"","class":"lineCov","hits":"1","order":"3439",},
{"lineNum":"  606","line":"    if install_agent \"${interval}\"; then","class":"lineCov","hits":"1","order":"3462",},
{"lineNum":"  607","line":"      return 0","class":"lineCov","hits":"1","order":"3472",},
{"lineNum":"  608","line":"    fi"},
{"lineNum":"  609","line":"    return 1","class":"lineCov","hits":"1","order":"3538",},
{"lineNum":"  610","line":"  fi"},
{"lineNum":"  611","line":"  if [[ ${opt_uninstall} == true ]]; then","class":"lineCov","hits":"1","order":"3490",},
{"lineNum":"  612","line":"    uninstall_agent","class":"lineCov","hits":"1","order":"3529",},
{"lineNum":"  613","line":"    return 0","class":"lineCov","hits":"1","order":"3537",},
{"lineNum":"  614","line":"  fi"},
{"lineNum":"  615","line":""},
{"lineNum":"  616","line":"  load_optional_config","class":"lineCov","hits":"1","order":"3389",},
{"lineNum":"  617","line":""},
{"lineNum":"  618","line":"  reject_retired_key PRESSURE_WARN_PERCENT USED_WARN_PERCENT \"it governed memory free where the reading is memory used, so its sense is inverted\" \"${USED_WARN_PERCENT}\"","class":"lineCov","hits":"1","order":"3388",},
{"lineNum":"  619","line":"  reject_retired_key COMPRESSOR_WARN_MB COMPRESSOR_WARN_PERCENT \"the threshold is a share of installed RAM, so a size in MB reads as a percentage it can never reach\" \"${COMPRESSOR_WARN_PERCENT}\"","class":"lineCov","hits":"1","order":"3387",},
{"lineNum":"  620","line":""},
{"lineNum":"  621","line":"  # Explicit flags win over the config file."},
{"lineNum":"  622","line":"  [[ -n ${opt_swap} ]] && SWAP_WARN_MB=${opt_swap}","class":"lineCov","hits":"1","order":"3386",},
{"lineNum":"  623","line":"  [[ -n ${opt_used} ]] && USED_WARN_PERCENT=${opt_used}","class":"lineCov","hits":"1","order":"3385",},
{"lineNum":"  624","line":"  [[ -n ${opt_compressor} ]] && COMPRESSOR_WARN_PERCENT=${opt_compressor}","class":"lineCov","hits":"1","order":"3384",},
{"lineNum":"  625","line":""},
{"lineNum":"  626","line":"  # Checked after the merge so a bad value is caught wherever it came from, and before"},
{"lineNum":"  627","line":"  # any reading is taken so the complaint is about the setting rather than the machine."},
{"lineNum":"  628","line":"  validate_percent USED_WARN_PERCENT \"${USED_WARN_PERCENT}\"","class":"lineCov","hits":"1","order":"3496",},
{"lineNum":"  629","line":"  validate_percent COMPRESSOR_WARN_PERCENT \"${COMPRESSOR_WARN_PERCENT}\"","class":"lineCov","hits":"1","order":"3383",},
{"lineNum":"  630","line":""},
{"lineNum":"  631","line":"  local total_mb swap_mb used_percent used_mb compressor_mb","class":"lineCov","hits":"1","order":"3382",},
{"lineNum":"  632","line":"  total_mb=$(read_total_mb)","class":"lineCov","hits":"1","order":"3470",},
{"lineNum":"  633","line":"  swap_mb=$(read_swap_mb)","class":"lineCov","hits":"1","order":"3498",},
{"lineNum":"  634","line":"  read -r used_percent used_mb <<<\"$(read_used)\"","class":"lineCov","hits":"1","order":"3442",},
{"lineNum":"  635","line":"  compressor_mb=$(read_compressor_mb)","class":"lineCov","hits":"1","order":"3468",},
{"lineNum":"  636","line":""},
{"lineNum":"  637","line":"  local swap_percent compressor_percent","class":"lineCov","hits":"1","order":"3381",},
{"lineNum":"  638","line":"  swap_percent=$(percent_of_ram \"${swap_mb}\" \"${total_mb}\")","class":"lineCov","hits":"1","order":"3380",},
{"lineNum":"  639","line":"  compressor_percent=$(percent_of_ram \"${compressor_mb}\" \"${total_mb}\")","class":"lineCov","hits":"1","order":"3379",},
{"lineNum":"  640","line":""},
{"lineNum":"  641","line":"  # Decided before anything is printed, so a report and an alert mark the same"},
{"lineNum":"  642","line":"  # figures rather than each judging the readings for itself."},
{"lineNum":"  643","line":"  local used_hot=false swap_hot=false comp_hot=false","class":"lineCov","hits":"1","order":"3378",},
{"lineNum":"  644","line":"  (( used_percent >= USED_WARN_PERCENT )) && used_hot=true","class":"lineCov","hits":"1","order":"3455",},
{"lineNum":"  645","line":"  (( swap_mb >= SWAP_WARN_MB )) && swap_hot=true","class":"lineCov","hits":"1","order":"3377",},
{"lineNum":"  646","line":"  (( compressor_percent >= COMPRESSOR_WARN_PERCENT )) && comp_hot=true","class":"lineCov","hits":"1","order":"3376",},
{"lineNum":"  647","line":""},
{"lineNum":"  648","line":"  # A report is read deliberately and has the width for both forms of every figure;"},
{"lineNum":"  649","line":"  # an alert arrives unbidden in a notification and gets the one its threshold uses."},
{"lineNum":"  650","line":"  local both=${opt_report}","class":"lineCov","hits":"1","order":"3375",},
{"lineNum":"  651","line":"  local used_text swap_text comp_text","class":"lineCov","hits":"1","order":"3374",},
{"lineNum":"  652","line":"  used_text=$(format_reading used \"${used_percent}%\" \"${used_mb} MB\" \"${used_hot}\" \"${both}\")","class":"lineCov","hits":"1","order":"3373",},
{"lineNum":"  653","line":"  swap_text=$(format_reading swap \"${swap_mb} MB\" \"${swap_percent}%\" \"${swap_hot}\" \"${both}\")","class":"lineCov","hits":"1","order":"3372",},
{"lineNum":"  654","line":"  comp_text=$(format_reading compressed \"${compressor_percent}%\" \"${compressor_mb} MB\" \"${comp_hot}\" \"${both}\")","class":"lineCov","hits":"1","order":"3414",},
{"lineNum":"  655","line":"  local readings=\"${used_text} · ${swap_text} · ${comp_text}\"","class":"lineCov","hits":"1","order":"3438",},
{"lineNum":"  656","line":"  log_debug \"${readings}\"","class":"lineCov","hits":"1","order":"3371",},
{"lineNum":"  657","line":""},
{"lineNum":"  658","line":"  if [[ ${opt_report} == true ]]; then","class":"lineCov","hits":"1","order":"3501",},
{"lineNum":"  659","line":"    printf \'%s\\n\' \"${readings}\"","class":"lineCov","hits":"1","order":"3370",},
{"lineNum":"  660","line":"    read_top_offenders | while read -r mb procs app; do","class":"lineCov","hits":"1","order":"3369",},
{"lineNum":"  661","line":"      printf \'  %6s MB  %3s%%  %3s proc  %s\\n\' \"${mb}\" \"$(percent_of_ram \"${mb}\" \"${total_mb}\")\" \"${procs}\" \"${app}\"","class":"lineCov","hits":"1","order":"3368",},
{"lineNum":"  662","line":"    done"},
{"lineNum":"  663","line":"    return 0","class":"lineCov","hits":"1","order":"3367",},
{"lineNum":"  664","line":"  fi"},
{"lineNum":"  665","line":""},
{"lineNum":"  666","line":"  if [[ ${used_hot} == false && ${swap_hot} == false && ${comp_hot} == false ]]; then","class":"lineCov","hits":"1","order":"3366",},
{"lineNum":"  667","line":"    log_debug \"Healthy — no threshold crossed.\"","class":"lineCov","hits":"1","order":"3365",},
{"lineNum":"  668","line":"    return 0","class":"lineCov","hits":"1","order":"3364",},
{"lineNum":"  669","line":"  fi"},
{"lineNum":"  670","line":""},
{"lineNum":"  671","line":"  local offenders body","class":"lineCov","hits":"1","order":"3422",},
{"lineNum":"  672","line":"  # Named in the alert because identifying the cause is the whole point: without it"},
{"lineNum":"  673","line":"  # the user is told the machine is filling up and left to guess by what. Reported as"},
{"lineNum":"  674","line":"  # shares of RAM for the same reason the readings are: a size means nothing to a"},
{"lineNum":"  675","line":"  # reader who has to remember how much memory the machine has."},
{"lineNum":"  676","line":"  offenders=$(read_top_offenders | while read -r mb procs app; do","class":"lineNoCov","hits":"0",},
{"lineNum":"  677","line":"    printf \'%s %s%%; \' \"${app}\" \"$(percent_of_ram \"${mb}\" \"${total_mb}\")\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  678","line":"  done)"},
{"lineNum":"  679","line":"  offenders=${offenders%; }","class":"lineCov","hits":"1","order":"3363",},
{"lineNum":"  680","line":"  body=$(printf \'%s. Heaviest: %s\' \"${readings}\" \"${offenders:-unknown}\")","class":"lineCov","hits":"1","order":"3362",},
{"lineNum":"  681","line":"  log_error \"${body}\"","class":"lineCov","hits":"1","order":"3361",},
{"lineNum":"  682","line":"  deliver \"${body}\" \"${opt_no_notify}\"","class":"lineCov","hits":"1","order":"3419",},
{"lineNum":"  683","line":"  # 2 rather than 1, matching dmarc-report: 1 is what cli.sh\'s die_usage exits for"},
{"lineNum":"  684","line":"  # a usage error, so a raised condition needs its own code to stay distinguishable."},
{"lineNum":"  685","line":"  return 2","class":"lineCov","hits":"1","order":"3360",},
{"lineNum":"  686","line":"}"},
{"lineNum":"  687","line":""},
{"lineNum":"  688","line":"# Guarded so the test harness can source this file and call individual functions;"},
{"lineNum":"  689","line":"# an unguarded call would run the whole tool the moment it is sourced."},
{"lineNum":"  690","line":"if [[ \"${BASH_SOURCE[0]}\" == \"${0}\" ]]; then","class":"lineCov","hits":"1","order":"3359",},
{"lineNum":"  691","line":"  main \"$@\"","class":"lineCov","hits":"1","order":"3358",},
{"lineNum":"  692","line":"fi"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "update-all-indexes.sh", "date" : "2026-08-22 13:24:19", "instrumented" : 196, "covered" : 190,};
var merged_data = [];
