var data = {lines:[
{"lineNum":"    1","line":"#!/usr/bin/env bash"},
{"lineNum":"    2","line":"#"},
{"lineNum":"    3","line":"# Recursively compares two directories and reports differences in existence,"},
{"lineNum":"    4","line":"# size, timestamps, and checksums. Reports missing directories at the top level"},
{"lineNum":"    5","line":"# rather than enumerating all their contents."},
{"lineNum":"    6","line":"#"},
{"lineNum":"    7","line":"# Usage:"},
{"lineNum":"    8","line":"#   ./compare-dirs.sh [OPTIONS] <dir1> <dir2>"},
{"lineNum":"    9","line":""},
{"lineNum":"   10","line":"set -o errexit","class":"lineCov","hits":"1","order":"2596",},
{"lineNum":"   11","line":"set -o nounset","class":"lineCov","hits":"1","order":"2473",},
{"lineNum":"   12","line":"set -o pipefail","class":"lineCov","hits":"1","order":"2468",},
{"lineNum":"   13","line":""},
{"lineNum":"   14","line":"# --- Shared Library ---"},
{"lineNum":"   15","line":"# shellcheck source=../../lib/colors.sh"},
{"lineNum":"   16","line":"source \"$(cd \"$(dirname \"$0\")\" && pwd -P)/../../lib/colors.sh\"","class":"lineCov","hits":"1","order":"2520",},
{"lineNum":"   17","line":"# @include ../../lib/colors.sh"},
{"lineNum":"   18","line":"# shellcheck source=../../lib/platform.sh"},
{"lineNum":"   19","line":"source \"$(cd \"$(dirname \"$0\")\" && pwd -P)/../../lib/platform.sh\"","class":"lineCov","hits":"1","order":"2512",},
{"lineNum":"   20","line":"# @include ../../lib/platform.sh"},
{"lineNum":"   21","line":"# shellcheck source=../../lib/cli.sh"},
{"lineNum":"   22","line":"source \"$(cd \"$(dirname \"$0\")\" && pwd -P)/../../lib/cli.sh\"","class":"lineCov","hits":"1","order":"2505",},
{"lineNum":"   23","line":"# @include ../../lib/cli.sh"},
{"lineNum":"   24","line":"# shellcheck source=../../lib/core.sh"},
{"lineNum":"   25","line":"source \"$(cd \"$(dirname \"$0\")\" && pwd -P)/../../lib/core.sh\"","class":"lineCov","hits":"1","order":"2603",},
{"lineNum":"   26","line":"# @include ../../lib/core.sh"},
{"lineNum":"   27","line":""},
{"lineNum":"   28","line":"# --- Global State ---"},
{"lineNum":"   29","line":"_opt_timestamps=false","class":"lineCov","hits":"1","order":"2516",},
{"lineNum":"   30","line":"_opt_checksums=false","class":"lineCov","hits":"1","order":"2501",},
{"lineNum":"   31","line":"_opt_no_color=false","class":"lineCov","hits":"1","order":"2499",},
{"lineNum":"   32","line":"_opt_ignore_case=false","class":"lineCov","hits":"1","order":"2511",},
{"lineNum":"   33","line":"_opt_no_dotfiles=false","class":"lineCov","hits":"1","order":"2542",},
{"lineNum":"   34","line":"_opt_excludes=()"},
{"lineNum":"   35","line":"_opt_excludes_left=()"},
{"lineNum":"   36","line":"_opt_excludes_right=()"},
{"lineNum":"   37","line":"_dir1=\"\"","class":"lineCov","hits":"1","order":"2534",},
{"lineNum":"   38","line":"_dir2=\"\"","class":"lineCov","hits":"1","order":"2530",},
{"lineNum":"   39","line":"_count_left_only=0","class":"lineCov","hits":"1","order":"2528",},
{"lineNum":"   40","line":"_count_right_only=0","class":"lineCov","hits":"1","order":"2605",},
{"lineNum":"   41","line":"_count_differences=0","class":"lineCov","hits":"1","order":"2555",},
{"lineNum":"   42","line":""},
{"lineNum":"   43","line":"# --- Color Variables (set by setup_colors \"${_opt_no_color}\") ---"},
{"lineNum":"   44","line":""},
{"lineNum":"   45","line":"########################################"},
{"lineNum":"   46","line":"# Prints the script\'s usage instructions."},
{"lineNum":"   47","line":"# Globals:"},
{"lineNum":"   48","line":"#   SCRIPT_NAME"},
{"lineNum":"   49","line":"########################################"},
{"lineNum":"   50","line":"show_usage() {"},
{"lineNum":"   51","line":"  cat <<EOF","class":"lineCov","hits":"1","order":"2506",},
{"lineNum":"   52","line":"Usage: ${SCRIPT_NAME} [OPTIONS] <dir1> <dir2>"},
{"lineNum":"   53","line":""},
{"lineNum":"   54","line":"Recursively compare two directories and report differences."},
{"lineNum":"   55","line":""},
{"lineNum":"   56","line":"Options:"},
{"lineNum":"   57","line":"  -t, --timestamps         Also compare file modification times"},
{"lineNum":"   58","line":"  -c, --checksums          Also compare file checksums (sha256)"},
{"lineNum":"   59","line":"  -i, --ignore-case        Case-insensitive filename matching"},
{"lineNum":"   60","line":"  -d, --no-dotfiles        Skip hidden (dot) files and directories"},
{"lineNum":"   61","line":"  -x, --exclude PAT        Skip entries matching glob pattern (repeatable)"},
{"lineNum":"   62","line":"      --exclude-left PAT   Suppress LEFT-only reports for matches (repeatable)"},
{"lineNum":"   63","line":"      --exclude-right PAT  Suppress RIGHT-only reports for matches (repeatable)"},
{"lineNum":"   64","line":"  -n, --no-color           Disable colored output"},
{"lineNum":"   65","line":"  -h, --help               Show this help message"},
{"lineNum":"   66","line":""},
{"lineNum":"   67","line":"Output markers:"},
{"lineNum":"   68","line":"  ←  Item exists only in LEFT directory"},
{"lineNum":"   69","line":"  →  Item exists only in RIGHT directory"},
{"lineNum":"   70","line":"  ≠  Item differs between directories"},
{"lineNum":"   71","line":"  ⚡ Type mismatch (e.g., file vs directory)"},
{"lineNum":"   72","line":"EOF"},
{"lineNum":"   73","line":"}"},
{"lineNum":"   74","line":""},
{"lineNum":"   75","line":"########################################"},
{"lineNum":"   76","line":"# Parses command-line arguments into global option flags."},
{"lineNum":"   77","line":"# Supports long options and combined short options (e.g., -tc)."},
{"lineNum":"   78","line":"# Globals:"},
{"lineNum":"   79","line":"#   _opt_timestamps, _opt_checksums, _opt_no_color, _opt_ignore_case,"},
{"lineNum":"   80","line":"#   _opt_no_dotfiles, _opt_excludes, _opt_excludes_left, _opt_excludes_right,"},
{"lineNum":"   81","line":"#   _dir1, _dir2"},
{"lineNum":"   82","line":"# Arguments:"},
{"lineNum":"   83","line":"#   Command-line arguments passed to the script."},
{"lineNum":"   84","line":"########################################"},
{"lineNum":"   85","line":"parse_options() {"},
{"lineNum":"   86","line":"  local positional=()","class":"lineCov","hits":"1","order":"2541",},
{"lineNum":"   87","line":""},
{"lineNum":"   88","line":"  while [[ $# -gt 0 ]]; do","class":"lineCov","hits":"1","order":"2515",},
{"lineNum":"   89","line":"    case \"$1\" in","class":"lineCov","hits":"1","order":"2544",},
{"lineNum":"   90","line":"      -t|--timestamps)"},
{"lineNum":"   91","line":"        _opt_timestamps=true","class":"lineCov","hits":"1","order":"2509",},
{"lineNum":"   92","line":"        shift","class":"lineCov","hits":"1","order":"2543",},
{"lineNum":"   93","line":"        ;;"},
{"lineNum":"   94","line":"      -c|--checksums)"},
{"lineNum":"   95","line":"        _opt_checksums=true","class":"lineCov","hits":"1","order":"2521",},
{"lineNum":"   96","line":"        shift","class":"lineCov","hits":"1","order":"2537",},
{"lineNum":"   97","line":"        ;;"},
{"lineNum":"   98","line":"      -i|--ignore-case)"},
{"lineNum":"   99","line":"        _opt_ignore_case=true","class":"lineCov","hits":"1","order":"2524",},
{"lineNum":"  100","line":"        shift","class":"lineCov","hits":"1","order":"2547",},
{"lineNum":"  101","line":"        ;;"},
{"lineNum":"  102","line":"      -d|--no-dotfiles)"},
{"lineNum":"  103","line":"        _opt_no_dotfiles=true","class":"lineCov","hits":"1","order":"2585",},
{"lineNum":"  104","line":"        shift","class":"lineCov","hits":"1","order":"2549",},
{"lineNum":"  105","line":"        ;;"},
{"lineNum":"  106","line":"      -x|--exclude)"},
{"lineNum":"  107","line":"        _opt_excludes+=(\"$2\")","class":"lineCov","hits":"1","order":"2591",},
{"lineNum":"  108","line":"        shift 2","class":"lineCov","hits":"1","order":"2494",},
{"lineNum":"  109","line":"        ;;"},
{"lineNum":"  110","line":"      --exclude-left)"},
{"lineNum":"  111","line":"        _opt_excludes_left+=(\"$2\")","class":"lineCov","hits":"1","order":"2617",},
{"lineNum":"  112","line":"        shift 2","class":"lineCov","hits":"1","order":"2490",},
{"lineNum":"  113","line":"        ;;"},
{"lineNum":"  114","line":"      --exclude-right)"},
{"lineNum":"  115","line":"        _opt_excludes_right+=(\"$2\")","class":"lineCov","hits":"1","order":"2489",},
{"lineNum":"  116","line":"        shift 2","class":"lineCov","hits":"1","order":"2488",},
{"lineNum":"  117","line":"        ;;"},
{"lineNum":"  118","line":"      -n|--no-color)"},
{"lineNum":"  119","line":"        _opt_no_color=true","class":"lineCov","hits":"1","order":"2487",},
{"lineNum":"  120","line":"        shift","class":"lineCov","hits":"1","order":"2486",},
{"lineNum":"  121","line":"        ;;"},
{"lineNum":"  122","line":"      -h|--help)"},
{"lineNum":"  123","line":"        show_usage","class":"lineCov","hits":"1","order":"2485",},
{"lineNum":"  124","line":"        exit 0","class":"lineCov","hits":"1","order":"2484",},
{"lineNum":"  125","line":"        ;;"},
{"lineNum":"  126","line":"      --)"},
{"lineNum":"  127","line":"        shift","class":"lineCov","hits":"1","order":"2619",},
{"lineNum":"  128","line":"        positional+=(\"$@\")","class":"lineCov","hits":"1","order":"2621",},
{"lineNum":"  129","line":"        break","class":"lineCov","hits":"1","order":"2523",},
{"lineNum":"  130","line":"        ;;"},
{"lineNum":"  131","line":"      -*)"},
{"lineNum":"  132","line":"        local combined=\"${1#-}\"","class":"lineCov","hits":"1","order":"2481",},
{"lineNum":"  133","line":"        shift","class":"lineCov","hits":"1","order":"2479",},
{"lineNum":"  134","line":"        for (( i=0; i<${#combined}; i++ )); do","class":"lineCov","hits":"1","order":"2519",},
{"lineNum":"  135","line":"          case \"${combined:$i:1}\" in","class":"lineCov","hits":"1","order":"2477",},
{"lineNum":"  136","line":"            t) _opt_timestamps=true ;;","class":"lineCov","hits":"1","order":"2475",},
{"lineNum":"  137","line":"            c) _opt_checksums=true ;;","class":"lineCov","hits":"1","order":"2598",},
{"lineNum":"  138","line":"            i) _opt_ignore_case=true ;;","class":"lineCov","hits":"1","order":"2472",},
{"lineNum":"  139","line":"            d) _opt_no_dotfiles=true ;;","class":"lineCov","hits":"1","order":"2467",},
{"lineNum":"  140","line":"            x)"},
{"lineNum":"  141","line":"              if (( i + 1 < ${#combined} )); then","class":"lineCov","hits":"1","order":"2465",},
{"lineNum":"  142","line":"                die_usage \"-x must be last in a combined flag group (requires an argument)\"","class":"lineCov","hits":"1","order":"2463",},
{"lineNum":"  143","line":"              fi"},
{"lineNum":"  144","line":"              _opt_excludes+=(\"$1\")","class":"lineCov","hits":"1","order":"2462",},
{"lineNum":"  145","line":"              shift","class":"lineCov","hits":"1","order":"2539",},
{"lineNum":"  146","line":"              ;;"},
{"lineNum":"  147","line":"            n) _opt_no_color=true ;;","class":"lineNoCov","hits":"0",},
{"lineNum":"  148","line":"            h) show_usage; exit 0 ;;","class":"lineNoCov","hits":"0",},
{"lineNum":"  149","line":"            *)"},
{"lineNum":"  150","line":"              die_usage \"Unknown option: -${combined:$i:1}\"","class":"lineCov","hits":"1","order":"2508",},
{"lineNum":"  151","line":"              ;;"},
{"lineNum":"  152","line":"          esac"},
{"lineNum":"  153","line":"        done"},
{"lineNum":"  154","line":"        ;;"},
{"lineNum":"  155","line":"      *)"},
{"lineNum":"  156","line":"        positional+=(\"$1\")","class":"lineCov","hits":"1","order":"2517",},
{"lineNum":"  157","line":"        shift","class":"lineCov","hits":"1","order":"2503",},
{"lineNum":"  158","line":"        ;;"},
{"lineNum":"  159","line":"    esac"},
{"lineNum":"  160","line":"  done"},
{"lineNum":"  161","line":""},
{"lineNum":"  162","line":"  if [[ ${#positional[@]} -ne 2 ]]; then","class":"lineCov","hits":"1","order":"2551",},
{"lineNum":"  163","line":"    log_error \"Expected exactly 2 directory arguments, got ${#positional[@]}.\"","class":"lineCov","hits":"1","order":"2552",},
{"lineNum":"  164","line":"    show_usage","class":"lineCov","hits":"1","order":"2536",},
{"lineNum":"  165","line":"    exit 1","class":"lineCov","hits":"1","order":"2532",},
{"lineNum":"  166","line":"  fi"},
{"lineNum":"  167","line":""},
{"lineNum":"  168","line":"  _dir1=\"${positional[0]}\"","class":"lineCov","hits":"1","order":"2546",},
{"lineNum":"  169","line":"  _dir2=\"${positional[1]}\"","class":"lineCov","hits":"1","order":"2553",},
{"lineNum":"  170","line":""},
{"lineNum":"  171","line":"  if [[ ! -d \"${_dir1}\" ]]; then","class":"lineCov","hits":"1","order":"2554",},
{"lineNum":"  172","line":"    log_error \"\'${_dir1}\' is not a directory.\"","class":"lineCov","hits":"1","order":"2558",},
{"lineNum":"  173","line":"    exit 1","class":"lineCov","hits":"1","order":"2562",},
{"lineNum":"  174","line":"  fi"},
{"lineNum":"  175","line":"  if [[ ! -d \"${_dir2}\" ]]; then","class":"lineCov","hits":"1","order":"2565",},
{"lineNum":"  176","line":"    log_error \"\'${_dir2}\' is not a directory.\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  177","line":"    exit 1","class":"lineNoCov","hits":"0",},
{"lineNum":"  178","line":"  fi"},
{"lineNum":"  179","line":""},
{"lineNum":"  180","line":"  # Resolve to absolute paths for display"},
{"lineNum":"  181","line":"  _dir1=\"$(cd \"${_dir1}\" && pwd)\"","class":"lineCov","hits":"1","order":"2569",},
{"lineNum":"  182","line":"  _dir2=\"$(cd \"${_dir2}\" && pwd)\"","class":"lineCov","hits":"1","order":"2571",},
{"lineNum":"  183","line":"}"},
{"lineNum":"  184","line":""},
{"lineNum":"  185","line":"########################################"},
{"lineNum":"  186","line":"# Detects platform-specific tools and defines helper functions."},
{"lineNum":"  187","line":"# Defines get_size(), get_mtime(), and get_checksum() based on"},
{"lineNum":"  188","line":"# available system utilities."},
{"lineNum":"  189","line":"# Globals:"},
{"lineNum":"  190","line":"#   _opt_checksums"},
{"lineNum":"  191","line":""},
{"lineNum":"  192","line":"########################################"},
{"lineNum":"  193","line":"# Configures color variables based on terminal capability and user preference."},
{"lineNum":"  194","line":"# Globals:"},
{"lineNum":"  195","line":"#   _opt_no_color, _C_RED, _C_GREEN, _C_YELLOW, _C_CYAN, _C_BOLD, _C_RESET"},
{"lineNum":"  196","line":""},
{"lineNum":"  197","line":"########################################"},
{"lineNum":"  198","line":"# Formats an epoch timestamp as a human-readable date string."},
{"lineNum":"  199","line":"# Arguments:"},
{"lineNum":"  200","line":"#   ts: Unix epoch timestamp."},
{"lineNum":"  201","line":"# Outputs:"},
{"lineNum":"  202","line":"#   Prints formatted date to stdout."},
{"lineNum":"  203","line":"########################################"},
{"lineNum":"  204","line":"format_mtime() {"},
{"lineNum":"  205","line":"  local ts=\"$1\"","class":"lineCov","hits":"1","order":"2573",},
{"lineNum":"  206","line":"  if date -d \"@${ts}\" \'+%Y-%m-%d %H:%M:%S\' 2>/dev/null; then","class":"lineCov","hits":"1","order":"2574",},
{"lineNum":"  207","line":"    return","class":"lineCov","hits":"1","order":"2576",},
{"lineNum":"  208","line":"  fi"},
{"lineNum":"  209","line":"  # BSD date fallback"},
{"lineNum":"  210","line":"  date -r \"${ts}\" \'+%Y-%m-%d %H:%M:%S\'","class":"lineNoCov","hits":"0",},
{"lineNum":"  211","line":"}"},
{"lineNum":"  212","line":""},
{"lineNum":"  213","line":"########################################"},
{"lineNum":"  214","line":"# Formats a byte count with thousands separators."},
{"lineNum":"  215","line":"# Arguments:"},
{"lineNum":"  216","line":"#   size: File size in bytes."},
{"lineNum":"  217","line":"# Outputs:"},
{"lineNum":"  218","line":"#   Prints formatted size to stdout."},
{"lineNum":"  219","line":"########################################"},
{"lineNum":"  220","line":"format_size() {"},
{"lineNum":"  221","line":"  printf \"%\'d bytes\" \"$1\"","class":"lineCov","hits":"1","order":"2579",},
{"lineNum":"  222","line":"}"},
{"lineNum":"  223","line":""},
{"lineNum":"  224","line":"########################################"},
{"lineNum":"  225","line":"# Determines the filesystem type of a path."},
{"lineNum":"  226","line":"# Arguments:"},
{"lineNum":"  227","line":"#   path: Filesystem path to inspect."},
{"lineNum":"  228","line":"# Outputs:"},
{"lineNum":"  229","line":"#   Prints one of: symlink, directory, file, other."},
{"lineNum":"  230","line":"########################################"},
{"lineNum":"  231","line":"get_type() {"},
{"lineNum":"  232","line":"  local path=\"$1\"","class":"lineCov","hits":"1","order":"2581",},
{"lineNum":"  233","line":"  if [[ -L \"${path}\" ]]; then","class":"lineCov","hits":"1","order":"2584",},
{"lineNum":"  234","line":"    echo \"symlink\"","class":"lineCov","hits":"1","order":"2498",},
{"lineNum":"  235","line":"  elif [[ -d \"${path}\" ]]; then","class":"lineCov","hits":"1","order":"2496",},
{"lineNum":"  236","line":"    echo \"directory\"","class":"lineCov","hits":"1","order":"2588",},
{"lineNum":"  237","line":"  elif [[ -f \"${path}\" ]]; then","class":"lineCov","hits":"1","order":"2590",},
{"lineNum":"  238","line":"    echo \"file\"","class":"lineCov","hits":"1","order":"2492",},
{"lineNum":"  239","line":"  else"},
{"lineNum":"  240","line":"    echo \"other\"","class":"lineCov","hits":"1","order":"2594",},
{"lineNum":"  241","line":"  fi"},
{"lineNum":"  242","line":"}"},
{"lineNum":"  243","line":""},
{"lineNum":"  244","line":"# --- Output Helpers ---"},
{"lineNum":"  245","line":""},
{"lineNum":"  246","line":"########################################"},
{"lineNum":"  247","line":"# Reports an item found only in the left directory."},
{"lineNum":"  248","line":"# Globals:"},
{"lineNum":"  249","line":"#   _C_RED, _C_BOLD, _C_RESET, _count_left_only"},
{"lineNum":"  250","line":"# Arguments:"},
{"lineNum":"  251","line":"#   Relative path of the item."},
{"lineNum":"  252","line":"########################################"},
{"lineNum":"  253","line":"print_left_only() {"},
{"lineNum":"  254","line":"  echo \"${_C_RED}← LEFT only:  ${_C_BOLD}${1}${_C_RESET}\"","class":"lineCov","hits":"1","order":"2483",},
{"lineNum":"  255","line":"  (( _count_left_only++ )) || true","class":"lineCov","hits":"1","order":"2526",},
{"lineNum":"  256","line":"}"},
{"lineNum":"  257","line":""},
{"lineNum":"  258","line":"########################################"},
{"lineNum":"  259","line":"# Reports an item found only in the right directory."},
{"lineNum":"  260","line":"# Globals:"},
{"lineNum":"  261","line":"#   _C_GREEN, _C_BOLD, _C_RESET, _count_right_only"},
{"lineNum":"  262","line":"# Arguments:"},
{"lineNum":"  263","line":"#   Relative path of the item."},
{"lineNum":"  264","line":"########################################"},
{"lineNum":"  265","line":"print_right_only() {"},
{"lineNum":"  266","line":"  echo \"${_C_GREEN}→ RIGHT only: ${_C_BOLD}${1}${_C_RESET}\"","class":"lineCov","hits":"1","order":"2470",},
{"lineNum":"  267","line":"  (( _count_right_only++ )) || true","class":"lineCov","hits":"1","order":"2597",},
{"lineNum":"  268","line":"}"},
{"lineNum":"  269","line":""},
{"lineNum":"  270","line":"########################################"},
{"lineNum":"  271","line":"# Reports a file size difference between left and right."},
{"lineNum":"  272","line":"# Globals:"},
{"lineNum":"  273","line":"#   _C_YELLOW, _C_BOLD, _C_RESET, _count_differences"},
{"lineNum":"  274","line":"# Arguments:"},
{"lineNum":"  275","line":"#   path: Relative path of the file."},
{"lineNum":"  276","line":"#   size1: Size in left directory (bytes)."},
{"lineNum":"  277","line":"#   size2: Size in right directory (bytes)."},
{"lineNum":"  278","line":"########################################"},
{"lineNum":"  279","line":"print_size_diff() {"},
{"lineNum":"  280","line":"  local path=\"$1\" size1=\"$2\" size2=\"$3\"","class":"lineCov","hits":"1","order":"2600",},
{"lineNum":"  281","line":"  echo \"${_C_YELLOW}≠ Size differs: ${_C_BOLD}${path}${_C_RESET}\"","class":"lineCov","hits":"1","order":"2602",},
{"lineNum":"  282","line":"  echo \"    LEFT:  $(format_size \"${size1}\")\"","class":"lineCov","hits":"1","order":"2604",},
{"lineNum":"  283","line":"  echo \"    RIGHT: $(format_size \"${size2}\")\"","class":"lineCov","hits":"1","order":"2518",},
{"lineNum":"  284","line":"  (( _count_differences++ )) || true","class":"lineCov","hits":"1","order":"2504",},
{"lineNum":"  285","line":"}"},
{"lineNum":"  286","line":""},
{"lineNum":"  287","line":"########################################"},
{"lineNum":"  288","line":"# Reports a modification time difference between left and right."},
{"lineNum":"  289","line":"# Globals:"},
{"lineNum":"  290","line":"#   _C_YELLOW, _C_BOLD, _C_RESET, _count_differences"},
{"lineNum":"  291","line":"# Arguments:"},
{"lineNum":"  292","line":"#   path: Relative path of the file."},
{"lineNum":"  293","line":"#   mtime1: Epoch timestamp in left directory."},
{"lineNum":"  294","line":"#   mtime2: Epoch timestamp in right directory."},
{"lineNum":"  295","line":"########################################"},
{"lineNum":"  296","line":"print_mtime_diff() {"},
{"lineNum":"  297","line":"  local path=\"$1\" mtime1=\"$2\" mtime2=\"$3\"","class":"lineCov","hits":"1","order":"2606",},
{"lineNum":"  298","line":"  echo \"${_C_YELLOW}≠ Mtime differs: ${_C_BOLD}${path}${_C_RESET}\"","class":"lineCov","hits":"1","order":"2556",},
{"lineNum":"  299","line":"  echo \"    LEFT:  $(format_mtime \"${mtime1}\")\"","class":"lineCov","hits":"1","order":"2560",},
{"lineNum":"  300","line":"  echo \"    RIGHT: $(format_mtime \"${mtime2}\")\"","class":"lineCov","hits":"1","order":"2563",},
{"lineNum":"  301","line":"  (( _count_differences++ )) || true","class":"lineCov","hits":"1","order":"2607",},
{"lineNum":"  302","line":"}"},
{"lineNum":"  303","line":""},
{"lineNum":"  304","line":"########################################"},
{"lineNum":"  305","line":"# Reports a checksum difference between left and right."},
{"lineNum":"  306","line":"# Globals:"},
{"lineNum":"  307","line":"#   _C_YELLOW, _C_BOLD, _C_RESET, _count_differences"},
{"lineNum":"  308","line":"# Arguments:"},
{"lineNum":"  309","line":"#   Relative path of the file."},
{"lineNum":"  310","line":"########################################"},
{"lineNum":"  311","line":"print_checksum_diff() {"},
{"lineNum":"  312","line":"  echo \"${_C_YELLOW}≠ Checksum differs: ${_C_BOLD}${1}${_C_RESET}\"","class":"lineCov","hits":"1","order":"2608",},
{"lineNum":"  313","line":"  (( _count_differences++ )) || true","class":"lineCov","hits":"1","order":"2609",},
{"lineNum":"  314","line":"}"},
{"lineNum":"  315","line":""},
{"lineNum":"  316","line":"########################################"},
{"lineNum":"  317","line":"# Reports a type mismatch (e.g., file vs directory)."},
{"lineNum":"  318","line":"# Globals:"},
{"lineNum":"  319","line":"#   _C_YELLOW, _C_BOLD, _C_RESET, _count_differences"},
{"lineNum":"  320","line":"# Arguments:"},
{"lineNum":"  321","line":"#   path: Relative path of the item."},
{"lineNum":"  322","line":"#   type1: Type in left directory."},
{"lineNum":"  323","line":"#   type2: Type in right directory."},
{"lineNum":"  324","line":"########################################"},
{"lineNum":"  325","line":"print_type_mismatch() {"},
{"lineNum":"  326","line":"  local path=\"$1\" type1=\"$2\" type2=\"$3\"","class":"lineCov","hits":"1","order":"2610",},
{"lineNum":"  327","line":"  echo \"${_C_YELLOW}⚡ Type mismatch: ${_C_BOLD}${path}${_C_RESET}\"","class":"lineCov","hits":"1","order":"2611",},
{"lineNum":"  328","line":"  echo \"    LEFT:  ${type1}\"","class":"lineCov","hits":"1","order":"2612",},
{"lineNum":"  329","line":"  echo \"    RIGHT: ${type2}\"","class":"lineCov","hits":"1","order":"2613",},
{"lineNum":"  330","line":"  (( _count_differences++ )) || true","class":"lineCov","hits":"1","order":"2614",},
{"lineNum":"  331","line":"}"},
{"lineNum":"  332","line":""},
{"lineNum":"  333","line":"########################################"},
{"lineNum":"  334","line":"# Reports a symlink target difference between left and right."},
{"lineNum":"  335","line":"# Globals:"},
{"lineNum":"  336","line":"#   _C_YELLOW, _C_BOLD, _C_RESET, _count_differences"},
{"lineNum":"  337","line":"# Arguments:"},
{"lineNum":"  338","line":"#   path: Relative path of the symlink."},
{"lineNum":"  339","line":"#   target1: Link target in left directory."},
{"lineNum":"  340","line":"#   target2: Link target in right directory."},
{"lineNum":"  341","line":"########################################"},
{"lineNum":"  342","line":"print_symlink_diff() {"},
{"lineNum":"  343","line":"  local path=\"$1\" target1=\"$2\" target2=\"$3\"","class":"lineCov","hits":"1","order":"2540",},
{"lineNum":"  344","line":"  echo \"${_C_YELLOW}≠ Symlink target differs: ${_C_BOLD}${path}${_C_RESET}\"","class":"lineCov","hits":"1","order":"2615",},
{"lineNum":"  345","line":"  echo \"    LEFT:  -> ${target1}\"","class":"lineCov","hits":"1","order":"2514",},
{"lineNum":"  346","line":"  echo \"    RIGHT: -> ${target2}\"","class":"lineCov","hits":"1","order":"2545",},
{"lineNum":"  347","line":"  (( _count_differences++ )) || true","class":"lineCov","hits":"1","order":"2616",},
{"lineNum":"  348","line":"}"},
{"lineNum":"  349","line":""},
{"lineNum":"  350","line":"########################################"},
{"lineNum":"  351","line":"# Tests whether a filename matches any of the given glob patterns."},
{"lineNum":"  352","line":"# Arguments:"},
{"lineNum":"  353","line":"#   name: The filename to test."},
{"lineNum":"  354","line":"#   ...: One or more glob patterns."},
{"lineNum":"  355","line":"# Returns:"},
{"lineNum":"  356","line":"#   0 if any pattern matches, 1 otherwise."},
{"lineNum":"  357","line":"########################################"},
{"lineNum":"  358","line":"matches_pattern() {"},
{"lineNum":"  359","line":"  local name=\"$1\"","class":"lineCov","hits":"1","order":"2582",},
{"lineNum":"  360","line":"  shift","class":"lineCov","hits":"1","order":"2586",},
{"lineNum":"  361","line":"  local pattern","class":"lineCov","hits":"1","order":"2548",},
{"lineNum":"  362","line":"  for pattern in \"$@\"; do","class":"lineCov","hits":"1","order":"2497",},
{"lineNum":"  363","line":"    # shellcheck disable=SC2254,SC2053"},
{"lineNum":"  364","line":"    if [[ \"${name}\" == ${pattern} ]]; then","class":"lineCov","hits":"1","order":"2592",},
{"lineNum":"  365","line":"      return 0","class":"lineCov","hits":"1","order":"2493",},
{"lineNum":"  366","line":"    fi"},
{"lineNum":"  367","line":"  done"},
{"lineNum":"  368","line":"  return 1","class":"lineCov","hits":"1","order":"2618",},
{"lineNum":"  369","line":"}"},
{"lineNum":"  370","line":""},
{"lineNum":"  371","line":"########################################"},
{"lineNum":"  372","line":"# Recursively compares two directory trees, printing differences."},
{"lineNum":"  373","line":"# Uses null-delimited I/O internally to handle arbitrary filenames."},
{"lineNum":"  374","line":"# Globals:"},
{"lineNum":"  375","line":"#   _opt_timestamps, _opt_checksums, _opt_ignore_case, _opt_no_dotfiles,"},
{"lineNum":"  376","line":"#   _opt_excludes, _opt_excludes_left, _opt_excludes_right,"},
{"lineNum":"  377","line":"#   _count_left_only, _count_right_only, _count_differences"},
{"lineNum":"  378","line":"# Arguments:"},
{"lineNum":"  379","line":"#   prefix: Relative path prefix for display (empty string for top level)."},
{"lineNum":"  380","line":"#   left:   Absolute path to the left directory being compared."},
{"lineNum":"  381","line":"#   right:  Absolute path to the right directory being compared."},
{"lineNum":"  382","line":"########################################"},
{"lineNum":"  383","line":"compare_dirs() {"},
{"lineNum":"  384","line":"  local prefix=\"$1\"","class":"lineCov","hits":"1","order":"2620",},
{"lineNum":"  385","line":"  local left=\"$2\"","class":"lineCov","hits":"1","order":"2622",},
{"lineNum":"  386","line":"  local right=\"$3\"","class":"lineCov","hits":"1","order":"2522",},
{"lineNum":"  387","line":""},
{"lineNum":"  388","line":"  # Build sorted lists of entries (null-delimited for filename safety)"},
{"lineNum":"  389","line":"  local -a left_sorted=()","class":"lineCov","hits":"1","order":"2480",},
{"lineNum":"  390","line":"  local -a right_sorted=()","class":"lineCov","hits":"1","order":"2478",},
{"lineNum":"  391","line":""},
{"lineNum":"  392","line":"  if [[ -d \"${left}\" ]]; then","class":"lineCov","hits":"1","order":"2476",},
{"lineNum":"  393","line":"    while IFS= read -r -d \'\' entry; do","class":"lineCov","hits":"1","order":"2474",},
{"lineNum":"  394","line":"      local base","class":"lineCov","hits":"1","order":"2599",},
{"lineNum":"  395","line":"      base=\"$(basename \"${entry}\")\"","class":"lineCov","hits":"1","order":"2471",},
{"lineNum":"  396","line":"      [[ \"${_opt_no_dotfiles}\" == true && \"${base}\" == .* ]] && continue","class":"lineCov","hits":"1","order":"2466",},
{"lineNum":"  397","line":"      [[ ${#_opt_excludes[@]} -gt 0 ]] && matches_pattern \"${base}\" \"${_opt_excludes[@]}\" && continue","class":"lineCov","hits":"1","order":"2461",},
{"lineNum":"  398","line":"      left_sorted+=(\"${base}\")","class":"lineCov","hits":"1","order":"2464",},
{"lineNum":"  399","line":"    done < <(find \"${left}\" -maxdepth 1 -mindepth 1 -print0 | sort -z)","class":"lineNoCov","hits":"0",},
{"lineNum":"  400","line":"  fi"},
{"lineNum":"  401","line":""},
{"lineNum":"  402","line":"  if [[ -d \"${right}\" ]]; then","class":"lineCov","hits":"1","order":"2538",},
{"lineNum":"  403","line":"    while IFS= read -r -d \'\' entry; do","class":"lineCov","hits":"1","order":"2460",},
{"lineNum":"  404","line":"      local base","class":"lineCov","hits":"1","order":"2513",},
{"lineNum":"  405","line":"      base=\"$(basename \"${entry}\")\"","class":"lineCov","hits":"1","order":"2500",},
{"lineNum":"  406","line":"      [[ \"${_opt_no_dotfiles}\" == true && \"${base}\" == .* ]] && continue","class":"lineCov","hits":"1","order":"2459",},
{"lineNum":"  407","line":"      [[ ${#_opt_excludes[@]} -gt 0 ]] && matches_pattern \"${base}\" \"${_opt_excludes[@]}\" && continue","class":"lineCov","hits":"1","order":"2507",},
{"lineNum":"  408","line":"      right_sorted+=(\"${base}\")","class":"lineCov","hits":"1","order":"2458",},
{"lineNum":"  409","line":"    done < <(find \"${right}\" -maxdepth 1 -mindepth 1 -print0 | sort -z)","class":"lineNoCov","hits":"0",},
{"lineNum":"  410","line":"  fi"},
{"lineNum":"  411","line":""},
{"lineNum":"  412","line":"  # Use associative arrays for O(1) set membership tests."},
{"lineNum":"  413","line":"  # Values store the original filename for path construction."},
{"lineNum":"  414","line":"  local -A left_set=()","class":"lineCov","hits":"1","order":"2502",},
{"lineNum":"  415","line":"  local -A right_set=()","class":"lineCov","hits":"1","order":"2457",},
{"lineNum":"  416","line":"  for e in \"${left_sorted[@]+\"${left_sorted[@]}\"}\"; do","class":"lineCov","hits":"1","order":"2456",},
{"lineNum":"  417","line":"    local norm=\"${e}\"","class":"lineCov","hits":"1","order":"2455",},
{"lineNum":"  418","line":"    [[ \"${_opt_ignore_case}\" == true ]] && norm=\"${e,,}\"","class":"lineCov","hits":"1","order":"2454",},
{"lineNum":"  419","line":"    left_set[\"${norm}\"]=\"${e}\"","class":"lineCov","hits":"1","order":"2550",},
{"lineNum":"  420","line":"  done"},
{"lineNum":"  421","line":"  for e in \"${right_sorted[@]+\"${right_sorted[@]}\"}\"; do","class":"lineCov","hits":"1","order":"2535",},
{"lineNum":"  422","line":"    local norm=\"${e}\"","class":"lineCov","hits":"1","order":"2531",},
{"lineNum":"  423","line":"    [[ \"${_opt_ignore_case}\" == true ]] && norm=\"${e,,}\"","class":"lineCov","hits":"1","order":"2453",},
{"lineNum":"  424","line":"    right_set[\"${norm}\"]=\"${e}\"","class":"lineCov","hits":"1","order":"2452",},
{"lineNum":"  425","line":"  done"},
{"lineNum":"  426","line":""},
{"lineNum":"  427","line":"  # Compute merged sorted unique list of normalized keys. Both sides accumulate into one array, which"},
{"lineNum":"  428","line":"  # the enclosing condition guarantees is non-empty, so its expansion needs no guarding."},
{"lineNum":"  429","line":"  local -a all_entries=()","class":"lineCov","hits":"1","order":"2557",},
{"lineNum":"  430","line":"  if [[ ${#left_sorted[@]} -gt 0 || ${#right_sorted[@]} -gt 0 ]]; then","class":"lineCov","hits":"1","order":"2561",},
{"lineNum":"  431","line":"    local -a norm_entries=()","class":"lineCov","hits":"1","order":"2451",},
{"lineNum":"  432","line":"    for e in \"${left_sorted[@]+\"${left_sorted[@]}\"}\"; do","class":"lineCov","hits":"1","order":"2564",},
{"lineNum":"  433","line":"      local n=\"${e}\"","class":"lineCov","hits":"1","order":"2566",},
{"lineNum":"  434","line":"      [[ \"${_opt_ignore_case}\" == true ]] && n=\"${e,,}\"","class":"lineCov","hits":"1","order":"2567",},
{"lineNum":"  435","line":"      norm_entries+=(\"${n}\")","class":"lineCov","hits":"1","order":"2450",},
{"lineNum":"  436","line":"    done"},
{"lineNum":"  437","line":"    for e in \"${right_sorted[@]+\"${right_sorted[@]}\"}\"; do","class":"lineCov","hits":"1","order":"2449",},
{"lineNum":"  438","line":"      local n=\"${e}\"","class":"lineCov","hits":"1","order":"2568",},
{"lineNum":"  439","line":"      [[ \"${_opt_ignore_case}\" == true ]] && n=\"${e,,}\"","class":"lineCov","hits":"1","order":"2570",},
{"lineNum":"  440","line":"      norm_entries+=(\"${n}\")","class":"lineCov","hits":"1","order":"2448",},
{"lineNum":"  441","line":"    done"},
{"lineNum":"  442","line":"    while IFS= read -r -d \'\' entry; do","class":"lineCov","hits":"1","order":"2447",},
{"lineNum":"  443","line":"      all_entries+=(\"${entry}\")","class":"lineCov","hits":"1","order":"2446",},
{"lineNum":"  444","line":"    done < <(printf \'%s\\0\' \"${norm_entries[@]}\" | sort -uz)","class":"lineNoCov","hits":"0",},
{"lineNum":"  445","line":"  fi"},
{"lineNum":"  446","line":""},
{"lineNum":"  447","line":"  for norm_entry in \"${all_entries[@]+\"${all_entries[@]}\"}\"; do","class":"lineCov","hits":"1","order":"2445",},
{"lineNum":"  448","line":"    local orig_left=\"${left_set[${norm_entry}]:-}\"","class":"lineCov","hits":"1","order":"2444",},
{"lineNum":"  449","line":"    local orig_right=\"${right_set[${norm_entry}]:-}\"","class":"lineCov","hits":"1","order":"2443",},
{"lineNum":"  450","line":""},
{"lineNum":"  451","line":"    # Use the left original name for display if available, otherwise right"},
{"lineNum":"  452","line":"    local display_name=\"${orig_left:-${orig_right}}\"","class":"lineCov","hits":"1","order":"2442",},
{"lineNum":"  453","line":"    local rel_path","class":"lineCov","hits":"1","order":"2441",},
{"lineNum":"  454","line":"    if [[ -n \"${prefix}\" ]]; then","class":"lineCov","hits":"1","order":"2440",},
{"lineNum":"  455","line":"      rel_path=\"${prefix}${display_name}\"","class":"lineCov","hits":"1","order":"2439",},
{"lineNum":"  456","line":"    else"},
{"lineNum":"  457","line":"      rel_path=\"${display_name}\"","class":"lineCov","hits":"1","order":"2438",},
{"lineNum":"  458","line":"    fi"},
{"lineNum":"  459","line":""},
{"lineNum":"  460","line":"    if [[ -n \"${orig_left}\" && -z \"${orig_right}\" ]]; then","class":"lineCov","hits":"1","order":"2437",},
{"lineNum":"  461","line":"      if [[ ${#_opt_excludes_left[@]} -gt 0 ]] && matches_pattern \"${display_name}\" \"${_opt_excludes_left[@]}\"; then","class":"lineCov","hits":"1","order":"2436",},
{"lineNum":"  462","line":"        continue","class":"lineCov","hits":"1","order":"2572",},
{"lineNum":"  463","line":"      fi"},
{"lineNum":"  464","line":"      local type_l","class":"lineCov","hits":"1","order":"2575",},
{"lineNum":"  465","line":"      type_l=\"$(get_type \"${left}/${orig_left}\")\"","class":"lineCov","hits":"1","order":"2435",},
{"lineNum":"  466","line":"      if [[ \"${type_l}\" == \"directory\" ]]; then","class":"lineCov","hits":"1","order":"2434",},
{"lineNum":"  467","line":"        print_left_only \"${rel_path}/\"","class":"lineCov","hits":"1","order":"2577",},
{"lineNum":"  468","line":"      else"},
{"lineNum":"  469","line":"        print_left_only \"${rel_path}\"","class":"lineCov","hits":"1","order":"2433",},
{"lineNum":"  470","line":"      fi"},
{"lineNum":"  471","line":""},
{"lineNum":"  472","line":"    elif [[ -z \"${orig_left}\" && -n \"${orig_right}\" ]]; then","class":"lineCov","hits":"1","order":"2432",},
{"lineNum":"  473","line":"      if [[ ${#_opt_excludes_right[@]} -gt 0 ]] && matches_pattern \"${display_name}\" \"${_opt_excludes_right[@]}\"; then","class":"lineCov","hits":"1","order":"2431",},
{"lineNum":"  474","line":"        continue","class":"lineCov","hits":"1","order":"2430",},
{"lineNum":"  475","line":"      fi"},
{"lineNum":"  476","line":"      local type_r","class":"lineCov","hits":"1","order":"2429",},
{"lineNum":"  477","line":"      type_r=\"$(get_type \"${right}/${orig_right}\")\"","class":"lineCov","hits":"1","order":"2428",},
{"lineNum":"  478","line":"      if [[ \"${type_r}\" == \"directory\" ]]; then","class":"lineCov","hits":"1","order":"2578",},
{"lineNum":"  479","line":"        print_right_only \"${rel_path}/\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  480","line":"      else"},
{"lineNum":"  481","line":"        print_right_only \"${rel_path}\"","class":"lineCov","hits":"1","order":"2427",},
{"lineNum":"  482","line":"      fi"},
{"lineNum":"  483","line":""},
{"lineNum":"  484","line":"    else"},
{"lineNum":"  485","line":"      # Present in both — compare"},
{"lineNum":"  486","line":"      local left_path=\"${left}/${orig_left}\"","class":"lineCov","hits":"1","order":"2426",},
{"lineNum":"  487","line":"      local right_path=\"${right}/${orig_right}\"","class":"lineCov","hits":"1","order":"2425",},
{"lineNum":"  488","line":"      local type_l type_r","class":"lineCov","hits":"1","order":"2424",},
{"lineNum":"  489","line":"      type_l=\"$(get_type \"${left_path}\")\"","class":"lineCov","hits":"1","order":"2580",},
{"lineNum":"  490","line":"      type_r=\"$(get_type \"${right_path}\")\"","class":"lineCov","hits":"1","order":"2583",},
{"lineNum":"  491","line":""},
{"lineNum":"  492","line":"      if [[ \"${type_l}\" != \"${type_r}\" ]]; then","class":"lineCov","hits":"1","order":"2495",},
{"lineNum":"  493","line":"        print_type_mismatch \"${rel_path}\" \"${type_l}\" \"${type_r}\"","class":"lineCov","hits":"1","order":"2587",},
{"lineNum":"  494","line":"      elif [[ \"${type_l}\" == \"directory\" ]]; then","class":"lineCov","hits":"1","order":"2589",},
{"lineNum":"  495","line":"        compare_dirs \"${rel_path}/\" \"${left_path}\" \"${right_path}\"","class":"lineCov","hits":"1","order":"2491",},
{"lineNum":"  496","line":"      elif [[ \"${type_l}\" == \"symlink\" ]]; then","class":"lineCov","hits":"1","order":"2423",},
{"lineNum":"  497","line":"        local target_l target_r","class":"lineCov","hits":"1","order":"2593",},
{"lineNum":"  498","line":"        target_l=\"$(readlink \"${left_path}\")\"","class":"lineCov","hits":"1","order":"2422",},
{"lineNum":"  499","line":"        target_r=\"$(readlink \"${right_path}\")\"","class":"lineCov","hits":"1","order":"2421",},
{"lineNum":"  500","line":"        if [[ \"${target_l}\" != \"${target_r}\" ]]; then","class":"lineCov","hits":"1","order":"2420",},
{"lineNum":"  501","line":"          print_symlink_diff \"${rel_path}\" \"${target_l}\" \"${target_r}\"","class":"lineCov","hits":"1","order":"2419",},
{"lineNum":"  502","line":"        fi"},
{"lineNum":"  503","line":"      elif [[ \"${type_l}\" == \"file\" ]]; then","class":"lineCov","hits":"1","order":"2418",},
{"lineNum":"  504","line":"        local size_l size_r","class":"lineCov","hits":"1","order":"2417",},
{"lineNum":"  505","line":"        size_l=\"$(stat_size \"${left_path}\")\"","class":"lineCov","hits":"1","order":"2416",},
{"lineNum":"  506","line":"        size_r=\"$(stat_size \"${right_path}\")\"","class":"lineCov","hits":"1","order":"2415",},
{"lineNum":"  507","line":""},
{"lineNum":"  508","line":"        if [[ \"${size_l}\" != \"${size_r}\" ]]; then","class":"lineCov","hits":"1","order":"2414",},
{"lineNum":"  509","line":"          print_size_diff \"${rel_path}\" \"${size_l}\" \"${size_r}\"","class":"lineCov","hits":"1","order":"2413",},
{"lineNum":"  510","line":"        elif [[ \"${_opt_checksums}\" == true ]]; then","class":"lineCov","hits":"1","order":"2412",},
{"lineNum":"  511","line":"          local cksum_l cksum_r","class":"lineCov","hits":"1","order":"2482",},
{"lineNum":"  512","line":"          cksum_l=\"$(file_checksum \"${left_path}\")\"","class":"lineCov","hits":"1","order":"2525",},
{"lineNum":"  513","line":"          cksum_r=\"$(file_checksum \"${right_path}\")\"","class":"lineCov","hits":"1","order":"2411",},
{"lineNum":"  514","line":"          if [[ \"${cksum_l}\" != \"${cksum_r}\" ]]; then","class":"lineCov","hits":"1","order":"2410",},
{"lineNum":"  515","line":"            print_checksum_diff \"${rel_path}\"","class":"lineCov","hits":"1","order":"2409",},
{"lineNum":"  516","line":"          fi"},
{"lineNum":"  517","line":"        fi"},
{"lineNum":"  518","line":""},
{"lineNum":"  519","line":"        if [[ \"${_opt_timestamps}\" == true ]]; then","class":"lineCov","hits":"1","order":"2408",},
{"lineNum":"  520","line":"          local mtime_l mtime_r","class":"lineCov","hits":"1","order":"2407",},
{"lineNum":"  521","line":"          mtime_l=\"$(stat_mtime \"${left_path}\")\"","class":"lineCov","hits":"1","order":"2406",},
{"lineNum":"  522","line":"          mtime_r=\"$(stat_mtime \"${right_path}\")\"","class":"lineCov","hits":"1","order":"2405",},
{"lineNum":"  523","line":"          if [[ \"${mtime_l}\" != \"${mtime_r}\" ]]; then","class":"lineCov","hits":"1","order":"2469",},
{"lineNum":"  524","line":"            print_mtime_diff \"${rel_path}\" \"${mtime_l}\" \"${mtime_r}\"","class":"lineCov","hits":"1","order":"2595",},
{"lineNum":"  525","line":"          fi"},
{"lineNum":"  526","line":"        fi"},
{"lineNum":"  527","line":"      fi"},
{"lineNum":"  528","line":"    fi"},
{"lineNum":"  529","line":"  done"},
{"lineNum":"  530","line":"}"},
{"lineNum":"  531","line":""},
{"lineNum":"  532","line":"########################################"},
{"lineNum":"  533","line":"# Main entry point."},
{"lineNum":"  534","line":"# Arguments:"},
{"lineNum":"  535","line":"#   Command-line arguments."},
{"lineNum":"  536","line":"########################################"},
{"lineNum":"  537","line":"main() {"},
{"lineNum":"  538","line":"  parse_options \"$@\"","class":"lineCov","hits":"1","order":"2601",},
{"lineNum":"  539","line":""},
{"lineNum":"  540","line":"  # Checked once, up front: without a checksum tool every comparison would fail one file at a time,"},
{"lineNum":"  541","line":"  # and the option promises something the machine cannot deliver."},
{"lineNum":"  542","line":"  if [[ \"${_opt_checksums}\" == true ]] && ! has_checksum_tool; then","class":"lineCov","hits":"1","order":"2404",},
{"lineNum":"  543","line":"    log_error \"No checksum tool found (sha256sum or shasum). Checksum comparison disabled.\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  544","line":"    _opt_checksums=false","class":"lineNoCov","hits":"0",},
{"lineNum":"  545","line":"  fi"},
{"lineNum":"  546","line":"  setup_colors \"${_opt_no_color}\"","class":"lineCov","hits":"1","order":"2510",},
{"lineNum":"  547","line":""},
{"lineNum":"  548","line":"  # Print header"},
{"lineNum":"  549","line":"  echo \"${_C_CYAN}Comparing:${_C_RESET}\"","class":"lineCov","hits":"1","order":"2403",},
{"lineNum":"  550","line":"  echo \"  LEFT:  ${_C_BOLD}${_dir1}${_C_RESET}\"","class":"lineCov","hits":"1","order":"2402",},
{"lineNum":"  551","line":"  echo \"  RIGHT: ${_C_BOLD}${_dir2}${_C_RESET}\"","class":"lineCov","hits":"1","order":"2533",},
{"lineNum":"  552","line":"  echo \"─────────────────────────────────\"","class":"lineCov","hits":"1","order":"2529",},
{"lineNum":"  553","line":"  echo \"\"","class":"lineCov","hits":"1","order":"2527",},
{"lineNum":"  554","line":""},
{"lineNum":"  555","line":"  # Run comparison"},
{"lineNum":"  556","line":"  compare_dirs \"\" \"${_dir1}\" \"${_dir2}\"","class":"lineCov","hits":"1","order":"2559",},
{"lineNum":"  557","line":""},
{"lineNum":"  558","line":"  # Print footer"},
{"lineNum":"  559","line":"  echo \"\"","class":"lineCov","hits":"1","order":"2401",},
{"lineNum":"  560","line":"  echo \"─────────────────────────────────\"","class":"lineCov","hits":"1","order":"2400",},
{"lineNum":"  561","line":"  local total=$(( _count_left_only + _count_right_only + _count_differences ))","class":"lineCov","hits":"1","order":"2399",},
{"lineNum":"  562","line":"  if [[ ${total} -eq 0 ]]; then","class":"lineCov","hits":"1","order":"2398",},
{"lineNum":"  563","line":"    echo \"${_C_GREEN}Directories are identical.${_C_RESET}\"","class":"lineCov","hits":"1","order":"2397",},
{"lineNum":"  564","line":"    exit 0","class":"lineCov","hits":"1","order":"2396",},
{"lineNum":"  565","line":"  else"},
{"lineNum":"  566","line":"    echo \"${_C_CYAN}Summary:${_C_RESET} ${_count_left_only} only in LEFT, ${_count_right_only} only in RIGHT, ${_count_differences} differences\"","class":"lineCov","hits":"1","order":"2395",},
{"lineNum":"  567","line":"    exit 1","class":"lineCov","hits":"1","order":"2394",},
{"lineNum":"  568","line":"  fi"},
{"lineNum":"  569","line":"}"},
{"lineNum":"  570","line":""},
{"lineNum":"  571","line":"# Only run when executed, not when sourced — the test suite sources this file to exercise its"},
{"lineNum":"  572","line":"# individual functions."},
{"lineNum":"  573","line":"if [[ \"${BASH_SOURCE[0]}\" == \"${0}\" ]]; then","class":"lineCov","hits":"1","order":"2393",},
{"lineNum":"  574","line":"  main \"$@\"","class":"lineCov","hits":"1","order":"2392",},
{"lineNum":"  575","line":"fi"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "update-all-tables.sh", "date" : "2026-08-17 09:23:58", "instrumented" : 242, "covered" : 231,};
var merged_data = [];
