var data = {lines:[
{"lineNum":"    1","line":"#!/usr/bin/env bash"},
{"lineNum":"    2","line":"#"},
{"lineNum":"    3","line":"# A script to create an incremental backup and then automatically prune old ones"},
{"lineNum":"    4","line":"# based on a retention policy defined in its configuration file."},
{"lineNum":"    5","line":""},
{"lineNum":"    6","line":"# Exit immediately if a command exits with a non-zero status."},
{"lineNum":"    7","line":"set -o errexit","class":"lineCov","hits":"1","order":"599",},
{"lineNum":"    8","line":"# Treat unset variables as an error when substituting."},
{"lineNum":"    9","line":"set -o nounset","class":"lineCov","hits":"1","order":"594",},
{"lineNum":"   10","line":"# Pipelines return the exit status of the last command to fail."},
{"lineNum":"   11","line":"set -o pipefail","class":"lineCov","hits":"1","order":"613",},
{"lineNum":"   12","line":""},
{"lineNum":"   13","line":"# --- Global Constants ---"},
{"lineNum":"   14","line":"readonly MDSTAT_CHECK_INTERVAL=300 # Seconds between /proc/mdstat checks","class":"lineCov","hits":"1","order":"603",},
{"lineNum":"   15","line":""},
{"lineNum":"   16","line":"# --- Shared Library ---"},
{"lineNum":"   17","line":"_LOG_QUIET=\"true\"","class":"lineCov","hits":"1","order":"606",},
{"lineNum":"   18","line":"# shellcheck source=../lib/common.sh"},
{"lineNum":"   19","line":"source \"$(cd \"$(dirname \"$0\")\" && pwd -P)/../lib/common.sh\"","class":"lineCov","hits":"1","order":"609",},
{"lineNum":"   20","line":"# @include ../lib/common.sh"},
{"lineNum":"   21","line":""},
{"lineNum":"   22","line":"#######################################"},
{"lineNum":"   23","line":"# Prints the script\'s usage instructions to stderr."},
{"lineNum":"   24","line":"# Globals:"},
{"lineNum":"   25","line":"#   SCRIPT_NAME"},
{"lineNum":"   26","line":"# Arguments:"},
{"lineNum":"   27","line":"#   None"},
{"lineNum":"   28","line":"#######################################"},
{"lineNum":"   29","line":"show_usage() {"},
{"lineNum":"   30","line":"  cat <<EOF","class":"lineCov","hits":"1","order":"596",},
{"lineNum":"   31","line":"Usage: ${SCRIPT_NAME} [OPTIONS]"},
{"lineNum":"   32","line":"Creates an incremental rsync backup and prunes old backups."},
{"lineNum":"   33","line":""},
{"lineNum":"   34","line":"All settings are read from a configuration file"},
{"lineNum":"   35","line":"(e.g., /etc/${SCRIPT_NAME}.conf)."},
{"lineNum":"   36","line":""},
{"lineNum":"   37","line":"Options:"},
{"lineNum":"   38","line":"  -d    Debug mode (enables verbose logging to stderr)"},
{"lineNum":"   39","line":"  -h    Show this help message"},
{"lineNum":"   40","line":"EOF"},
{"lineNum":"   41","line":"}"},
{"lineNum":"   42","line":""},
{"lineNum":"   43","line":"#######################################"},
{"lineNum":"   44","line":"# Parses command-line options."},
{"lineNum":"   45","line":"# Globals:"},
{"lineNum":"   46","line":"#   IS_DEBUG_MODE"},
{"lineNum":"   47","line":"# Arguments:"},
{"lineNum":"   48","line":"#   Command-line arguments passed to the script."},
{"lineNum":"   49","line":"#######################################"},
{"lineNum":"   50","line":"parse_options() {"},
{"lineNum":"   51","line":"  while getopts \":dh\" opt; do","class":"lineCov","hits":"1","order":"610",},
{"lineNum":"   52","line":"    case \"${opt}\" in","class":"lineCov","hits":"1","order":"611",},
{"lineNum":"   53","line":"      d) enable_debug_mode ;;","class":"lineCov","hits":"1","order":"604",},
{"lineNum":"   54","line":"      h)"},
{"lineNum":"   55","line":"        show_usage","class":"lineCov","hits":"1","order":"612",},
{"lineNum":"   56","line":"        exit 0","class":"lineCov","hits":"1","order":"608",},
{"lineNum":"   57","line":"        ;;"},
{"lineNum":"   58","line":"      *)"},
{"lineNum":"   59","line":"        log_error \"Invalid option: -${OPTARG}\"","class":"lineCov","hits":"1","order":"607",},
{"lineNum":"   60","line":"        show_usage","class":"lineCov","hits":"1","order":"597",},
{"lineNum":"   61","line":"        exit 1","class":"lineCov","hits":"1","order":"595",},
{"lineNum":"   62","line":"        ;;"},
{"lineNum":"   63","line":"    esac"},
{"lineNum":"   64","line":"  done"},
{"lineNum":"   65","line":"  shift $((OPTIND - 1))","class":"lineCov","hits":"1","order":"598",},
{"lineNum":"   66","line":""},
{"lineNum":"   67","line":"  if (( $# > 0 )); then","class":"lineCov","hits":"1","order":"600",},
{"lineNum":"   68","line":"    log_error \"Unexpected arguments: $*\"","class":"lineCov","hits":"1","order":"593",},
{"lineNum":"   69","line":"    show_usage","class":"lineCov","hits":"1","order":"601",},
{"lineNum":"   70","line":"    exit 1","class":"lineCov","hits":"1","order":"592",},
{"lineNum":"   71","line":"  fi"},
{"lineNum":"   72","line":"}"},
{"lineNum":"   73","line":""},
{"lineNum":"   74","line":"#######################################"},
{"lineNum":"   75","line":"# Performs an incremental backup using rsync."},
{"lineNum":"   76","line":"# Globals:"},
{"lineNum":"   77","line":"#   SOURCE_DIR, BACKUP_DIR, EXCLUDES"},
{"lineNum":"   78","line":"#######################################"},
{"lineNum":"   79","line":"run_backup() {"},
{"lineNum":"   80","line":"  log_info \"Starting backup...\"","class":"lineNoCov","hits":"0",},
{"lineNum":"   81","line":""},
{"lineNum":"   82","line":"  local datetime","class":"lineNoCov","hits":"0",},
{"lineNum":"   83","line":"  datetime=\"$(date \'+%Y-%m-%d_%H:%M:%S\')\"","class":"lineNoCov","hits":"0",},
{"lineNum":"   84","line":"  local backup_path=\"${BACKUP_DIR}/${datetime}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"   85","line":"  local latest_link=\"${BACKUP_DIR}/latest\"","class":"lineNoCov","hits":"0",},
{"lineNum":"   86","line":""},
{"lineNum":"   87","line":"  local rsync_excludes=()","class":"lineNoCov","hits":"0",},
{"lineNum":"   88","line":"  for pattern in \"${EXCLUDES[@]}\"; do","class":"lineNoCov","hits":"0",},
{"lineNum":"   89","line":"    rsync_excludes+=(\"--exclude=${pattern}\")","class":"lineNoCov","hits":"0",},
{"lineNum":"   90","line":"  done"},
{"lineNum":"   91","line":""},
{"lineNum":"   92","line":"  log_info \"Creating new backup at: ${backup_path}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"   93","line":"  mkdir -p \"${backup_path}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"   94","line":""},
{"lineNum":"   95","line":"  log_info \"Running rsync...\"","class":"lineNoCov","hits":"0",},
{"lineNum":"   96","line":"  local rsync_exit_code=0","class":"lineNoCov","hits":"0",},
{"lineNum":"   97","line":"  local rsync_opts=(-ax --delete)","class":"lineNoCov","hits":"0",},
{"lineNum":"   98","line":""},
{"lineNum":"   99","line":"  # Show progress when running interactively"},
{"lineNum":"  100","line":"  if [[ -t 1 ]]; then","class":"lineNoCov","hits":"0",},
{"lineNum":"  101","line":"    rsync_opts+=(--info=progress2)","class":"lineNoCov","hits":"0",},
{"lineNum":"  102","line":"  fi"},
{"lineNum":"  103","line":""},
{"lineNum":"  104","line":"  log_debug \"rsync command: rsync ${rsync_opts[*]} ${rsync_excludes[*]} ${SOURCE_DIR}/ --link-dest ${latest_link} ${backup_path}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  105","line":""},
{"lineNum":"  106","line":"  rsync \"${rsync_opts[@]}\" \\","class":"lineNoCov","hits":"0",},
{"lineNum":"  107","line":"    \"${rsync_excludes[@]}\" \\"},
{"lineNum":"  108","line":"    \"${SOURCE_DIR}/\" \\"},
{"lineNum":"  109","line":"    --link-dest \"${latest_link}\" \\"},
{"lineNum":"  110","line":"    \"${backup_path}\" || rsync_exit_code=$?"},
{"lineNum":"  111","line":""},
{"lineNum":"  112","line":"  if [[ ${rsync_exit_code} -eq 0 ]]; then","class":"lineNoCov","hits":"0",},
{"lineNum":"  113","line":"    log_info \"Rsync process completed successfully.\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  114","line":"  elif [[ ${rsync_exit_code} -eq 24 ]]; then","class":"lineNoCov","hits":"0",},
{"lineNum":"  115","line":"    # This non-fatal error means some files vanished during transfer."},
{"lineNum":"  116","line":"    # It\'s common for temp files and is safe to ignore."},
{"lineNum":"  117","line":"    log_info \"Rsync completed with a non-fatal warning (code 24): Some source files vanished during transfer.\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  118","line":"  else"},
{"lineNum":"  119","line":"    log_error \"Rsync failed with a critical error (code ${rsync_exit_code}).\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  120","line":"    exit \"${rsync_exit_code}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  121","line":"  fi"},
{"lineNum":"  122","line":""},
{"lineNum":"  123","line":"  log_info \"Updating the \'latest\' symbolic link.\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  124","line":"  ln -sfn \"${backup_path}\" \"${latest_link}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  125","line":""},
{"lineNum":"  126","line":"  log_info \"Backup operation completed.\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  127","line":"}"},
{"lineNum":"  128","line":""},
{"lineNum":"  129","line":"#######################################"},
{"lineNum":"  130","line":"# Automatically prunes old backups based on the retention policy."},
{"lineNum":"  131","line":"# Globals:"},
{"lineNum":"  132","line":"#   BACKUP_DIR, KEEP_BACKUPS"},
{"lineNum":"  133","line":"#######################################"},
{"lineNum":"  134","line":"run_prune() {"},
{"lineNum":"  135","line":"  log_info \"Starting automatic backup pruning for: ${BACKUP_DIR}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  136","line":""},
{"lineNum":"  137","line":"  mapfile -t backups < <(find \"${BACKUP_DIR}\" -maxdepth 1 -mindepth 1 -type d -name \'[0-9][0-9][0-9][0-9]-*\' | sort)","class":"lineNoCov","hits":"0",},
{"lineNum":"  138","line":"  local total_backups=${#backups[@]}","class":"lineNoCov","hits":"0",},
{"lineNum":"  139","line":"  log_debug \"Found ${total_backups} existing backup(s) in ${BACKUP_DIR}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  140","line":""},
{"lineNum":"  141","line":"  if (( total_backups <= KEEP_BACKUPS )); then","class":"lineNoCov","hits":"0",},
{"lineNum":"  142","line":"    log_info \"Total backups (${total_backups}) is not greater than the number to keep (${KEEP_BACKUPS}). No pruning needed.\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  143","line":"    return 0","class":"lineNoCov","hits":"0",},
{"lineNum":"  144","line":"  fi"},
{"lineNum":"  145","line":""},
{"lineNum":"  146","line":"  local delete_count=$((total_backups - KEEP_BACKUPS))","class":"lineNoCov","hits":"0",},
{"lineNum":"  147","line":"  local backups_to_delete=(\"${backups[@]:0:${delete_count}}\")","class":"lineNoCov","hits":"0",},
{"lineNum":"  148","line":""},
{"lineNum":"  149","line":"  log_info \"Found ${total_backups} backups. Deleting ${delete_count} oldest backup(s)...\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  150","line":"  for backup_to_delete in \"${backups_to_delete[@]}\"; do","class":"lineNoCov","hits":"0",},
{"lineNum":"  151","line":"    local backup_name","class":"lineNoCov","hits":"0",},
{"lineNum":"  152","line":"    backup_name=$(basename \"${backup_to_delete}\")","class":"lineNoCov","hits":"0",},
{"lineNum":"  153","line":"    log_info \"Deleting: ${backup_name}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  154","line":"    if ! rm -rf \"${backup_to_delete}\"; then","class":"lineNoCov","hits":"0",},
{"lineNum":"  155","line":"        log_error \"Failed to delete backup directory: ${backup_name}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  156","line":"    fi"},
{"lineNum":"  157","line":"  done"},
{"lineNum":"  158","line":""},
{"lineNum":"  159","line":"  log_info \"Pruning complete!\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  160","line":"}"},
{"lineNum":"  161","line":""},
{"lineNum":"  162","line":"#######################################"},
{"lineNum":"  163","line":"# Waits for any active RAID resync/check/rebuild operations to finish."},
{"lineNum":"  164","line":"# Polls /proc/mdstat at a regular interval. If /proc/mdstat does not"},
{"lineNum":"  165","line":"# exist (e.g., no RAID arrays on this system), returns immediately."},
{"lineNum":"  166","line":"# Globals:"},
{"lineNum":"  167","line":"#   MDSTAT_CHECK_INTERVAL"},
{"lineNum":"  168","line":"# Arguments:"},
{"lineNum":"  169","line":"#   None"},
{"lineNum":"  170","line":"#######################################"},
{"lineNum":"  171","line":"wait_for_raid() {"},
{"lineNum":"  172","line":"  if [[ ! -f /proc/mdstat ]]; then","class":"lineNoCov","hits":"0",},
{"lineNum":"  173","line":"    log_debug \"/proc/mdstat not found, skipping RAID check.\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  174","line":"    return","class":"lineNoCov","hits":"0",},
{"lineNum":"  175","line":"  fi"},
{"lineNum":"  176","line":""},
{"lineNum":"  177","line":"  while grep -qE \'\\[(resync|check|recover|reshape)\' /proc/mdstat 2>/dev/null; do","class":"lineNoCov","hits":"0",},
{"lineNum":"  178","line":"    log_info \"RAID operation in progress. Waiting ${MDSTAT_CHECK_INTERVAL}s before rechecking...\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  179","line":"    sleep \"${MDSTAT_CHECK_INTERVAL}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  180","line":"  done"},
{"lineNum":"  181","line":"}"},
{"lineNum":"  182","line":""},
{"lineNum":"  183","line":"#######################################"},
{"lineNum":"  184","line":"# Lowers the I/O scheduling priority of the current process to idle."},
{"lineNum":"  185","line":"# This ensures the backup yields I/O to other processes."},
{"lineNum":"  186","line":"# Globals:"},
{"lineNum":"  187","line":"#   None"},
{"lineNum":"  188","line":"# Arguments:"},
{"lineNum":"  189","line":"#   None"},
{"lineNum":"  190","line":"#######################################"},
{"lineNum":"  191","line":"set_low_io_priority() {"},
{"lineNum":"  192","line":"  if ! command -v ionice &> /dev/null; then","class":"lineNoCov","hits":"0",},
{"lineNum":"  193","line":"    log_info \"ionice not found, skipping I/O priority adjustment.\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  194","line":"    return","class":"lineNoCov","hits":"0",},
{"lineNum":"  195","line":"  fi"},
{"lineNum":"  196","line":"  ionice -c3 -p $$","class":"lineNoCov","hits":"0",},
{"lineNum":"  197","line":"  log_info \"I/O priority set to idle (class 3).\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  198","line":"  log_debug \"ionice applied to PID $$\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  199","line":"}"},
{"lineNum":"  200","line":""},
{"lineNum":"  201","line":"#######################################"},
{"lineNum":"  202","line":"# Main function to orchestrate the script\'s execution."},
{"lineNum":"  203","line":"# Globals:"},
{"lineNum":"  204","line":"#   All (via function calls)"},
{"lineNum":"  205","line":"# Arguments:"},
{"lineNum":"  206","line":"#   All arguments passed to the script."},
{"lineNum":"  207","line":"#######################################"},
{"lineNum":"  208","line":"main() {"},
{"lineNum":"  209","line":"  parse_options \"$@\"","class":"lineCov","hits":"1","order":"602",},
{"lineNum":"  210","line":"  load_config || { log_error \"Configuration file not found.\"; exit 1; }","class":"lineNoCov","hits":"0",},
{"lineNum":"  211","line":"  validate_config \"SOURCE_DIR\" \"BACKUP_DIR\" \"int:KEEP_BACKUPS\" \"array:EXCLUDES\" || exit 1","class":"lineNoCov","hits":"0",},
{"lineNum":"  212","line":""},
{"lineNum":"  213","line":"  log_debug \"Configuration loaded: SOURCE_DIR=${SOURCE_DIR}, BACKUP_DIR=${BACKUP_DIR}, KEEP_BACKUPS=${KEEP_BACKUPS}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  214","line":"  log_debug \"Exclude patterns: ${EXCLUDES[*]}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  215","line":""},
{"lineNum":"  216","line":"  # Prevent concurrent backup runs using a lockfile."},
{"lineNum":"  217","line":"  local lock_file=\"${BACKUP_DIR}/.local-backup.lock\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  218","line":"  exec 9>\"${lock_file}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  219","line":"  if ! flock -n 9; then","class":"lineNoCov","hits":"0",},
{"lineNum":"  220","line":"    log_error \"Another backup is already running (lockfile: ${lock_file}). Exiting.\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  221","line":"    exit 1","class":"lineNoCov","hits":"0",},
{"lineNum":"  222","line":"  fi"},
{"lineNum":"  223","line":"  log_debug \"Lock acquired: ${lock_file}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  224","line":""},
{"lineNum":"  225","line":"  if [[ -n \"${LOG_FILE:-}\" ]]; then","class":"lineNoCov","hits":"0",},
{"lineNum":"  226","line":"    log_info \"Logging to: ${LOG_FILE}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  227","line":"  fi"},
{"lineNum":"  228","line":""},
{"lineNum":"  229","line":"  set_low_io_priority","class":"lineNoCov","hits":"0",},
{"lineNum":"  230","line":"  wait_for_raid","class":"lineNoCov","hits":"0",},
{"lineNum":"  231","line":""},
{"lineNum":"  232","line":"  run_backup","class":"lineNoCov","hits":"0",},
{"lineNum":"  233","line":"  run_prune","class":"lineNoCov","hits":"0",},
{"lineNum":"  234","line":"}"},
{"lineNum":"  235","line":""},
{"lineNum":"  236","line":"# Only run when executed, not when sourced — the test suite sources this file to exercise its"},
{"lineNum":"  237","line":"# individual functions."},
{"lineNum":"  238","line":"if [[ \"${BASH_SOURCE[0]}\" == \"${0}\" ]]; then","class":"lineCov","hits":"1","order":"591",},
{"lineNum":"  239","line":"  main \"$@\"","class":"lineCov","hits":"1","order":"605",},
{"lineNum":"  240","line":"fi"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "update-readme-table.sh", "date" : "2026-08-11 18:14:27", "instrumented" : 94, "covered" : 23,};
var merged_data = [];
