var data = {lines:[
{"lineNum":"    1","line":"#!/usr/bin/env bash"},
{"lineNum":"    2","line":"#"},
{"lineNum":"    3","line":"# A script to create an incremental backup and then automatically prune old ones"},
{"lineNum":"    4","line":"# based on a retention policy defined in its configuration file."},
{"lineNum":"    5","line":""},
{"lineNum":"    6","line":"# Exit immediately if a command exits with a non-zero status."},
{"lineNum":"    7","line":"set -o errexit","class":"lineCov","hits":"1","order":"768",},
{"lineNum":"    8","line":"# Treat unset variables as an error when substituting."},
{"lineNum":"    9","line":"set -o nounset","class":"lineCov","hits":"1","order":"774",},
{"lineNum":"   10","line":"# Pipelines return the exit status of the last command to fail."},
{"lineNum":"   11","line":"set -o pipefail","class":"lineCov","hits":"1","order":"778",},
{"lineNum":"   12","line":""},
{"lineNum":"   13","line":"# --- Global Constants ---"},
{"lineNum":"   14","line":"# The RAID status file and the polling interval are read from the environment when set, so the wait can"},
{"lineNum":"   15","line":"# be pointed at a fixture and driven at a usable speed; unset, they are the real file and five minutes."},
{"lineNum":"   16","line":": \"${MDSTAT:=/proc/mdstat}\"","class":"lineCov","hits":"1","order":"782",},
{"lineNum":"   17","line":": \"${MDSTAT_CHECK_INTERVAL:=300}\" # Seconds between MDSTAT checks","class":"lineCov","hits":"1","order":"787",},
{"lineNum":"   18","line":"readonly MDSTAT MDSTAT_CHECK_INTERVAL","class":"lineCov","hits":"1","order":"790",},
{"lineNum":"   19","line":""},
{"lineNum":"   20","line":"# --- Shared Library ---"},
{"lineNum":"   21","line":"_LOG_QUIET=\"true\"","class":"lineCov","hits":"1","order":"794",},
{"lineNum":"   22","line":"# shellcheck source=../lib/common.sh"},
{"lineNum":"   23","line":"source \"$(cd \"$(dirname \"$0\")\" && pwd -P)/../lib/common.sh\"","class":"lineCov","hits":"1","order":"804",},
{"lineNum":"   24","line":"# @include ../lib/common.sh"},
{"lineNum":"   25","line":""},
{"lineNum":"   26","line":"#######################################"},
{"lineNum":"   27","line":"# Prints the script\'s usage instructions to stderr."},
{"lineNum":"   28","line":"# Globals:"},
{"lineNum":"   29","line":"#   SCRIPT_NAME"},
{"lineNum":"   30","line":"# Arguments:"},
{"lineNum":"   31","line":"#   None"},
{"lineNum":"   32","line":"#######################################"},
{"lineNum":"   33","line":"show_usage() {"},
{"lineNum":"   34","line":"  cat <<EOF","class":"lineCov","hits":"1","order":"800",},
{"lineNum":"   35","line":"Usage: ${SCRIPT_NAME} [OPTIONS]"},
{"lineNum":"   36","line":"Creates an incremental rsync backup and prunes old backups."},
{"lineNum":"   37","line":""},
{"lineNum":"   38","line":"All settings are read from a configuration file"},
{"lineNum":"   39","line":"(e.g., /etc/${SCRIPT_NAME}.conf)."},
{"lineNum":"   40","line":""},
{"lineNum":"   41","line":"Options:"},
{"lineNum":"   42","line":"  -d    Debug mode (enables verbose logging to stderr)"},
{"lineNum":"   43","line":"  -h    Show this help message"},
{"lineNum":"   44","line":"EOF"},
{"lineNum":"   45","line":"}"},
{"lineNum":"   46","line":""},
{"lineNum":"   47","line":"#######################################"},
{"lineNum":"   48","line":"# Parses command-line options."},
{"lineNum":"   49","line":"# Globals:"},
{"lineNum":"   50","line":"#   IS_DEBUG_MODE"},
{"lineNum":"   51","line":"# Arguments:"},
{"lineNum":"   52","line":"#   Command-line arguments passed to the script."},
{"lineNum":"   53","line":"#######################################"},
{"lineNum":"   54","line":"parse_options() {"},
{"lineNum":"   55","line":"  while getopts \":dh\" opt; do","class":"lineCov","hits":"1","order":"784",},
{"lineNum":"   56","line":"    case \"${opt}\" in","class":"lineCov","hits":"1","order":"788",},
{"lineNum":"   57","line":"      d) enable_debug_mode ;;","class":"lineCov","hits":"1","order":"792",},
{"lineNum":"   58","line":"      h)"},
{"lineNum":"   59","line":"        show_usage","class":"lineCov","hits":"1","order":"772",},
{"lineNum":"   60","line":"        exit 0","class":"lineCov","hits":"1","order":"765",},
{"lineNum":"   61","line":"        ;;"},
{"lineNum":"   62","line":"      *)"},
{"lineNum":"   63","line":"        log_error \"Invalid option: -${OPTARG}\"","class":"lineCov","hits":"1","order":"799",},
{"lineNum":"   64","line":"        show_usage","class":"lineCov","hits":"1","order":"761",},
{"lineNum":"   65","line":"        exit 1","class":"lineCov","hits":"1","order":"766",},
{"lineNum":"   66","line":"        ;;"},
{"lineNum":"   67","line":"    esac"},
{"lineNum":"   68","line":"  done"},
{"lineNum":"   69","line":"  shift $((OPTIND - 1))","class":"lineCov","hits":"1","order":"776",},
{"lineNum":"   70","line":""},
{"lineNum":"   71","line":"  if (( $# > 0 )); then","class":"lineCov","hits":"1","order":"759",},
{"lineNum":"   72","line":"    log_error \"Unexpected arguments: $*\"","class":"lineCov","hits":"1","order":"758",},
{"lineNum":"   73","line":"    show_usage","class":"lineCov","hits":"1","order":"757",},
{"lineNum":"   74","line":"    exit 1","class":"lineCov","hits":"1","order":"780",},
{"lineNum":"   75","line":"  fi"},
{"lineNum":"   76","line":"}"},
{"lineNum":"   77","line":""},
{"lineNum":"   78","line":"#######################################"},
{"lineNum":"   79","line":"# Performs an incremental backup using rsync."},
{"lineNum":"   80","line":"# Globals:"},
{"lineNum":"   81","line":"#   SOURCE_DIR, BACKUP_DIR, EXCLUDES"},
{"lineNum":"   82","line":"#######################################"},
{"lineNum":"   83","line":"run_backup() {"},
{"lineNum":"   84","line":"  log_info \"Starting backup...\"","class":"lineCov","hits":"1","order":"781",},
{"lineNum":"   85","line":""},
{"lineNum":"   86","line":"  local datetime","class":"lineCov","hits":"1","order":"789",},
{"lineNum":"   87","line":"  datetime=\"$(date \'+%Y-%m-%d_%H:%M:%S\')\"","class":"lineCov","hits":"1","order":"755",},
{"lineNum":"   88","line":"  local backup_path=\"${BACKUP_DIR}/${datetime}\"","class":"lineCov","hits":"1","order":"769",},
{"lineNum":"   89","line":"  local latest_link=\"${BACKUP_DIR}/latest\"","class":"lineCov","hits":"1","order":"763",},
{"lineNum":"   90","line":""},
{"lineNum":"   91","line":"  local rsync_excludes=()","class":"lineCov","hits":"1","order":"754",},
{"lineNum":"   92","line":"  for pattern in \"${EXCLUDES[@]}\"; do","class":"lineCov","hits":"1","order":"797",},
{"lineNum":"   93","line":"    rsync_excludes+=(\"--exclude=${pattern}\")","class":"lineCov","hits":"1","order":"802",},
{"lineNum":"   94","line":"  done"},
{"lineNum":"   95","line":""},
{"lineNum":"   96","line":"  log_info \"Creating new backup at: ${backup_path}\"","class":"lineCov","hits":"1","order":"807",},
{"lineNum":"   97","line":"  mkdir -p \"${backup_path}\"","class":"lineCov","hits":"1","order":"808",},
{"lineNum":"   98","line":""},
{"lineNum":"   99","line":"  log_info \"Running rsync...\"","class":"lineCov","hits":"1","order":"810",},
{"lineNum":"  100","line":"  local rsync_exit_code=0","class":"lineCov","hits":"1","order":"812",},
{"lineNum":"  101","line":"  local rsync_opts=(-ax --delete)","class":"lineCov","hits":"1","order":"814",},
{"lineNum":"  102","line":""},
{"lineNum":"  103","line":"  # Show progress when running interactively"},
{"lineNum":"  104","line":"  if [[ -t 1 ]]; then","class":"lineCov","hits":"1","order":"815",},
{"lineNum":"  105","line":"    rsync_opts+=(--info=progress2)","class":"lineNoCov","hits":"0",},
{"lineNum":"  106","line":"  fi"},
{"lineNum":"  107","line":""},
{"lineNum":"  108","line":"  local -a rsync_args=(\"${rsync_opts[@]}\" \"${rsync_excludes[@]}\")","class":"lineCov","hits":"1","order":"818",},
{"lineNum":"  109","line":"  rsync_args+=(\"${SOURCE_DIR}/\" --link-dest \"${latest_link}\" \"${backup_path}\")","class":"lineCov","hits":"1","order":"819",},
{"lineNum":"  110","line":""},
{"lineNum":"  111","line":"  # Logged from the array that is actually run, so the two cannot describe different commands."},
{"lineNum":"  112","line":"  log_debug \"rsync command: rsync ${rsync_args[*]}\"","class":"lineCov","hits":"1","order":"821",},
{"lineNum":"  113","line":""},
{"lineNum":"  114","line":"  rsync \"${rsync_args[@]}\" || rsync_exit_code=$?","class":"lineCov","hits":"1","order":"786",},
{"lineNum":"  115","line":""},
{"lineNum":"  116","line":"  if [[ ${rsync_exit_code} -eq 0 ]]; then","class":"lineCov","hits":"1","order":"793",},
{"lineNum":"  117","line":"    log_info \"Rsync process completed successfully.\"","class":"lineCov","hits":"1","order":"822",},
{"lineNum":"  118","line":"  elif [[ ${rsync_exit_code} -eq 24 ]]; then","class":"lineCov","hits":"1","order":"773",},
{"lineNum":"  119","line":"    # This non-fatal error means some files vanished during transfer."},
{"lineNum":"  120","line":"    # It\'s common for temp files and is safe to ignore."},
{"lineNum":"  121","line":"    log_info \"Rsync completed with a non-fatal warning (code 24): Some source files vanished during transfer.\"","class":"lineCov","hits":"1","order":"824",},
{"lineNum":"  122","line":"  else"},
{"lineNum":"  123","line":"    log_error \"Rsync failed with a critical error (code ${rsync_exit_code}).\"","class":"lineCov","hits":"1","order":"762",},
{"lineNum":"  124","line":"    exit \"${rsync_exit_code}\"","class":"lineCov","hits":"1","order":"767",},
{"lineNum":"  125","line":"  fi"},
{"lineNum":"  126","line":""},
{"lineNum":"  127","line":"  log_info \"Updating the \'latest\' symbolic link.\"","class":"lineCov","hits":"1","order":"775",},
{"lineNum":"  128","line":"  ln -sfn \"${backup_path}\" \"${latest_link}\"","class":"lineCov","hits":"1","order":"777",},
{"lineNum":"  129","line":""},
{"lineNum":"  130","line":"  log_info \"Backup operation completed.\"","class":"lineCov","hits":"1","order":"760",},
{"lineNum":"  131","line":"}"},
{"lineNum":"  132","line":""},
{"lineNum":"  133","line":"#######################################"},
{"lineNum":"  134","line":"# Automatically prunes old backups based on the retention policy."},
{"lineNum":"  135","line":"# Globals:"},
{"lineNum":"  136","line":"#   BACKUP_DIR, KEEP_BACKUPS"},
{"lineNum":"  137","line":"#######################################"},
{"lineNum":"  138","line":"run_prune() {"},
{"lineNum":"  139","line":"  log_info \"Starting automatic backup pruning for: ${BACKUP_DIR}\"","class":"lineCov","hits":"1","order":"795",},
{"lineNum":"  140","line":""},
{"lineNum":"  141","line":"  mapfile -t backups < <(find \"${BACKUP_DIR}\" -maxdepth 1 -mindepth 1 -type d -name \'[0-9][0-9][0-9][0-9]-*\' | sort)","class":"lineCov","hits":"1","order":"805",},
{"lineNum":"  142","line":"  local total_backups=${#backups[@]}","class":"lineCov","hits":"1","order":"825",},
{"lineNum":"  143","line":"  log_debug \"Found ${total_backups} existing backup(s) in ${BACKUP_DIR}\"","class":"lineCov","hits":"1","order":"783",},
{"lineNum":"  144","line":""},
{"lineNum":"  145","line":"  if (( total_backups <= KEEP_BACKUPS )); then","class":"lineCov","hits":"1","order":"791",},
{"lineNum":"  146","line":"    log_info \"Total backups (${total_backups}) is not greater than the number to keep (${KEEP_BACKUPS}). No pruning needed.\"","class":"lineCov","hits":"1","order":"756",},
{"lineNum":"  147","line":"    return 0","class":"lineCov","hits":"1","order":"770",},
{"lineNum":"  148","line":"  fi"},
{"lineNum":"  149","line":""},
{"lineNum":"  150","line":"  local delete_count=$((total_backups - KEEP_BACKUPS))","class":"lineCov","hits":"1","order":"803",},
{"lineNum":"  151","line":"  local backups_to_delete=(\"${backups[@]:0:${delete_count}}\")","class":"lineCov","hits":"1","order":"798",},
{"lineNum":"  152","line":""},
{"lineNum":"  153","line":"  log_info \"Found ${total_backups} backups. Deleting ${delete_count} oldest backup(s)...\"","class":"lineCov","hits":"1","order":"752",},
{"lineNum":"  154","line":"  for backup_to_delete in \"${backups_to_delete[@]}\"; do","class":"lineCov","hits":"1","order":"751",},
{"lineNum":"  155","line":"    local backup_name","class":"lineCov","hits":"1","order":"750",},
{"lineNum":"  156","line":"    backup_name=$(basename \"${backup_to_delete}\")","class":"lineCov","hits":"1","order":"749",},
{"lineNum":"  157","line":"    log_info \"Deleting: ${backup_name}\"","class":"lineCov","hits":"1","order":"748",},
{"lineNum":"  158","line":"    if ! rm -rf \"${backup_to_delete}\"; then","class":"lineCov","hits":"1","order":"747",},
{"lineNum":"  159","line":"        log_error \"Failed to delete backup directory: ${backup_name}\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  160","line":"    fi"},
{"lineNum":"  161","line":"  done"},
{"lineNum":"  162","line":""},
{"lineNum":"  163","line":"  log_info \"Pruning complete!\"","class":"lineCov","hits":"1","order":"746",},
{"lineNum":"  164","line":"}"},
{"lineNum":"  165","line":""},
{"lineNum":"  166","line":"#######################################"},
{"lineNum":"  167","line":"# Waits for any active RAID resync/check/rebuild operations to finish."},
{"lineNum":"  168","line":"# Polls MDSTAT at a regular interval. If that file does not exist (e.g., no RAID"},
{"lineNum":"  169","line":"# arrays on this system), returns immediately."},
{"lineNum":"  170","line":"# Globals:"},
{"lineNum":"  171","line":"#   MDSTAT, MDSTAT_CHECK_INTERVAL"},
{"lineNum":"  172","line":"# Arguments:"},
{"lineNum":"  173","line":"#   None"},
{"lineNum":"  174","line":"#######################################"},
{"lineNum":"  175","line":"wait_for_raid() {"},
{"lineNum":"  176","line":"  if [[ ! -f \"${MDSTAT}\" ]]; then","class":"lineCov","hits":"1","order":"745",},
{"lineNum":"  177","line":"    log_debug \"${MDSTAT} not found, skipping RAID check.\"","class":"lineCov","hits":"1","order":"744",},
{"lineNum":"  178","line":"    return","class":"lineCov","hits":"1","order":"743",},
{"lineNum":"  179","line":"  fi"},
{"lineNum":"  180","line":""},
{"lineNum":"  181","line":"  # The kernel reports an operation in progress as a progress line — \"[=>...]  resync = 6.8% (…)\" — and a"},
{"lineNum":"  182","line":"  # queued one as \"resync=PENDING\" or \"resync=DELAYED\". Both forms put the operation name immediately"},
{"lineNum":"  183","line":"  # before an \"=\", which is what this matches; the trailing [a-z]* covers \"recovery\", the name used for a"},
{"lineNum":"  184","line":"  # rebuild. Matching a bracket before the name would find none of these, since the brackets in that line"},
{"lineNum":"  185","line":"  # hold the progress bar."},
{"lineNum":"  186","line":"  while grep -qE \'(resync|check|recover|reshape)[a-z]*[[:space:]]*=\' \"${MDSTAT}\" 2>/dev/null; do","class":"lineCov","hits":"1","order":"771",},
{"lineNum":"  187","line":"    log_info \"RAID operation in progress. Waiting ${MDSTAT_CHECK_INTERVAL}s before rechecking...\"","class":"lineCov","hits":"1","order":"764",},
{"lineNum":"  188","line":"    sleep \"${MDSTAT_CHECK_INTERVAL}\"","class":"lineCov","hits":"1","order":"742",},
{"lineNum":"  189","line":"  done"},
{"lineNum":"  190","line":"}"},
{"lineNum":"  191","line":""},
{"lineNum":"  192","line":"#######################################"},
{"lineNum":"  193","line":"# Lowers the I/O scheduling priority of the current process to idle."},
{"lineNum":"  194","line":"# This ensures the backup yields I/O to other processes."},
{"lineNum":"  195","line":"# Globals:"},
{"lineNum":"  196","line":"#   None"},
{"lineNum":"  197","line":"# Arguments:"},
{"lineNum":"  198","line":"#   None"},
{"lineNum":"  199","line":"#######################################"},
{"lineNum":"  200","line":"set_low_io_priority() {"},
{"lineNum":"  201","line":"  if ! command -v ionice &> /dev/null; then","class":"lineCov","hits":"1","order":"779",},
{"lineNum":"  202","line":"    log_info \"ionice not found, skipping I/O priority adjustment.\"","class":"lineNoCov","hits":"0",},
{"lineNum":"  203","line":"    return","class":"lineNoCov","hits":"0",},
{"lineNum":"  204","line":"  fi"},
{"lineNum":"  205","line":"  ionice -c3 -p $$","class":"lineCov","hits":"1","order":"741",},
{"lineNum":"  206","line":"  log_info \"I/O priority set to idle (class 3).\"","class":"lineCov","hits":"1","order":"740",},
{"lineNum":"  207","line":"  log_debug \"ionice applied to PID $$\"","class":"lineCov","hits":"1","order":"739",},
{"lineNum":"  208","line":"}"},
{"lineNum":"  209","line":""},
{"lineNum":"  210","line":"#######################################"},
{"lineNum":"  211","line":"# Main function to orchestrate the script\'s execution."},
{"lineNum":"  212","line":"# Globals:"},
{"lineNum":"  213","line":"#   All (via function calls)"},
{"lineNum":"  214","line":"# Arguments:"},
{"lineNum":"  215","line":"#   All arguments passed to the script."},
{"lineNum":"  216","line":"#######################################"},
{"lineNum":"  217","line":"main() {"},
{"lineNum":"  218","line":"  parse_options \"$@\"","class":"lineCov","hits":"1","order":"753",},
{"lineNum":"  219","line":"  load_config || { log_error \"Configuration file not found.\"; exit 1; }","class":"lineCov","hits":"1","order":"796",},
{"lineNum":"  220","line":"  validate_config \"SOURCE_DIR\" \"BACKUP_DIR\" \"int:KEEP_BACKUPS\" \"array:EXCLUDES\" || exit 1","class":"lineCov","hits":"1","order":"801",},
{"lineNum":"  221","line":""},
{"lineNum":"  222","line":"  log_debug \"Configuration loaded: SOURCE_DIR=${SOURCE_DIR}, BACKUP_DIR=${BACKUP_DIR}, KEEP_BACKUPS=${KEEP_BACKUPS}\"","class":"lineCov","hits":"1","order":"738",},
{"lineNum":"  223","line":"  log_debug \"Exclude patterns: ${EXCLUDES[*]}\"","class":"lineCov","hits":"1","order":"806",},
{"lineNum":"  224","line":""},
{"lineNum":"  225","line":"  # Prevent concurrent backup runs using a lockfile."},
{"lineNum":"  226","line":"  local lock_file=\"${BACKUP_DIR}/.local-backup.lock\"","class":"lineCov","hits":"1","order":"809",},
{"lineNum":"  227","line":"  exec 9>\"${lock_file}\"","class":"lineCov","hits":"1","order":"811",},
{"lineNum":"  228","line":"  if ! flock -n 9; then","class":"lineCov","hits":"1","order":"813",},
{"lineNum":"  229","line":"    log_error \"Another backup is already running (lockfile: ${lock_file}). Exiting.\"","class":"lineCov","hits":"1","order":"737",},
{"lineNum":"  230","line":"    exit 1","class":"lineCov","hits":"1","order":"736",},
{"lineNum":"  231","line":"  fi"},
{"lineNum":"  232","line":"  log_debug \"Lock acquired: ${lock_file}\"","class":"lineCov","hits":"1","order":"816",},
{"lineNum":"  233","line":""},
{"lineNum":"  234","line":"  if [[ -n \"${LOG_FILE:-}\" ]]; then","class":"lineCov","hits":"1","order":"735",},
{"lineNum":"  235","line":"    log_info \"Logging to: ${LOG_FILE}\"","class":"lineCov","hits":"1","order":"817",},
{"lineNum":"  236","line":"  fi"},
{"lineNum":"  237","line":""},
{"lineNum":"  238","line":"  set_low_io_priority","class":"lineCov","hits":"1","order":"734",},
{"lineNum":"  239","line":"  wait_for_raid","class":"lineCov","hits":"1","order":"820",},
{"lineNum":"  240","line":""},
{"lineNum":"  241","line":"  run_backup","class":"lineCov","hits":"1","order":"785",},
{"lineNum":"  242","line":"  run_prune","class":"lineCov","hits":"1","order":"733",},
{"lineNum":"  243","line":"}"},
{"lineNum":"  244","line":""},
{"lineNum":"  245","line":"# Only run when executed, not when sourced — the test suite sources this file to exercise its"},
{"lineNum":"  246","line":"# individual functions."},
{"lineNum":"  247","line":"if [[ \"${BASH_SOURCE[0]}\" == \"${0}\" ]]; then","class":"lineCov","hits":"1","order":"732",},
{"lineNum":"  248","line":"  main \"$@\"","class":"lineCov","hits":"1","order":"823",},
{"lineNum":"  249","line":"fi"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "update-readme-table.sh", "date" : "2026-08-14 14:53:45", "instrumented" : 98, "covered" : 94,};
var merged_data = [];
